### ISSUE TITLE
More INFO logs to filter

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#1054]
```
[INFO] Making sure inputs are available (this may take some time)
[INFO] Unlocking files
[INFO] Completed unlocking files
```

All of the above frame actual `unlock(ok)` results, if any unlocking is actually happening.

```
[INFO ] Creating a new annex repo at ...
```

The next is a candidate, but it is so frequent that we should double-check in the handbook whether it is not even a subject of discussion that explains that it needs to be ignored.

```
[INFO] Remote origin not usable by git-annex; setting annex-ignore
```

**Comment by adswa** [comment]
Found more:

* '[INFO] Recording unlocked state in git'
* '[INFO] Finished push of Dataset(/home/me/dl-101/DataLad-101/midterm_project)'
* [INFO] Initializing special remote datalad

I'll also add a few filters that didn't seem to work:

```
(r'\n\[INFO\] Downloading \S+ into .*', ''),
```

-> still included: 
```
 [INFO] Downloading 'https://www.tldp.org/LDP/Bash-Beginners-Guide/Bash-Beginners-
↪Guide.pdf' into '/home/me/dl-101/DataLad-101/books/bash_guide.pdf'
```

```
(r'\n\[INFO\] Attempting a clone into .*', ''),
```

-> still included:

```
[INFO] Attempting a clone into /home/me/dl-101/DataLad-101/recordings/longnow
```

```
\n\[INFO\] Fetching updates for Dataset.*
```
-> still included:

```
[INFO] Fetching updates for Dataset(/home/me/dl-101/mock_user/DataLad-101)
```

**Comment by mih** [comment]
Almost all of the above is done now. Looking through the logs I can see

```
[INFO] Making sure inputs are available (this may take some time)
```

unsuccessful filter, the actual message has a trailing newline.

```
[INFO] Copying non-annexed file or copy into non-annex dataset: ...
```

The full message is really ugly.

**Comment by mih** [comment]
Hopefully last run https://github.com/datalad-handbook/book/pull/1058

**Comment by mih** [comment]
Merged.
