### ISSUE TITLE
Stop referring to `datalad remove` for dropping

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#1079]
`drop` is the goto for this. This includes dropping an entire dataset (incl the repository).

**Comment by adswa** [comment]
I think in general, ``drop`` is given priority in the handbook. I git grepped, and ``remove`` is used in the file system chapter in one run-record and two in-text references in [this section](https://handbook.datalad.org/basics/101-136-filesystem.html#uninstalling-or-deleting-subdatasets) - and while this section mentions uninstall and remove, it starts with highlighting how to do it with drop.

There are also three instances in a code chapter I can probably easily remove.

**Comment by adswa** [comment]
pretty much fixed with #1111
