### ISSUE TITLE
Figures included via `.. image::`

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#1081]
The following graphics are not just decorative, but are included via `.. image::`, not `.. figure::`, hence lack a caption.

- [ ] `artwork/src/screenshot_midtermproject.png`
- [ ] `artwork/src/screenshot_submodule.png`
- [ ] `artwork/src/publishing/clone_local.svg`
- [ ] `artwork/src/publishing/clone_server.svg`
- [ ] `artwork/src/GIN_private.png`
- [ ] `artwork/src/command-structure.png`
- [ ] `artwork/src/img/remodnav2.png`

**Comment by adswa** [comment]
Many of them can't become figures because they're inside of findoutmores. For LaTeX, this becomes an environment (Minipage?) in which figures are disallowed. I have added comments about this where necessary, and changed every image where possible to figure.
