### ISSUE TITLE
Consistency in Language

### ISSUE THREAD

**Issue by loj** [datalad-handbook/book#11]
We should be consistent with how we capitalize/separate/hyphenate terms. I think it makes sense to follow the language used on the DataLad website and in the docs. However, I don't think we need to be beholden to how it's currently done. This can be an opportunity to assess if language should be tweaked, and later bring the other resources to the same standard.

Some inconsistencies I've noticed so far are:
* DataLad (vs Datalad or datalad)
* dataset (vs data set)
* subdataset (vs sub-dataset)
* metadata (vs meta data)

This doesn't need to be addressed now, and can be cleaned up as the handbook reaches completion. But, I wanted to start the conversation now to develop a running list so we can use these terms intentionally.

**Comment by mih** [comment]
I agree -- on both both content and timing. I'd say that the book content being consistent in itself is more important than being consistent with other material on datalad. Here is my vote on the specific examples above:

- DataLad (I am aware that even within this post I am not consistent ;-)
- dataset
- metadata
- subdataset

**Comment by adswa** [comment]
I also agree!
Within a few notes on datasets and first example, I'm trying to distinguish the general term "data set" (as used outside of DataLad to refer to any data-containing file(s)) and the DataLad specific term (DataLad dataset). I've so far used "data set" to refer to non-DataLad datasets and "dataset" plus 'DataLad' as a "prefix" (DataLad dataset) whenever possible for Datalad datasets, but if you have any suggestion how to improve this distinction please let me know.

**Comment by adswa** [comment]
Follow-up question: Does anyone have an opinion on whether to capitalize or not capitalize ``git`` (versus ``Git``)? Wikipedia stays with ``Git`` and I'm inclined to do the same.

**Comment by mih** [comment]
My vote is "Git"

**Comment by loj** [comment]
I also leans towards "Git".

**Comment by adswa** [comment]
The inconsistencies noted here are standardized in the book. I think it's okay to close this.
