### ISSUE TITLE
Datalad in EasyBuild

### ISSUE THREAD

**Issue by jkuhl-uni** [datalad-handbook/book#1117]
Hey there,

I just wanted to let you know, that [EasyBuild](https://github.com/easybuilders/easybuild-easyconfigs) just accepted my PR to introduce Datalad (v0.18.4) into the EasyBuild repo.
This could be useful information in chapter 3.1.2, as EasyBuild is a widely available installation platform for HPC.
While one needs to load Datalad as a module later, it could still be easier to convince your HPC-Admin to install this via EasyBuild, than systemwide :)
The workflow in [this paper](https://www.biorxiv.org/content/10.1101/2021.10.12.464122v1) is still valid and just needs a `module load` in the beginning.

**Comment by jkuhl-uni** [comment]
Hi,
I'm sorry, I was in the "advanced" section 3.1.2.
Yes, it would be of interest especially to HPC admins. I think technically it is possible to make the tooling available to everyone on a cluster, but usually only the admins are using it.
Admittedly, I have not yet read through your contributing guidelines properly, but I'd be happy to provide some input or write a short paragraph.

**Comment by adswa** [comment]
fixed in #1192 - thanks again!
