### ISSUE TITLE
Collaboration chapter `whereis` demo broken

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#1127]
It discusses a different between files (two vs three sources), but the logs are identical for both.

**Comment by adswa** [comment]
That is true. I am inclined to resolve this section and demo "whereis" maybe on a retrieved and unretrieved file

**Comment by adswa** [comment]
On closer look, it doesn't really add anything new to the previous chapter's ``whereis`` exploration on the different books. My suggestion would be to move the ``whereis`` part of ``101-116-sharelocal.rst`` into ``101-117-sharelocal2.rst``. It helps to reduce the length of the first "Share local" chapter and keeps the "Where's Waldo" chapter, and does a good job of demonstrating ``whereis``

**Comment by mih** [comment]
done, thx
