### ISSUE TITLE
Dedicated markup for "the lecturer says"

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#116]
Those bits often represent summaries, or abstract-type statements. I could be nice to have them presented with specific markup (an special icon in the margin of the PDF, like done in 'discovering statistics'). For that to become possible, we would not to start using a dedicated directive, and also have these bits universally serve this purpose.

@adswa how do you feel about this? Do you want to be this strict? Or do you prefer to keep it as is?

**Comment by mih** [comment]
To expand a little. The Field stats book uses a whole slew of personas to illustrate particular attitudes to topics. More on them in the section "Why do I keep seeing stupid faces everywhere?" ;-)

So far, I can see only two in here: lecturer and student.

**Comment by adswa** [comment]
I did not intentionally phrase them like this. Usually, I just wanted to create a bit more of a story than a textbook by having anyone say something. But I like Andy Fields style, he manages to continuously universally use those characters, and I think this is an interesting idea. I'll re-read what is already present and make up my mind on whether we could transform existing and yet-to-come sections into something like this. :-)

**Comment by adswa** [comment]
I have recruited Zebava to provide us with some sketches of these characters that we could consider including in such a markup. :wink:

**Comment by adswa** [comment]
I think a dedicated markup is not necessary. The book works quite well without it, and while it could make it better, I'm not sure that it is worth the effort for a dedicated markup and for refinement of everything that "the lecturer says". Instead, IMO, the summary sections at the end of each chapter serve as something similar to what we were envisioning in this issue. They wrap up the contents of the chapter in a concise manner, and they actually do have some form of dedicated mark-up: Stand-alone sections and a consistent structure.
