### ISSUE TITLE
Non-standard URL spec for RIA URLs

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#1194]
https://handbook.datalad.org/en/latest/beyond_basics/101-147-riastores.html shows:

```
ria+ssh://[user@]hostname:/absolute/path/to/ria-store
```

The `:` after the hostname should not be there. What follows is not a port specification.

A "URL" with this pattern still works, but should not be advertized, I think.

Report via @dickscheid

**Comment by adswa** [comment]
thanks much for the report, and sorry for the slow response. https://github.com/datalad-handbook/book/pull/1209 fixes it.
