### ISSUE TITLE
Call for contributions

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#12]
Once the desired structure of the book is determined, and the first pieces are in a shape that communicates the target style and audience, it would good to send out a call for contributions.

There are many small, but useful bits of information floating around that never had a place to live. Some of those might be a good fit for this effort.

**Comment by adswa** [comment]
Agreed. Just to make note of it I'm reminding us of the obvious:

We should make sure we by this time have a useful ``contributing.rst`` (currently, its empty) by then.

I think we will need to include some installation instructions to contributing to make sure contributers can build the docs locally, should they wish to. Maybe instructions about how to set up a virtual environment, how to install the requirements.txt within the virtual environment, and how to work with the extension you wrote.

**Comment by mih** [comment]
+1 on the CONTRIBUTING doc

**Comment by mih** [comment]
Just noticed that the link to the contribution guidelines on the frontpage is also broken.

**Comment by adswa** [comment]
I fixed the link in #103.

**Comment by adswa** [comment]
this may go hand in hand with #291.

**Comment by adswa** [comment]
this issue has served its purpose. We shall continue to try to find contributors, but we don't need to keep this open for this.
