### ISSUE TITLE
use the openneuro use case to show case how to paralellize across subdatasets

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#1202]
Was chatting with @melanieganz and realized that the openneuro use case could also showcase the 'parallel' subdataset processing to speed up install of the > 1000 datasets that openneuro now has. Otherwise users may be at it until the cows come home. 🐮 🐮 ➡️ 🏠

_Originally posted by @Remi-Gau in https://github.com/datalad-handbook/book/issues/1198#issuecomment-1840635351_

**Comment by adswa** [comment]
yes! indeed! (sorry, I saw that comment already, but forgot to reply. I will, after Monday, when the PhD things are done. :) )
