### ISSUE TITLE
DataCat Tutorial does not work as expected

### ISSUE THREAD

**Issue by tmheunis** [datalad-handbook/book#1210]
This could be related to the upgrade to `datalad-catalog 1.1.0`.

I detailed my steps here: https://github.com/datalad/datalad-catalog/issues/410

**Comment by jsheunis** [comment]
Thanks for the tag! will look into the issue.

**Comment by jsheunis** [comment]
Some remarks: https://github.com/datalad/datalad-catalog/issues/410#issuecomment-1894016378

Looks like there are bugs in 1.1.0, although I'm not sure yet whether they were introduced then or were in 1.0.1 all along. I will work on fixes.

W.r.t. the handbook chapter:

> Lastly, I think it would be a good idea to rerun the tutorial once the fixes are applied and capture screenshots of the output and update the handbook chapter with those. There have been catalog UI changes since that are not reflected in the current handbook chapter version.

**Comment by jsheunis** [comment]
This PR fixes the main bug and a few related things: https://github.com/datalad/datalad-catalog/pull/413

Next step will be to create a patch release for datalad-catalog and then redo and update the handbook chapter.
