### ISSUE TITLE
Add acknowledgements section

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#124]
People, institutions, funders, grant numbers, logos, etc.

**Comment by mih** [comment]
The 'people' aspect will be addressed by #140

**Comment by adswa** [comment]
Some of the funding was mentioned with #308, but there is more funding to be mentioned, right?

**Comment by adswa** [comment]
Will have an up-to-date overview in the last minor tune ups for the 0.13 release. closing for now.
