### ISSUE TITLE
Export to epub?

### ISSUE THREAD

**Issue by Gullumluvl** [datalad-handbook/book#1242]
### Is your feature request related to a problem?

Hi there,

I am really interested in reading this handbook from my e-reader, is there currently a way to get it in epub format? Otherwise how hard would it be to make it available?

Thanks a lot!

### Describe the solution you'd like

Ideally just download it from the website. Otherwise I could probably generate it for myself.

**Comment by adswa** [comment]
Hey, I believe you should be able to download it as epub, if you expand the menu in the bottom right corner: 

![Screenshot_20241215-214840~2](https://github.com/user-attachments/assets/07e7f18b-f29f-46b4-8f15-31d81f4d222a)

Let me know if it works as expected. :)

**Comment by Gullumluvl** [comment]
Oh so that was already possible thanks to ReadTheDocs... 🤦
Sorry about that and thanks a lot!
