### ISSUE TITLE
Sidebar taller than screen, doesn't scroll

### ISSUE THREAD

**Issue by effigies** [datalad-handbook/book#170]
In Firefox 68.0.2 on OSX, the sidebar has a large chunk of white space, pushing some of the contents off screen. Looks like #62 set the sidebars to fixed, which means those contents can't be scrolled to.

<div display="flex">
<img width="270" alt="Screen Shot 2019-09-12 at 11 34 07" src="https://user-images.githubusercontent.com/83442/64798597-477dba00-d551-11e9-9057-f433b33b213b.png">
<img width="250" alt="Screen Shot 2019-09-12 at 11 34 13" src="https://user-images.githubusercontent.com/83442/64798598-477dba00-d551-11e9-954e-109b851576c2.png">
</div>

**Comment by adswa** [comment]
Oh, thanks a lot for noticing and reporting! That indeed is inconvenient. I'll PR a fix in a bit.

**Comment by adswa** [comment]
Hey, @all-contributors, please add @effigies for bug
