### ISSUE TITLE
Use case: dataset hosting on GIN

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#186]
See https://github.com/datalad/datalad/issues/2680

This is particularly appealing for novice users, because:

- it is free
- it also uses git-annex under the hood, hence is fully compatible with everything we do on datalad
- unlike GitHub, has a UI that resolves annex a symlinks to the real file content

**Comment by adswa** [comment]
Rather than doing it as a use case, I'd suggest adding this as a section to the chapter I am starting in #111.

**Comment by mih** [comment]
Sounds good to me.
