### ISSUE TITLE
shorten full paths in the book?

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#189]
I guess we are to deal with those full paths at datalad level eventually (e.g. reduce use of full paths in the logs and Dataset's `repr` outputs), but I wondered if may be the book examples could be built/ran under some other shorter path than e.g. `/home/adina/repos/datalad-handbook/docs/_build/`, may be `/tmp/book` or alike?
That would also assure that book build/examples ran by different ppl would produce the same result/do not introduce a diff

**Comment by adswa** [comment]
I agree that the long paths can be confusing (and also make code snippets harder to read). I think  https://github.com/datalad-handbook/book/issues/53 is related/similar. I'm not an expert on this so I don't know whether it is possible/useful to have the workdir set up outside of the handbooks directory (@mih wrote the ``autorunrecord`` extension module we are using to set up working directories to execute code in). Currently, all code that needs a working directory is under ``/datalad-handbook/docs/_build/wdirs``, which assures that anyone can execute/build the book (relative path within the ``handbook`` directory), and also that the datasets and their content in the workdir lasts (as opposed to anything in ``/tmp/``; rerunning everything from scratch already takes a few minutes, it is immensely helpful to not have to rerun everything all of the time).

I wonder whether it may just be sufficient to have ``sed`` replace all ``/home/adina/repos/datalad-handbook/docs/_build/wdirs/`` in the examples with ``/home/someuser`` (or something similar) in the Makefile for a "quick fix", @mih?

**Comment by mih** [comment]
I'll look into it.
