### ISSUE TITLE
Add a "progress bar" or keep contents visible

### ISSUE THREAD

**Issue by lisanmo** [datalad-handbook/book#193]
**Is your feature request related to a problem? Please describe.**

When I was working my way through the "Basics" part (which I loved - I could follow along easily and even felt well entertained!) I got to the point where I had to decide to go home or keep working - I would have loved to see directly on the page I was where I was within the "Basics" section. Would I need only 10 minutes to finish it or a few more hours? Would this be a good point to take a break?
At the side and the bottom of the page I could only see the previous and next chapters, but no overview.

**Describe the solution you'd like**
I would like to have a kind of progress bar or overview of where exactly I am in the section or even entire book, so I can see more of what will come next and plan ahead.

**Describe alternatives you've considered**

I could have just opened the "Documentation overview" on the left of the page and return to the table of contents, find which chapter I am working on there and seen what is to come.

However,
a) that feels more disruptive to me than being able to check it while I remain on the site I am working on. Maybe the "Related Topics" section could be designed to expandable? Then you can minimise it if you don't want to be distracted by a full list of contents, but get an easy overview whenever you feel like it.
b) when following the book, I felt like I was in the "Basics" section and expected an "Advanced" section to follow upon completion. When opening the "Documentation overview", the section I was working on was now called "DataLad datasets". Because the chapters are listed there, it is no problem for navigation, but looking back it feels a bit disjunct (language-wise) from the "Basics" section the handbook leads you to. 

**Additional context**

I hope I could make clear what I mean! If not, please let me know!

**Comment by adswa** [comment]
Hey @lisanmo, thanks a lot for the feedback and the solutions you propose!
I have tried to play with both (full table of contents, progress bar). Displaying a full table of contents in the sidebar didn't work so well:

![image](https://user-images.githubusercontent.com/29738718/66068108-41c23580-e54d-11e9-9b74-62be2f56a340.png)

I'm inclined towards the progress bar, and I've been playing with it briefly (see  #196). So far in my toy examples I only have a progress bar per page (and I believe you'd rather have a progress bar related to a full "chapter" (e.g. all of DataLad's datasets - Exploring DataLad's core data structure, if I understand correctly):

![image](https://user-images.githubusercontent.com/29738718/66068385-c745e580-e54d-11e9-895c-68fa266d9f6e.png)

But I'm happy to extend my css/html/javascript a bit with this and find out whether I can make chapter-wise progress bars.

Also thanks for bringing up your confusion about "Basics" with several chapters but no "Advanced" part. This might indicate a need to explain the chapters in "Basics" a bit more in the section "How to use the handbook" or the general table of contents...

Finally: Hey @all-contributors, please add @lisanmo for ideas!

**Comment by adswa** [comment]
I will close this, as we got page wise progress bars (at least) in #196.
