### ISSUE TITLE
Pip-Problem with Datalad installation

### ISSUE THREAD

**Issue by LisaWiersch96** [datalad-handbook/book#236]
I tried to install Datalad on my MacBook and followed the description in the handbook. All the installations (Xcode, Homebrew, Git-annex, Python and pip) worked until the command "pip install datalad". The error message can be seen in the screenshot.
![Bildschirmfoto 2019-11-04 um 13 35 41](https://user-images.githubusercontent.com/57354773/68121415-01692500-ff08-11e9-83a8-b61d8dde5fdf.png)

The solution of the problem was to use pip 3, but my computer chose pip 2 as default. The right command can be seen in the following screenshot.
![Bildschirmfoto 2019-11-04 um 13 37 22](https://user-images.githubusercontent.com/57354773/68121510-3d03ef00-ff08-11e9-850c-28a504cf6487.png)

**Comment by adswa** [comment]
Thanks a lot for the bug report, @LisaWiersch96! Hey @all-contributors, please add @LisaWiersch96 for bug!
