### ISSUE TITLE
Installtion on most recent macOS

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#241]
Thanks to Jona and @aqw, I'm now in possession of ``bnbmac38``, a Mac book Pro with the most recent macOS release ``Catalina, 10.51.1``. I'm documenting what I encounter when installing DataLad:

- upon starting the computer and attempting a git command in the terminal, I get
```sh
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```
This seems to be a known issue for recent macOS versions: https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa. It was fixed with

```
xcode-select --install
```
and an update of Xcode Command Line tools.

- just as in #236, ``pip3`` was installed by default
- running ``pip3 install datalad`` resulted in 
```sh

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
Consider using the `--user` option or check the permissions.
```
- running ``pip3 install --user datalad`` succeeded, but
```sh
  The script chardetect is installed in '/Users/awagner/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script keyring is installed in '/Users/awagner/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script tqdm is installed in '/Users/awagner/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pyjwt is installed in '/Users/awagner/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

```

**Comment by PeerHerholz** [comment]
As you know, `catalina` created a lot of problems re permissions (all the mailing lists were full of it), hence would you recommend that folks use `chmod` to change the respective permission or go with the `--user` option? Thinking of `datalad` (which I of course do a lot, hehe), there might be more problems waiting around the corner (e.g., `git annex`, etc.). Hence, I would recommend that folks change permissions (if they can and/or allowed to). Unfortunately, my machines are to old to update to `catalina`, so I won't be able to help actively.

**Comment by adswa** [comment]
Thanks for the suggestion @PeerHerholz! I'm reunited with the Mac I was given on Tue or Wed and will try it out.

**Comment by aqw** [comment]
I would recommend against chmodding stuff outside of the home dir. Apple is continuing to iOS-ification of macOS, and the permission system will continue to expand, and not through the use of unix permissions.

I see two (sane) approaches when it comes to DataLad and macOS:
* build a proper, signed .pkg (way too much work at the moment)
* simply install w/ --user. (Installing globally with pip is already a bad idea on Linux, and macOS is usually a single user system anyway. Keep the stuff contained (as much as possible) inside a directory where we will have minimal interference from Apple.

The directions will likely need to add the appropriate dirs to the PATH. Do note that Catalina now defaults to `zsh`, but those upgrading will retain `bash`. Whatever one-liner provided to adjust the path will have either adjust both the `.zshrc` and `.bashrc`, or will need to sniff for the shell that is in use.

**Comment by aqw** [comment]
As another idea... (still too much effort for now, but a mid-way point between pip and an Apple package) is to make a `brew` package. As much as I dislike brew, it's the current most-beloved macOS package manager.

That way we get to stand on their shoulders and they deal with the permissions and path mess.

**Comment by adswa** [comment]
A brew package would be cool... (but, indeed, that's for later). wrt PATH I need to check my notes how  stackoverflow advised me to do it - I think there was a nice oneliner floating around somewhere... thx for your take on this, @aqw !

**Comment by PeerHerholz** [comment]
thx you very much for the pointers and information @aqw. Do you have any insights regarding `git annex` and `catalina`?

**Comment by adswa** [comment]
(less well informed comment from my side because it came up today: git-annex is available via brew, so ``brew install git-annex`` takes care of the installation... AND it is a good scapegoat to blame when things stop working)

**Comment by adswa** [comment]
The installation instructions are updated, I will close this.

**Comment by PeerHerholz** [comment]
I'm truly sorry for posting in an already closed issue, but I was wondering if a small note in the `macOS` related installation instructions mentioning the changes introduced in `catalina` might be helpful and/or necessary? This could, for example, include the pointes outlined by @aqw (e.g., `PATH` and used `shell`?
