### ISSUE TITLE
Check when exactly we need to `rev-parse` stuff like "HEAD~1"

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#258]
Felt a bit difficult to swallow during the course.

Also, in the context of re-run we might consider introducing tags earlier to be able to reference particular analysis components that we rerun (frequently).

Ping https://github.com/datalad/datalad/issues/3866

**Comment by adswa** [comment]
This issue has been open a while now, and more recent demonstrations have made use of tags and fixed commit hashes. I will close this.
