### ISSUE TITLE
Next datamanagement support session

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#264]
Short brainstorming with @mih:

- the next session should include an INM-7 workflow training:
   - Install a "training-superdataset" from Gitlab
        - [ ] create superdataset as part of a "INM-7 Training" group
        - [ ] create inm-7-training-config procedure
   - Compute average grey matter volume from CAT files in a large dataset
   - Throw away (drop) the input data afterwards
- The "technical" HAMMERPANTS usecase (#223) should link to the "user" HAMMERPANTS usecase (yet even to start a draft) (but likely not vice versa)
     - [x] finish writing #223 . Needs content on the inm7_config procedure, and can benefit from content/pictures of @mih's talk in Canada
     - [ ] write the HAMMERPANTS user-perspective use case. The basis for this can be the training outlined above
  
- The Git-annex/symlink session can be squeezed in to explain a bit about why the data store is set up the way it is.

**Comment by adswa** [comment]
hey @mih, do you now where I can read about these CAT files, and where on the cluster I could view a few of those to draft an example grey matter volumne analysis we could do as a hands-on exercise?

**Comment by mih** [comment]
http://www.neuro.uni-jena.de/cat/index.html#DOWNLOAD

has the manual (I don't know specific).

I think they live in such places:
```
$ ls -1 /data/BnB2/Derivatives/CAT/12.5/eNKI/sub-*/*/TIV*.txt |wc -l
1618
```

**Comment by adswa** [comment]
Thanks!

**Comment by adswa** [comment]
This was abandoned a year ago. I will close this.
