### ISSUE TITLE
Tiny typo munnin or muninn

### ISSUE THREAD

**Issue by lilikapa** [datalad-handbook/book#276]
Hi there dear DataLadders,

I identified a very tiny typo under the section "General prerequisites - The prompt":
The code snippet says  "munnin" for the machine, but the text in the paragraph below says "muninn." It is a very tiny thing, but I also wonder if this is the right way to issue a typo for possible future situations.

Cheers :)

**Comment by adswa** [comment]
Ha, thanks a lot for catching that! :-) Hey @all-contributors, please add @lilikapa for bug!
Issues are always highly appreciated - But if you want, you can of course also directly pull request a change!

I'll leave this issue open for the morning, so if you want to, you can fix it (my computers name is "muninn", so the error is indeed in the code snippet), if not I'll PR a fix after lunch :)

**Comment by adswa** [comment]
fixed in #278
