### ISSUE TITLE
Needed: section on/discussion of datalad publish

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#281]
Since it is currently an issue in a discussion behind me, it occurred to me that we need to discuss the functions of ``datalad publish`` more. At this point, it only appears in the [exemplary YODA project](http://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html), and in there, the command does not receive much attention, and it will/may come in #111 (when publishing a dataset to GitHub with a publication-dependency to a Dropbox storage). What it primarily needs, I think, is a discussion on the ``--transfer-data`` option, and (I assume?) also a hidden section on the Git-annex branch would be useful (which I still need to understand in depth, as well)

**Comment by mih** [comment]
Oh yes! But https://github.com/datalad/datalad/projects/9

There is much to do in datalad itself in that respect.
