### ISSUE TITLE
Potential FAQs from Neurostars

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#285]
I'm looking through Neurostars for questions on DataLad. Maybe they can be useful FAQs:

- [x] Behavior with large amounts of files. Given the INM7 data store experiences, based on the outcomes, we could report benchmarks, limitations, rules of thumb
- [x] How do to add a subdataset *later* into a superdataset (i.e., after creation without -d)
- [x] How does data access can be restricted when sharing? (maybe a sketch of general considerations)
- [x] ``datalad run`` on HPC systems (i.e. batch schedulling)
- [x] DataLad versus Gin versus git LFS versus ... versus...
- [x] Is DataLad a "standard"?

**Comment by PeerHerholz** [comment]
How about using `DataLad containers` as this might become a big(ger) thing the more folks use `DataLad` and `containers`? An example post is e.g. [here](https://neurostars.org/t/using-fmriprep-with-datalad-containers-run/5327).

**Comment by adswa** [comment]
Hey @PeerHerholz , thanks, yes, that sounds sensible!
I'm preparing an OHBM submission (#310), \*goes on one knee\*: "Would you want to be my co-author?"

hey @all-contributors please add @PeerHerholz for ideas

**Comment by PeerHerholz** [comment]
Hey @adswa,

thanks for the fast reply. 
*laying down the floor*: " I'm not worthy.".  --> I don't think my small contributions (that mainly create more work for you) justify my existence as a co-author...However, if you insist, I'm more than happy to take this as an opportunity to finally become more involved.

**Comment by adswa** [comment]
Hehe, let me be brash: I insist ;-)

**Comment by PeerHerholz** [comment]
I guess, I can't say no then, hehe. I'll upload my `.json` file in the corresponding thread. Thanks a lot!

**Comment by adswa** [comment]
all those "potentials questions from neurostars" are finally addressed in the book or in an upcoming PR
