### ISSUE TITLE
Question: Shall we come out of the closet with 0.12 release?

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#291]
Currently, the existence of the handbook is mainly communicated via talks, and the front page says "We're alpha-stage". Shall we "officially" announce that the handbook exists (e.g., via Twitter) when DataLad 0.12 is released, and in the same vein update the note on the front page from alpha-stage to beta-stage?

**Comment by mih** [comment]
Yes, we should! And Datalad 0.12 should also come out of the closet ;-)

**Comment by adswa** [comment]
I'm closing this, and we'll wait for https://github.com/datalad/datalad/pull/3993 to release :wink:
