### ISSUE TITLE
When populating a dataset, how to log where data came from when source not a 'dataset'

### ISSUE THREAD

**Issue by pvavra** [datalad-handbook/book#293]
When populating a new dataset [in this chapter](http://handbook.datalad.org/en/latest/basics/101-102-populate.html), the data are grabbed by `wget ..`. It would be good to show how to include the related URL into the datalad's record.

Actual use case: 
I'm grabbing dicom files from a file-server (i.e. _not_ a datalad dataset and hence cannot use `datalad install` as far as I understand that command), and would like to log the source of the raw data as well.

I guess I can use `datalad run` to execute my `rsync` call and log that, but would be good to show this already this early in the populate chapter, I think.

**Comment by adswa** [comment]
Hey @pvavra, thanks for getting in touch!

I believe the command that you are looking for might be `datalad download-url` (see the documentation [here](http://docs.datalad.org/en/latest/generated/man/datalad-download-url.html)). Afterwards, a ``git annex whereis`` will be able to report the URL as a source for the data, and ``datalad get`` would be able to reobtain the content should you ``datalad drop`` file content or share the dataset (given the url remains valid of course).

I agree that it may be useful to show early on how to accurately capture provenance of a datasets' contents. The tricky bit is how to not overwhelm in the beginning already (I chose to use a plain download to stay as close to a naive users workflows as possible, and to have ``create``, ``save``, ``status``, and ``install`` as the "basic" set of commands in the first chapter). Nevertheless, so far ``datalad download-url`` does not have a very prominent role in the handbook (it gets somewhat hastily introduced in chapter [Networking](http://handbook.datalad.org/en/latest/basics/101-121-siblings.html)). I'll ponder on this and would be glad if I could get your feedback on some solutions I'll try out!

**Comment by pvavra** [comment]
@adswa beware what you thank me for. many more issues might be coming ;)

just fyi: a master-student of mine is working through the handbook and trying to use hirni for her master-thesis project now. feel free to use us to "test" different solutions. 

I hadn't spotted the `datalad download-url` command before. 
For a `wget `, this is a nice wrapper, but for having to `rsync `/`scp` using `ssh` it doesn't seem work, there my `datalad run ..` approach is the only solution, right?

I agree that overwhelming readers should be avoided. However, teaching "bad practices" (like not capturing the origin of the data during the populating step) should be an even more important aspect to consider, IMHO. 

There are three options, I think:
Create an "advanced populating" section at the end of the chapter 
a dedicated page for the same content
or use a "Find out more" box (only viable if this would be mentioned very briefly)

Concerning "dedicated page":
The [Networking](http://handbook.datalad.org/en/latest/basics/101-121-siblings.html) chapter is not appropriate, I think, because it talks more about related datasets. Here, we are talking about creating the very first one.

My personal preference would be the first option, i.e. a subsection on "tracking the data sources". This section would introduce the notion that one might be interested in tracking the sources of the data, and hence have a provenance-teaching aspect to it.

**Comment by adswa** [comment]
Ah, gotcha. Yes, as far as I'm aware ``datalad download-url`` does not take ssh URLs (see [this related discussion](https://git-annex.branchable.com/todo/support_ssh__58____47____47___or_sftp__58____47____47___urls_via___34__built-in__34___ssh_support/). 

Then, yes, I suppose capturing the copying with datalad run is correct and sensible.
(You have probably already considered and decided against it, I just want to note this here explicitly: turning the DICOM location into a dataset with ``datalad create -f`` and ``datalad save .`` would also make ``datalad install`` possible, e.g. as detailed in the hidden section "creating an independent input dataset" in the [YODA project chapter](http://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html)).

I can assure you that I am grateful for every single issue you or your students will be filing ;-) Its very helpful to get feedback from as many people as possible, and to also learn about their use cases. Thx for the information about your masters student. This may be sufficient to get my motivation up to incorporate ``datalad-hirni`` in #234. As a FYI for your student: I believe @bpoldrack will give a demo/talk about ``datalad-hirni`` in an upcoming DataLad call.

As for your suggestions: Yes, I reached a very similar set of potential solutions. Thanks for sharing your preference!

**Comment by pvavra** [comment]
concerning the `datalad create -f` option:
This would only work if I had the option to write to the DICOM-hosting server. But in this specific instance, I have only read access as the server is hosted by another institution..

**Comment by bpoldrack** [comment]
> As a FYI for your student: I believe @bpoldrack will give a demo/talk about datalad-hirni in an upcoming DataLad call.

That particular call will be on Tue, December 17th, 15:00 CET.
https://meet.jit.si/DataLad

@pvavra : Independently from that, she's welcome to contact me directly. I might be able to help faster than I can improve on hirni's documentation.

**Comment by bpoldrack** [comment]
Actually, if she wants to join that call, let me know. We might switch to zoom for that one call to record it. So, the link might change.
