### ISSUE TITLE
Resources to draw from

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#3]
- Tutorial on a complete, and reproducible neuroimaging analysis: http://www.repronim.org/ohbm2018-training/03-01-reproin/
- Slides of a short talk on the YODA principles https://github.com/myyoda/talk-principles
- datalad hirni demos https://datalad-hirni.readthedocs.io/en/latest/demos.html
- figure of the target API structure
![image](https://user-images.githubusercontent.com/136479/59693448-3b4ebe80-91e7-11e9-8ace-98a4827f83d9.png)

**Comment by adswa** [comment]
here is a very concise Sphinx cheat sheet: https://matplotlib.org/sampledoc/cheatsheet.html

**Comment by mih** [comment]
Here is the source SVG of a poster that has some figure elements that could be useful: https://github.com/myyoda/poster/blob/master/ohbm2018.svg

**Comment by mih** [comment]
Closing this info issue

**Comment by adswa** [comment]
Asking for #290: does the original svg for the graphic still exist somewhere?

**Comment by mih** [comment]
I am confident that it does. Location is ToDo ;-)
