### ISSUE TITLE
Need for a "Going big" section/chapter?

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#306]
There are recent experiences about DataLads behavior with very large datasets, e.g. our own HCP endeavor or https://neurostars.org/t/datalad-containers-data-organization-multiple-questions. We might turn some lessons learned from these attempts (benchmarks, limits, ...) into a standalone section that outlines best-practices, tricks for faster performance, and caveats..

**Comment by mih** [comment]
There is a need for clarity in this area, but I am afraid that we are too early for conclusions. Here is the latest of my activities in this regard: https://github.com/datalad/datalad/issues/3869

**Comment by mih** [comment]
Also: https://github.com/datalad/datalad/issues/3655

**Comment by adswa** [comment]
Also: https://github.com/datalad/datalad/issues/4184
