### ISSUE TITLE
datalad search section in "Use Cases"?

### ISSUE THREAD

**Issue by PeerHerholz** [datalad-handbook/book#324]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a specific problem.

**Describe the solution you'd like**
While trying to answer a [question on neurostars regarding dataset search](https://neurostars.org/t/fast-tr-open-task-fmri-datasets/5601), I tried to incorporate a `datalad` solution through the `datalad search` functionality. While going through the handbook I thought about including a corresponding section in ["Use Cases"](http://handbook.datalad.org/en/latest/#use-cases) (or somewhere else) might be helpful. 

**Describe alternatives you've considered**
I did not consider any alternatives as I wanted to propose this addition to the creators, contributors and users before undertaking any precise steps.

I'm truly sorry if I missed already existing respective content.

Best, Peer

**Comment by adswa** [comment]
Hey @PeerHerholz, thx! It would be a very good addition. I've tried to tackle it once before (here: https://github.com/datalad-handbook/book/pull/202), and we want to spice up the existing neuroimaging usecase with a metadata search (see #209, but before that #234 needs to happen). Unfortunately, we haven't yet gotten far with it, and especially for #202, further development is highly dependent on simultaneous co-development of [datalad metalad](https://github.com/datalad/datalad-metalad). It is high on our list for 2020, both for book content and software development!

**Comment by PeerHerholz** [comment]
Hi @adswa,

oh wow, I missed a lot of already existing respective content. Sorry for that. 
This all sounds very cool, as usual: amazing work! Happy to help where I can (if help needed).

**Comment by mih** [comment]
`search` has been deprecated. This is not going to happen.
