### ISSUE TITLE
Restructure sections

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#35]
Proposal (only set of files relevant, within-chapter-order would stay the same as it is now):

### intro
duction
installation
philosophy

### basics
datasets
howto

### usecases
remodnav

plus a logical chapter "appendix" (there is not necessarily an editable source file for each bit, some of it is generated by sphinx)

glossary
index
search
contributing

@loj @adswa Are you OK with such a change? Would open a separate PR in that case.

**Comment by adswa** [comment]
yes, that sounds sensible to me.

**Comment by mih** [comment]
Cool, thx -- will do on top of #31.
