### ISSUE TITLE
[suggestion] System Usability Scale (SUS) report from course attendees

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#355]
**Is your feature request related to a problem? Please describe.**

We don't have a standardized metric for usability (UX) "feedback"

**Describe the solution you'd like**

Adopt something like https://www.usability.gov/how-to-and-tools/methods/system-usability-scale.html and use that questionnaire at training workshops (after users had a chance to use datalad for a while).

**Comment by adswa** [comment]
I think that's a really cool idea. For starters, I have created a [google form](https://forms.gle/FkNEc7HVaZU5RTYP6), and #356 puts it into the sidebar and on the contributing page. Feedback on what else could be in the form or where in the book it should be referenced appreciated!

**Comment by adswa** [comment]
This was implemented in #356, so its there. We need to start highlighting it/pointing people to it.
