### ISSUE TITLE
Import use-case docs/demos from other sources

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#36]
These are all floating around:

- [x] http://docs.datalad.org/en/latest/usecases/simple_provenance_tracking.html https://github.com/datalad/datalad.org/blob/master/content/asciicast/simple_provenance_tracking.sh
- [x] http://docs.datalad.org/en/latest/generated/examples/3rdparty_analysis_workflow.html
- [x] https://github.com/datalad/datalad.org/blob/master/content/asciicast/heudiconv_dicom_to_bids.sh
- [x] https://github.com/datalad/datalad.org/blob/master/content/asciicast/publish_on_github.sh
- [x] https://github.com/datalad/datalad.org/blob/master/content/asciicast/reproducible_analysis.sh
- [x] https://github.com/datalad/datalad.org/blob/master/content/asciicast/seamless_nested_repos.sh
- [ ] https://github.com/datalad/datalad.org/blob/master/content/asciicast/track_data_from_webpage.sh

Some are very technical, some are very special interest. If we want to aim for a common narrative (example dataset), all of them would need to be adjusted (but with few exceptions also could be adjusted).

In any case, collecting all these things in a single place, rather than scattering them all over the web would be attractive to me.

What do you think?

**Comment by adswa** [comment]
Very, very helpful!

I agree that we should have all of this collected in a single place. It makes life easier for anyone interested in DataLad, and it also saves us work. Personally, I would aim for rewriting them into how we write this book plus adjusting to the soon-to-come common narrative, and cite the originals appropriately as sources. In addition, we could curate an "Additional resources"  document with such pointers.

**Comment by mih** [comment]
Here is one more: http://mvdoc.me/2017/data-version-control-with-datalad-and-git-annex-a-modest-example.html

**Comment by mih** [comment]
I think we have a wide range of use cases covered, and presently, I think.
