### ISSUE TITLE
Update the HAMMERPANTS use cases when clone-related PRs are merged

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#364]
- [x] https://github.com/datalad/datalad/pull/4022
- [ ] annex object tree layout v2 uses hashdir-mixed now (figure is showing hashdir-lower still)

**Comment by adswa** [comment]
Are any pointers beyond this PR for me that contain relevant changes? I will start to address this.

**Comment by mih** [comment]
This is the only other one that comes to my mind: https://github.com/datalad/datalad/pull/4073 It ensures that any dataset with a RIA url generator config will propagate this information to any obtained subdataset. This makes it possible to only have the generator config in the top-most superdataset, and have resolution work nevertheless at any depth. This is done once, for example, here: https://github.com/datalad-datasets/human-connectome-project-openaccess/blob/master/.datalad/config#L3-L4 to make it work for any of its 4.5k subdatasets, without having to preconfigure each and everyone of them.
