### ISSUE TITLE
High-resolution cheat sheet for poster printing

### ISSUE THREAD

**Issue by AlexandreHutton** [datalad-handbook/book#368]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A high-resolution version of the current .png. ~(9600x7200px).

**Describe alternatives you've considered**
None.

**Additional context**
Depending on how the cheat sheet was made, this might be just changing settings when exporting the file.

**Comment by mih** [comment]
Do you really need a raster image, or would an "arbitrary resolution" PDF do too?

**Comment by AlexandreHutton** [comment]
Yep, I'd been using the .png from the website rather than the .pdf that's on this repo. That solves it, thanks!
