### ISSUE TITLE
Close Windows subsystem for linux installation instructions?

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#382]
I believe the current state of things is:
- WSL1 is unusable and a pain to install
- WSL2 is more usable, with somewhat limited access to linux filesystem from windows (IIRC symlinks did not work?), and an even larger pain to install
- Windows native is still Windows, but works and installation is doable

Shall we remove the WSL instructions?

**Comment by mih** [comment]
Here is a new page with the most comprehensive guides for WSL that I am aware of: https://ubuntu.com/wsl

That also has little/nothing on the interaction of native windows apps with the filesystem inside WSL. This would be the crucial part AFAICS.

**Comment by adswa** [comment]
Thanks for the link. I have updated #397 with this.
