### ISSUE TITLE
add handbook favicon

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#407]
ATM the stock one is used: https://github.com/datalad-handbook/book/blob/44827bcc3f57dc3dca63a656aed221fe839296cf/docs/_templates/layout.html#L26 from readthedocs

**Comment by adswa** [comment]
Thanks for the suggestion!

**Comment by adswa** [comment]
BTW: the datalad docs also use the readthedocs favicons :thinking:, @yarikoptic

**Comment by yarikoptic** [comment]
datalad is the land of ample opportunities to contribute! ;)
