### ISSUE TITLE
DataLad installation instructions for Windows

### ISSUE THREAD

**Issue by hbaagil** [datalad-handbook/book#409]
Hello,

I am new to Datalad and using Windows. I tried to install everything according to the handbook, however I keep getting the message: 
'datalad' is not recognized as an internal or external command,
operable program or batch file.
I have added the PATH to the environment variable. If I type the command: where is datalad, I do get a path C:\Users\hbaagil\AppData\Roaming\Python\Python37\Scripts\datalad

Any help would be much appreciated!
Cheers,
Hamzah

**Comment by adswa** [comment]
Hi @hbaagil , thanks for getting in touch!
Could you tell me a bit more about
- which operating system you use precisely (I assume Windows 10, but I wanted to be sure)
- which installation method did you follow? I think there are still 3 different ones in the book (native installation, installation in WSL1, installation in WSL2)
- from which shell do you try to invoke the command? I.e., the Anaconda prompt, the powershell, ...?

Will try to help as best as I can, and we can hopefully enhance the installation instructions in the handbook once we have figured it out for you.

**Comment by hbaagil** [comment]
@adswa, thank you for the quick reply!

- I am using Windows 10
- Installation method: native installation within Windows
- Shell: Anaconda promt

Cheers!

-

**Comment by adswa** [comment]
I quickly grabbed a Windows machine (Windows 10 Home, version 1909, system build 18363.657) and created a new user account to try the installation myself. I indeed did run into a similar situation: I could not access datalad from the command line (however, importing it in a Python session worked fine). I'll try to see how this can be fixed, but I don't think I can update the installation instructions very fast (I myself am using Linux, and my understanding of how Windows works is very limited). However, there is a workaround and I'm describing it below. Please bear with me through a detailed installation instruction, but I want to be absolutely clear about what I did in case others stumble across this issue.

Here is what I do, from the start:

- Step 1: Download Miniconda3 for Windows 64bit from [here](https://docs.conda.io/en/latest/miniconda.html), and install it with the installer.
- Step 2: Search for Anaconda Prompt in the search bar and open an App called "Anaconda Prompt (Miniconda3)
- (Step 3: Its optional, but useful to create a [virtual environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html). I'm creating a virtual environment (called `dl`) by typing `conda create -n dl python=3.7.4`. Afterwards, I activate it with `conda activate dl`)
- Step 4: Install Git with `conda install -c conda-forge git`. Afterwards,I can use Git commands (try by running `git help -a`)
- Step 5: Install git-annex from [here](https://downloads.kitenet.net/git-annex/windows/current/). Importantly, save it into the directory in which Miniconda is installed (for me, that's C:/Users/adina/Miniconda3/Library). Afterwards, I close the Miniconda prompt and start a new one, and check that I can use git-annex (By running `git-annex` - it lists all available commands for me)
- If I now installed datalad in my virutal environment with `pip install datalad~=0.12`, I was not able to access it via the command line (however, importing in Python with `python -c "import datalad.api as dl"` worked). Until we've figured out why, here is a work-around: Clone the datalad GitHub repository and install it from there:
- Step 6: Clone the GitHub repo of datalad with `git clone https://github.com/datalad/datalad.git`. It should clone the repository into a directory datalad. Switch into this directory with `cd datalad`.
- Step 7: Install datalad from the repository by running `pip install -r requirements`
- Afterwards, datalad should be accessible from the command line


Please let me know whether this solves it for you!

**Comment by hbaagil** [comment]
I followed all the steps. Unfortunately for the last step 7:
I tried running: pip install -r requirements
and keep getting an error message: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'

Cheers!

**Comment by adswa** [comment]
Whops, sorry, it should be `pip install requirements.txt`. I will update my comment.

**Comment by hbaagil** [comment]
Thank you! Datalad seems to be working, but command line which used to work such as:
ls doesn't seem to be working anymore 
'ls' is not recognized as an internal or external command,
operable program or batch file.
Maybe I should rather switch to Linux for datalad...

**Comment by adswa** [comment]
> Maybe I should rather switch to Linux for datalad...

Its certainly much much easier to use DataLad (and many other programs) with Linux (sorry :( ). But having come from 10+ years of using Windows before switching to Debian myself, I didn't regret changing operating systems at all, quite the opposite - almost all of the scientific computing and software stuff I do is so much easier now. 

In any case, installing DataLad would not influence your shell's commands like this. I don't see a way in which a `pip install -r requirements.txt` would previously working commands of your shell inaccessible.
> 'ls' is not recognized as an internal or external command, operable program or batch file.

The most plausible thing I can think of
- You might be in a virtualenvironment which lacks e.g. a Git installation, or, similarly, outside of the virtualenvironment that contains a Git installation. If you have followed by steps above, make sure that you are in the same virtualenv in which you installed Git. (Windows by default does not have standard Unix commands such as `ls` (I think the Windows equivalent is `dir`, if I am not mistraken). Commands such as `ls` or `cd` come with other installations such as Git -- if you are in an environment without this installation, the commands will not be recognized).

**Comment by hbaagil** [comment]
Thank you for your help, much appreciated!

**Comment by adswa** [comment]
Update: This is fixed now. There is a new DataLad release ([0.12.4](https://github.com/datalad/datalad/releases/tag/0.12.4)) with working entrypoints on Windows. The installation instructions in the handbook for Windows should work again now. Details on issue: https://github.com/datalad/datalad/issues/4315
