### ISSUE TITLE
Where is the favicon?

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#413]
I thought I added a Favicon with #411 and #408, and I'm sure I had seen it already - but it is currently nowhere to be found.

This is how I tried to set it in [docs/_templates/layout.html](https://github.com/datalad-handbook/book/blob/master/docs/_templates/layout.html):

```html
 <link rel="icon" type="image/png" href="https://github.com/datalad-handbook/book/blob/master/docs/_static/favicon.png">
```

**Comment by adswa** [comment]
Also, if I visit the handbook with chromium, I get the readthedocs icon. Why??

**Comment by aqw** [comment]
There's multiple issues at play here:

* you're not linking to the raw icon (`https://raw.githubusercontent.com/datalad-handbook/book/master/docs/_static/favicon.png`)
* you shouldn't link cross-domain like that. use the one shipped on-site (`http://handbook.datalad.org/en/latest/_static/favicon.png`)
* favicons are ancient, and thus there is a lot of legacy cruft around their behavior:
   - multiple image formats and sizes are needed
   - some browsers require that it's located at `/`
   - they are aggressively cached (often forever), which is likely why you're seeing the read-the-docs favicon in chromium. Faux versioning in the URL can force a cache reload
* visually, the favicon you're linking to is too busy for 16x16 (the default favicon size), and is distorted when at high res.

Next time we're on a video call, I can explain some of the ways to go about setting this up.

**Comment by adswa** [comment]
I somehow missed this, sorry, and thanks! I would appreciate a brain dump on favicons, but its not urgent :)

**Comment by adswa** [comment]
We got a Favicon in #448! It better stays this time. Turns out, Sphinx does things differently, and there is a configuration option I wasn't aware of :woman_facepalming: 
Thanks for the help, @aqw !
