### ISSUE TITLE
CentOS install docs

### ISSUE THREAD

**Issue by glatard** [datalad-handbook/book#434]
**Is your feature request related to a problem? Please describe.**

The install section misses install instructions for CentOS/RH/Fedora distributions. This is an issue in particular to install git-annex.

**Describe the solution you'd like**

Link to the git-annex installation instructions [here](https://git-annex.branchable.com/install/rpm_standalone/).

**Describe alternatives you've considered**

Searching through my emails for that link: https://git-annex.branchable.com/install/rpm_standalone/ :)

**Comment by adswa** [comment]
Thanks a lot, @glatard!
I'd consider it a bug of the handbook to not have installation instructions for rpm-based distributions, so if you're okay with it I'd like to recognize this as a contribution to the handbook. :)

@all-contributors please add @glatard for bug

Let me know if you're fine with this and I'll merge the PR that the bots puts up.

**Comment by glatard** [comment]
sounds good, thanks!
