### ISSUE TITLE
Guidelines/Example for FSL analysis output capture

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#437]
This may be suitable for a special-interest use-case, but could also be framed in a more general fashion. The particular situation is this:

FSL analysis output captured in a single dataset. It ends up being 400GB (fine), but also 400k files (problematic). One approach could be to split the 1st-level results into per subject output datasets, but another approach would be to limit a-priori what is being captured. These alternative strategies could be the focus of a section/chapter.

In my case, the dataset was configured with `text2git`, which sounded sensible, but led to 320k text files to be committed to Git (total of 4.3GB). Maybe `text2git` docs should get a qualifier stating many many small files are still an issue.

The FSL output also contains less valuable for provenance tracking, but still make up a large number of files (e.g. the `tsplot/` FEAT output that is of limited value for many analysis once the QC is done). Those could be ignore. The docs could provide some guidelines what gotchas one could face when scaling up, and what compromises are possible, when one does not want to face the complexities of splitting output across multiple datasets.

**Comment by adswa** [comment]
I think that this would be a valuable addition to the handbook and much needed guidance. I have started a section on scaling up (#414) - We could turn this into its own chapter. The first section of this chapter (#414 would be a candidate for this) could introduce general caveats and principles (why is it a problem, what are rules of thumbs/benchmarks), subsequent chapters introduce special cases such as analyses with extensive outputs as you outline.

**Comment by mih** [comment]
And maybe something on how to fix things up, once they went wrong.

**Comment by adswa** [comment]
Good idea.

**Comment by mih** [comment]
Some random pointers:

- https://github.com/newren/git-filter-repo -- faster alternative to `git filter-branch`

Remove all `tsplot` folders from a dataset with lots of FEAT analysis outputs

```
# running in a fresh clone, no annexed file content present
% du -sh .
5.4G    .

% git-filter-repo --path-regex '^sub-[0-9]{2}/run-[0-9]{1}_speech-validation.feat/tsplot/.*$' --invert-paths --force

Parsed 60 commits
New history written in 7.46 seconds; now repacking/cleaning...                              
Repacking your repo and cleaning out old unneeded objects                                   
Updating files: 100% (273416/273416), done.
HEAD is now at d479870ec8 3rd lvl results
Enumerating objects: 520968, done.
Counting objects: 100% (520968/520968), done.
Delta compression using up to 16 threads
Compressing objects: 100% (436474/436474), done.                                            
Writing objects: 100% (520968/520968), done.
Total 520968 (delta 82894), reused 520946 (delta 82875)                                     
Completely finished after 18.30 seconds.

% du -sh .
649M    .
```

**Comment by kyleam** [comment]
>  https://github.com/newren/git-filter-repo -- faster alternative to `git filter-branch`

Beyond performance, Git also discourages the use of `filter-branch` for safety reasons and points to `filter-repo` as an alternative.  With a recent git version, there some is non-trivial delay where invoking `filter-branch` shows you this:

```
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as 'git filter-repo'
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
```

That behavior was prompted by [this thread][0] discussing whether to include `filter-repo` in git.git.

[0]: https://lore.kernel.org/git/CABPp-BEr8LVM+yWTbi76hAq7Moe1hyp2xqxXfgVV4_teh_9skA@mail.gmail.com/
