### ISSUE TITLE
Installed DataLad on Ubuntu 18.04 LTS run on VirtualBox 6.0

### ISSUE THREAD

**Issue by cmadjar** [datalad-handbook/book#441]
**What does not work?**

I installed a fresh Ubuntu 18.04 LTS VM via VirtualBox 6.0 on my Mac. When I ran `sudo apt-get install datalad`, version 0.9.3 of DataLad was installed which is not the greatest and latest. Do you see any reason why I get such an old version of DataLad on a fresh install of Ubuntu?

I also tried installing first `sudo apt-get install neurodebian` and then `sudo apt-get install datalad` after removing the first install and I still get version 0.9.3 of DataLad.

Would it be possible to update the version of DataLad we get from the apt-get package manager so that it is downloading more recent versions?

Note: I was finally able to install a more recent version of DataLad via the Miniconda install guidelines but other people might have the same issue than me and not necessarily think of going the Miniconda way.

**Background information**
Please provide us with everything relevant to make sense of the issue such as:
1. A fresh Ubuntu 18.04 LTS VM via VirtualBox 6.0 on my Mac (note I ran all the necessary updates before installing DataLad)
2. Your version of DataLad 0.9.3 and git-annex 6.20180227. Consider providing the output of a ``datalad wtf`` (I guess `wtf` was not part of DataLad 0.9.3 as I get `error: invalid choice: 'wtf'`).
3. Result of `apt search datalad`:
```
$ sudo apt search datalad 
Sorting... Done
Full Text Search... Done
datalad/bionic,bionic,now 0.9.3-1 all [installed]
  data files crawler and data distribution
python-datalad/bionic,bionic,now 0.9.3-1 all [installed,automatic]
  data files crawler and data distribution (Python 2)
```

**Additional context**

The CONP portal is referring to the DataLad Handbook for installation and configuration but if Ubuntu users get version 0.9.3 of DataLad, some functionality of our portal will not work, such as the loris-token for some datasets.

**Extra**

Congrats on the handbook!! Really great documentation! Went through most of it and I definitely understand better how DataLad and git annex work. :)

**Comment by adswa** [comment]
Hi @cmadjar, thanks for getting in touch!

I'm glad that you were able to resolve the issue with Miniconda! I'm a bit confused why you weren't able to get it via Neurodebian. The most recent DataLad release (12.4) should be available there, and ``sudo apt-get neurodebian`` should have enabled it. Did you update your package list after enabling the neurodebian repository?

I will cc @yarikoptic here, maybe he has insights. 

>  Congrats on the handbook!! Really great documentation! Went through most of it and I definitely understand better how DataLad and git annex work. :)

Thanks for the praise, really glad it is helpful! Don't hesitate to request content or raise issues if there is something missing that you need. :)

**Comment by cmadjar** [comment]
Hi @adswa,

Thank you for the quick reply!

I just removed DaraLad (`sudo apt-get remove datalad`) and tried to install it after running the following:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install datalad
```

If that helps, here are the version of datalad, git-annex and neurodebian installed after I run those commands:
```
datalad/bionic,bionic,now 0.9.3-1 all [installed]
git/bionic-updates,bionic-security,now 1:2.17.1-1ubuntu0.5 amd64 [installed,automatic]
git-annex/bionic,now 6.20180227-1 amd64 [installed,automatic]
git-man/bionic-updates,bionic-updates,bionic-security,bionic-security,now 1:2.17.1-1ubuntu0.5 all [installed,automatic]
git-remote-gcrypt/bionic,bionic,now 1.0.2-1 all [installed,automatic]
neurodebian/bionic,bionic,now 0.37.6 all [installed]
neurodebian-archive-keyring/bionic,bionic,now 0.37.6 all [installed,automatic]

```

Hope this helps. Don't hesitate to let me know if you need additional information. Thanks!

**Comment by yarikoptic** [comment]
0.9.3 is indeed the version elderly bionic was released with.  It would provide functionality of DataLad as it knew the world about 3 years ago,  the world without CONP.
http://neuro.debian.net/pkgs/datalad.html provides overview of versions of datalad package on debian based systems and shows that version you could get from neurodebian.  In your case it is not yet clear (didn't spot output of `apt-cache policy datalad`) if you have neurodebian enabled.  If not, something like this (as root) should do it
```
apt-get install neurodebian
apt-get update
apt-get install neurodebian=0.12.4-2~nd18.04+1
```
version in the last one should be optional, but who knows how priorities/pins are on your system.

**Comment by yarikoptic** [comment]
here is a quick demo for a proof that it should generally be ok, using neurodebian docker image for bionic:
```
$> docker run -it --rm neurodebian:nd18.04                                                                                                                                   
root@184dfbd30cd3:/# apt-get update -qqq
root@184dfbd30cd3:/# apt-cache policy datalad  
datalad:
  Installed: (none)
  Candidate: 0.12.4-2~nd18.04+1
  Version table:
     0.12.4-2~nd18.04+1 500
        500 http://neuro.debian.net/debian bionic/main amd64 Packages
     0.9.3-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
root@184dfbd30cd3:/# apt-get install datalad 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
...
```

**Comment by adswa** [comment]
I hope there is nothing left unattended in this issue - It fell of my radar, sorry. I'm closing this, but feel free to reopen!
