### ISSUE TITLE
Up to date author information

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#471]
As part of #468, to prepare for the next [release of the handbook](https://zenodo.org/record/3608612#.XqrnhKaxVhE) (together with a DataLad 0.13 release), I'd like to keep the information in [``.zenodo.json``](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) up to date. As this is where the author list is drawn from, I'm tagging everyone who contributed but is not yet mentioned in there: @hbaagil, @glatard, @dorianps, @sarah1989, @gi114

If you want to, please paste your name, affiliation, and - if you have one - orcid into this issue, and I will add you. Thanks in advance!

**Comment by dorianps** [comment]
Thanks @adswa . I realize my contribution has not been enormous but glad it helped. We are using datalad much more nowadays, so there will be more occasions to contribute.

Name: Dorian Pustina
Affiliation: CHDI Foundation
ORCID: https://orcid.org/0000-0002-2834-7220

**Comment by adswa** [comment]
Thanks @dorianps!
>  I realize my contribution has not been enormous but glad it helped. We are using datalad much more nowadays, so there will be more occasions to contribute.

I look very forward to all future occasions to contribute (and I hope I can find time to sit down and talk with you/write about your use case -  its just a bit busy at the moment on my side), but please let me assure you that your contributions were and are absolutely great and very very appreciated! :)

**Comment by hbaagil** [comment]
Same here @adswa, haven't contributed much. But thanks!

Name: Hamzah Hamid Baagil
Affiliation: Imaging in Neurodegenerative Diseases, University Hospital RWTH Aachen.

Best regards,
Hamzah

**Comment by glatard** [comment]
Thanks!
Tristan Glatard
Department of Computer Science and Software Engineering, Concordia University, Montreal

**Comment by gi114** [comment]
Hi @adswa ,

Thanks for that

Name: Giulia Ippoliti
Affiliation: Bioengineering Department, McGill University, Montreal

**Comment by adswa** [comment]
Awesome, thanks everyone!
