### ISSUE TITLE
How to `datalad run` in parallel

### ISSUE THREAD

**Issue by pvavra** [datalad-handbook/book#472]
Having a section on how to parallelize `datalad run` calls on a cluster would be a nice addition to the handbook.

I'm currently trying to run multiple `datalad run` calls in parallel (with `--explicit` set) and getting problems with git-locks.. I have a few ideas how I could avoid those in my specific case, but I assume that this would be relevant to many people using some form of HPC.

I think the section should highlight what the potential problems are (git-locks / multiple processes trying to commit at the same time) and how to avoid them. The section on [big analyses](http://handbook.datalad.org/en/latest/beyond_basics/101-161-biganalyses.html) is related/a good template for this (e.g. it mentions the `--explicit` flag), but it does not address locking issues. 

A gist or brief outline of how to code this up would be a great start for being pointed in the right direction. 

I assume that there are "intended" programming patterns and more of "anti-patterns". Having a short do's/dont's would be also an option.

**Comment by adswa** [comment]
Thanks for highlighting this need, @pvavra, I agree. I haven't started tackling this because somewhere there is a half-baked extension lying around for this, but until this is getting somewhere, outlining advice and caveats would indeed be helpful.

**Comment by adswa** [comment]
@mih, I think a sketch of the eNKI preprocessing you have done could address this as one example of how it can be done, do you think so, too? Then I'll write it up.

**Comment by mih** [comment]
Yes, this would fit!

**Comment by adswa** [comment]
I'll wait for the final rerun to work, and then I'll start.

**Comment by adswa** [comment]
attn @pvavra - took a while, but a write-up with an example will come in #547.
