### ISSUE TITLE
Inaccurate description of how `push` handles multiple branches

### ISSUE THREAD

**Issue by kyleam** [datalad-handbook/book#481]
docs/basics/101-141-push.rst (0246c38) says

```
If you have more than one :term:`branch` in your dataset, note that a
:command:`datalad push` command will by default update all branches that both
the sibling and the dataset share.
```

As far as I can tell, by looking at push.py and trying it out (e.g., the script below), that's not the case.  Putting aside the special handling of the git-annex branch, the approach is instead "try to do what `git push REMOTE` would do, falling back to pushing the current branch".  That *may* match your description, if the user configured `push.default` to `matching` (or tweaked the default push refspec), but the default for `push.default` (since Git 2.0) is `simple`, which restricts the push to the current branch.

<details>
<summary>script</summary>

```sh
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
datalad create a
git -C a config receive.denyCurrentBranch updateInstead

datalad clone a b
(
    cd b
    git config push.default simple  # current default value for git
    git commit --allow-empty -mc0
    git commit --allow-empty -mc1
    git checkout -b other master~1
    git commit --allow-empty -mc2
    datalad push --to origin
)
```

Output with DataLad 1b908b4ca:

```
[...]
publish(ok): . (dataset) [refs/heads/other->origin:refs/heads/other [new branch]]
publish(ok): . (dataset) [refs/heads/git-annex->origin:refs/heads/git-annex 9152532..6ecf2a2] 
```

</details>

**Comment by adswa** [comment]
Thanks a lot, @kyleam! I realized where that must have come from -- I'm often testing with the ``DataLad-101`` dataset (it has various content types, branches, and subdatasets) and I completely forgot that I configured it *specifically* to automatically push a complete set of branches in order to keep the published version of the dataset up to date. :woman_facepalming:

**Comment by AKSoo** [comment]
Not all parts of this section was fixed to address this. Opening a PR on this.
