### ISSUE TITLE
Permanent URLs

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#494]
This is an attempt to record URLs that need to be maintained permanently (e.g. via redirects), because they have been used in unmaintainable documents (e.g. reports) -- even if the handbook needs to be restructured.

- http://handbook.datalad.org/usecases/HCP_dataset.html
- http://handbook.datalad.org/usecases/reproducible-paper.html

**Comment by adswa** [comment]
I will use this issue to document a redirection feature we have just drafted.

There is a file [r.rst](https://raw.githubusercontent.com/datalad-handbook/book/master/docs/r.rst) which handles redirection.
Its an rst file with raw HTML that includes a bit of JS (I honestly know too little about this, but it feels like [this comic](https://m.xkcd.com/1926/)). 

It contains a mapping that can match a '#ID' appended to handbook.datalad.org/r.html:
```JS
        let redirects = new Map([
            ['GIN', 'basics/101-139-gin.html']
        ]);
```

opening handbook.datalad.org/r.html?GIN will redirect automatically to handbook.datalad.org/basics/101-139-gin.html with this mapping.

Mapping need to be defined with "?<id>", "relative-url-from-docs.html"

**Comment by mih** [comment]
With #518 merged, we have this info in code and will keep it there.
