### ISSUE TITLE
Create and continously update a glossary

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#5]
Writing this book will occasionally require specific vocabulary or common vocabulary that needs to be interpreted in a specific context. I can't come up with many examples now, but I'm sure we will stumble across many in the wake of writing -- ``dataset`` / ``superdataset``, ``history`` etc might be words like this.
Whenever I read about new things with specific vocabulary + definitions I keep myself a glossary to remember the terms or being able to look them up again. Maybe we would want to populate such a glossary as well?
I think of it as a dictionary-like structure, which in alphabetical order lists terms and then states a concise definition (like, you know, a glossary). Populating this while writing will be doable, creating one in the very end would be tedious. I propose we start a glossary document which we add to whenever we write and use a term that someone might want to look up at a later time.

**Comment by mih** [comment]
Good idea. Sphinx makes that very easy. Here are two relevant directives:

http://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary
http://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#index-generating-markup

**Comment by mih** [comment]
I think this can be closed now. It is happening already.
