### ISSUE TITLE
Enable RTD builds PR support

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#501]
RTD people have an experimental feature of providing builds for PRs.  See e.g. https://github.com/con/open-brain-consent/pull/50 where it was already enabled and tested.

I do not have admin privileges for RTD for this project, so the most I could do is to pester RTD people to enable the feature for this repository, which I was told they have done!  So it is now for people with the super powers to actually make it work.  Should be quite straightforward, see https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html for the documentation and common gotchas. In my case it was the need "to disconnect and reconnect to GitHub service" as now described in that document.

**Comment by yarikoptic** [comment]
FWIW, BIDS specification now has it enabled too: https://github.com/bids-standard/bids-specification/issues/484

**Comment by adswa** [comment]
Done, thx much!
