### ISSUE TITLE
Ideas on how to balance file length and recreation of datasets in individual workdirs

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#51]
When recording code and its output, every single .rst file gets an individual workdir associated with it in ``docs/_build/wdirs/``.

The dataset I'm continuously building up and extending will need to be in every one of these workdirs (as many as ``.rst`` files I am writing) in order for the code to work. I don't think it is feasible to create potentially dozens of datasets, slightly increasing in size between different ``.rst`` files. But if I write down everything in a single file, I'm creating - at least for the web version of the book - a really really really long page, and in principle, I'd like to chunk it up into individual pages, and also have toc entries for each of these pages.

Does anyone have an idea on how to balance these conflicting demands? Is there a way to "pagebreak" single ``.rst`` files and create toc entries referencing specific sections in files? Or, alternatively, specify a common workdir manually?

**Comment by mih** [comment]
I was already thinking of having a dedicated config option for the workdir. The examples tend to start with a `cd` already.

**Comment by mih** [comment]
There is an issue, however, if things are not constrained to a single RST file, we have to deal with dependency resolution and determine an execution order. Sphinx will only touch RST files that have been edited on a rebuild, but if such a partial rebuild now requires the output of examples that will not be re-rendered, the autorunrecord extension will never get to see those steps.

In any case, there is no sense in having the structure of the book be determined by the limitations of the supporting code.

It would be good to see a concrete example if a problematic case. Maybe there is a simple solution possible. If not, we could go to some kind of two-pass update strategy, where we first collect the code bits, and then run it to update the record files. But then we would always have to build twice. Not extremely bad, but also not nice.

**Comment by adswa** [comment]
Let me commit and push what I have created today, so that you could take a look what the problematic situation currently is. (give me 15 mins)

**Comment by mih** [comment]
We have `workdir` for a while now. Closing
