### ISSUE TITLE
Uniform user environment for the book examples

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#53]
At the moment the current system user environment (i.e. us) is used. That means that when I re-run and replace @adswa 's output, there will always be changes.

We could include a helper script that create a dedicated user enironment on our machines that we then use to build the book examples.

**Comment by adswa** [comment]
It sounds good to not replace output when re-running ``make`` after a ``make clean``!

I have to admit, though, that I don't know exactly what the dedicated user environment would do? Create a "common author" so that paths and commit authors always are the same?

**Comment by mih** [comment]
Yes, exactly. It would essentially be a (fake) HOME directory with a uniform identify, Git configuration, shell prompt setup. We have a similar setup for build the asciicasts in DataLad. I can work on that at some point.

Side note: the output would still be replaced, but changes would hopefully only reflect difference in software versions, and not in user identity or configuration.

**Comment by adswa** [comment]
Cool!
