### ISSUE TITLE
Needed: A troubleshooting section

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#536]
Following https://github.com/datalad/datalad/issues/4651#issuecomment-649180205. 
This can fit right into the "How to get help section". It should entail:

- short overview of the different log levels
- how to trigger "debug" messages and how to interpret them (DataLad: ``-l/--log-level`` or env ``$DATALAD_LOG_LEVEL``, git-annex: ``-v/--verbose``, ``--debug``/)
- how to enter a debugging session: ``-dbg``

... what else?

**Comment by jbpoline** [comment]
One thing that often trips the naive me is the git-annex debugging, and knowing if this is a datalad, git-annex, or interaction pb. I know there is "wtf" and that already should help - is there an equivalent git-annex wtf (that would be run first ...) ?
