### ISSUE TITLE
Approach to sub-part/multi-chapter structure?

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#54]
With https://github.com/datalad-handbook/book/pull/52 we get something like this:

![image](https://user-images.githubusercontent.com/136479/60702205-84e51c00-9efe-11e9-918f-91921e113ce4.png)

All content of the book PART "Basics", but the "Starting from scratch" chapters clearly aim to be more than just subsequent chapters, without technically being a part.

Two alternative approaches that I can see ATM:

1. 'Starting from scratch' becomes a part
2. There will be a single 'Starting from scratch'.rst with some kind of a preamble and a subordinate TOCtree that lists the actual chapters (create, populate, modify). This way, each of them stays its own chapter, but the hierarchical structure is made clear(er).

or 3): it stays implicit.

None of this has to be dealt with any time soon. I am only collecting issues that might have implications on the desired structure of the book.

**Comment by adswa** [comment]
Thanks for collecting those! I don't have an opinion on any approach currently, but I'd agree with @mih on waiting. There may other things that surface or stuff that might disappear given that we just started with actual content for the Basics.

**Comment by adswa** [comment]
This is getting more pressing already. Including what currently lives in some branches, the content more or less looks like this (ordering is in some cases not yet clear). Names of these sections can easily be changed, I did not give much thought to them. To be honest, I think it would be a good idea to rename or restructure them in a way that makes a clear red thread apparent (currently, it looks like someone dropped a bunch of more or less related files into this issue :wink: ) 

    Installation and Configuration
    General prerequisites
    Starting from scratch: Creating a dataset
    Starting from scratch: Populating a dataset
    Starting from scratch: Modifying content
    Starting from scratch: Summary
    Basic DataLad magic: Installing datasets
    Basic DataLad Magic: Dataset nesting
    Basic DataLad Magic: Summary
    DataLad, Run! [1]
    DataLad, Re-Run!
    Datalad, Run! [2]
    Content-protection, powered by Git-annex [1]
    Datalad, Run! [3]
    Run, Datalad! Summary
    Content-protection, powered by Git-annex [2]
    Secrets of Git-annex: Symlinks and object trees
    Sharing datasets: Common File systems
    Sharing datasets: Common File systems [2]
    Updating datasets: The basics
    Back and forth in time: Working with history
    Miscallaneous file system operations


If anyone has an idea on how to structure this differently what it is now, please voice that idea :smile:

**Comment by mih** [comment]
I think we are already moving in the direction of having more "parts", and grouping related chapters into them.
