### ISSUE TITLE
Have "when things go wrong" sections/boxes

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#55]
These could be hidden by default, but nevertheless contain essential information. Example from https://github.com/datalad-handbook/book/pull/52:

> Remember, if you run a ``datalad save`` without specifying a path, all untracked files and all file changes will be committed to the history together!

So what if that happens, because I did not remember this one time? There could be a box that just put it out there that `git reset HEAD~1` bring you back to the exact same state as before (within the current dataset), without necessarily having to explain all of `git reset`

Name inspired by git-annex, e.g.: https://git-annex.branchable.com/walkthrough/removing_files__58___When_things_go_wrong/ https://git-annex.branchable.com/walkthrough/transferring_files__58___When_things_go_wrong/

**Comment by adswa** [comment]
I really like this idea! We should make them visually distinct from other parts that can be hidden.

**Comment by adswa** [comment]
I still like this idea. We could just create a differently named and colored "Findoutmore", the principle is exactly the same. I don't have the capacity to do it, but this would actually be a well-suited project for a hackathon or for handbook contributors. If anyone reads this and is compelled to help, please reach out.

**Comment by mih** [comment]
While different from the proposal here, we have http://handbook.datalad.org/en/latest/basics/basics-help.html which does a decent job in the same spirit.
