### ISSUE TITLE
dead link to docs?

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#556]
**What does not work?**
The link in 
http://handbook.datalad.org/en/latest/intro/installation.html
to 
http://docs.datalad.org/en/latest/gettingstarted.html
does not work.

Is this the correct one? 
http://docs.datalad.org/en/stable/

**Comment by adswa** [comment]
Yes, indeed, that's the correct one! Would you PR a fix?

**Comment by Remi-Gau** [comment]
Will do that now.
