### ISSUE TITLE
pip installation problem chapter 6.3 - troubleshooting for newbies

### ISSUE THREAD

**Issue by judithbomba** [datalad-handbook/book#563]
Hello lovely DataLad Team!

I stumbled upon something during my studies of the handbook:
In the *Footnote 3 of YODA chapter 6.3* there is a copy-paste way of installing seaborn, pandas and sklearn that did not work for me. 

**Possible addition**
Maybe you could add an alternative way of installing those packages? For me, using `python -m pip install` worked.

Whilst google could help eventually it took a long time to find a working solution, because as a newbie I had a hard time finding a solution to this problem without knowing what to look for. Including possible troubleshooting in this part of the handbook would be very handy for future readers.

Greetings and a nice day to you all

**Comment by adswa** [comment]
Thanks a lot, @judithbomba. That is indeed a bug (there shouldn't be commas - it should be ``pip install seaborn pandas sklearn``). Thanks for letting us know and sorry for the confusion. @all-contributors please add @judithbomba for bug. Feel free to add yourself to the .zenodo.json file :)
I will fix this right away.

**Comment by adswa** [comment]
@all-contributors please add @judithbomba for bug

**Comment by adswa** [comment]
Fixed in  582dafa

**Comment by adswa** [comment]
Ah, I completely forgot to close this. 

Unrelated and random and weeks delayed: When you submitted your first PR @judithbomba I joyfully [shared this fact on Twitter](https://twitter.com/AdinaKrik/status/1291027227652567040?s=20) and some lovely folks from the open science bubble on Twitter wrote me privately to ask you whether you'd want to share you're experience about joining GitHub, posting an issue, and submitting a PR:

> Hi Adina! I love that story about the user with their first pull request! Do you think it would be appropriate to tag them or share their issue for recognition, or do you think it would be uncomfortable for them? I’d love to see them write a thread about their experience!!

> As much as the h/t, it would be really cool to hear about her journey! It’s such an important first step!  

I forgot to ask, but if you are/want to be on Twitter, there is a great and encouraging open science bubble that would enjoy stories about first time PRs (and that are also absolutely great people to follow, even if you don't want to tweet) :)

**Comment by judithbomba** [comment]
Now I'm the one reading comments way too late :)

> I forgot to ask, but if you are/want to be on Twitter, there is a great and encouraging open science bubble that would enjoy stories about first time PRs (and that are also absolutely great people to follow, even if you don't want to tweet) :)

Thanks, I have made a Twitter account just now, and will be enjoying the open science bubble al lot! :D

> > Hi Adina! I love that story about the user with their first pull request! Do you think it would be appropriate to tag them or share their issue for recognition, or do you think it would be uncomfortable for them? I’d love to see them write a thread about their experience!!
> 
> > As much as the h/t, it would be really cool to hear about her journey! It’s such an important first step!

Sure, you can share the issue, I hope it will be as much of a help to others, as it was to me! Tagging is always fine (now that I am on Twitter) and I will definitely post about my journey through the depths of getting better at programming and data science.
