### ISSUE TITLE
Add front-page info on the state of things

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#57]
Given that this repo and http://handbook.datalad.org are public, it would be sensible to have some brief statement on the state of things on the frontpages. The question came up whether or not it is OK to point people to it, and ask for feedback.

I *personally* think that is is always OK to point people that ask for more info, but I don't think general call for feedback (#12)  is useful ATM, because many things are still unknown and much is in flux.

**Comment by adswa** [comment]
I agree, it is a good thought to have such a disclaimer. I have done a simple front-page note in #58.
