### ISSUE TITLE
Add "What's new" announcement box?

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#571]
Handbook is big and growing.  While reviewing https://github.com/datalad-handbook/book/pull/569 I thought that additions to handbook are really worth a "news feed" so those who read the book before could be announced on what is new to it and read those new sections etc.  There is of cause a CHANGELOG but it is also mixed in with internal changes etc so a different medium to report "news" on the handbook.  Sure thing there could be a tweet to announce etc.  But I feel that getting some good old RSS news feed and displaying it on opening page ("What's new" popout or subsection) would be useful: then any new additions could be announced and former readers of the handbook could familiarize themselves with new sections/chapters.

**Comment by adswa** [comment]
That's a really cool idea. How does one set up an RSS news feed?

**Comment by yarikoptic** [comment]
IIRC for neurodebian @mih used some for the "blog" portion: http://neuro.debian.net/blog/index.html .  https://www.google.com/search?q=sphinx+RSS&oq=sphinx+RSS gives some hints but I have no prior/active experience with any I guess.

**Comment by adswa** [comment]
Looked around a bit, and I did not find a fast plug-and-play option yet. will continue searching.

**Comment by adswa** [comment]
I've added a "good first issue" label, and maybe someone familiar with setting up RSS feeds can come to help during Hacktoberfest. :)

**Comment by adswa** [comment]
I will close this, as we haven't gotten around to implement this yet,  and the CHANGELOG is a working way of handling this as well. :)
