### ISSUE TITLE
Mention dependency on 7-zip

### ISSUE THREAD

**Issue by khinsen** [datalad-handbook/book#572]
Chapter 3 "Installation and configuration" states right at the beginning:

"Beyond DataLad itself, the installation requires Python, Git, git-annex, and potentially Python’s package manager pip."

That list looks incomplete, because the DataLad installation procedure (via pip) complains 
```
datalad.support.exceptions.MissingExternalDependency: cmd:7z is missing. The 7z binary (7-Zip) is required for archive handling, but is missing. Setting the config flag 'datalad.runtime.use-patool' enables an alternative implementation that may not need 7z.
```
So it looks like 7-Zip is another external dependency. After installing [p7zip](https://sourceforge.net/projects/p7zip/) (Linux), the message disappeared.

**Comment by adswa** [comment]
Thank you @khinsen! True - we forgot that while p7zip gets installed as a dependency when installing datalad as a Debian or conda package, it can not be installed by pip. I've opened #573 to address this.

@all-contributors please add @khinsen for bug.

Also, feel free to add yourself to the .zenodo.json file (outlined [here](http://handbook.datalad.org/en/latest/contributing.html#acknowledging-contributors)).

**Comment by adswa** [comment]
(i hate talking to bots so much - sorry for the noise)

@all-contributors please add @khinsen for bug

**Comment by khinsen** [comment]
Thanks @adswa, I think I never became a contributor to a project that quickly! It almost makes me regret that I didn't start by pointing out some missing comma (I am sure there is one to be found somewhere), just to become the smallest imaginable contributor ;-)

**Comment by adswa** [comment]
Haha ;-) IMO every contribution helps and its always great if people take the time and effort to engage. There's also no threshold at which anything is "too small" or "big enough". My secret hope is that this especially encourages and empowers people new to Git and GitHub or first time contributors to be active in other open source projects. I'm super happy whenever the bot (listens to me and) adds someone to the author list, or if .zenodo.json gets more entries. Some people have joined GitHub only to report a bug and then practiced their first PR with adding their zenodo entry, and even if that's the only thing they learned from this resource, I'd be proud :-)
