### ISSUE TITLE
RIA chapter: link not publicly accessible

### ISSUE THREAD

**Issue by mikapfl** [datalad-handbook/book#596]
Hi,

In the [RIA workflows paragraph](http://handbook.datalad.org/en/latest/usecases/datastorage_for_institutions.html#ria-store-workflows), there is a link to a [custom procedure](https://jugit.fz-juelich.de/inm7/infrastructure/inm7-datalad/blob/master/inm7_datalad/resources/procedures/cfg_inm7.py), but unfortunately that link:

https://jugit.fz-juelich.de/inm7/infrastructure/inm7-datalad/blob/master/inm7_datalad/resources/procedures/cfg_inm7.py

is not accessible for people without an account at FZ Jülich and special access rights. Maybe you can upload that somewhere else and change the link or make the gitlab project visible for everybody?

Cheers,

Mika

**Comment by adswa** [comment]
Hi Mika, thanks for letting us know! I actually was under the assumption that any "guest" would be able to view the files - sorry about this. @bpoldrack, @mih - what do you think about the idea to collect the set of resources for RIA stores (IIRC there are also some maintenance scripts somewhere) into a joint, public repo, e.g. in a repo in the handbook organization?

**Comment by bpinsard** [comment]
Hi, I would also be greatly interested in this config file!
I cannot find anywhere in the doc or handbook, how the riastore can use 7z archives, so I guess config files are the answer?Thank you!

**Comment by MartinGrignard** [comment]
Hi! I'm just posting to say that this would be very useful for me too. Have a nice day :smile:

**Comment by adswa** [comment]
Sorry all, I lost this issue from my radar. @bpoldack, I'm quite confident that most RIA functionality we had in those procedures when I wrote the section has made it into datalad-core. Could you take a look if there are scripts/procedures/... that perform things beyond what the current RIA commands do by default? And could we host anything of relevance somewhere public?
I need to add reworking this section to my todo list.

**Comment by adswa** [comment]
Sorry all, I lost this issue from my radar. @bpoldrack, I'm quite confident that most RIA functionality we had in those procedures when I wrote the section has made it into datalad-core. Could you take a look if there are scripts/procedures/... that perform things beyond what the current RIA commands do by default? And could we host anything of relevance somewhere public?
I need to add reworking this section to my todo list.

**Comment by bpoldrack** [comment]
> Could you take a look if there are scripts/procedures/... that perform things beyond what the current RIA commands do by default?

There are and I will have a look shortly.

> And could we host anything of relevance somewhere public?

I actually began to build up a repository for that purpose. Aim is to move additional scripts/helper functions and comprehensive documentation there. Including everything that's on JuGit but not really about INM/FZ. It still is "under construction", though:
https://github.com/datalad/ria-tools/

**Comment by bpoldrack** [comment]
As an intermediate update while working on above mentioned effort to put all pieces in a dedicated repo:

The procedure in question is rather outdated by now and likely not worth looking at. We can and possibly should provide an updated version of it (or something very similar) to showcase the use of procedures for a more complex setup routine, but ATM it's neither used the way it was meant to, nor does it do exactly what it used to in an earlier version (because we changed when and how GitLab projects are set up).
Anyways - I have put the current version in the new repo and put in some additional remarks in the docstring at the top. So, if anyone really wants to get an idea: https://github.com/datalad/ria-tools/blob/master/ria_tools/resources/procedures/cfg_inm7.py


Note, however, that the important aspect for it to exist in the first place is that the config variables `annex.ria-remote.inm7-storage.base-path` and `annex.ria-remote.inm7-storage.ssh-host` are set at system-level (`git config --system ....`). And those configs can be different on different system, so that users using this procedure would be directed to different stores (or different access methods) transparently depending on where exactly they are.

In current datalad version, this kind of configuration would be done using `ria+(ssh|file|http(s)):// ....` URLs, which could be "rerouted" in the same transparent fashion using git's `url.URL-OR-PART-THEREOF.insteadof` overrides.

**Comment by bpoldrack** [comment]
However, leave this open, @adswa. I will update here, once the ria-tools repo is ready, since that should then (and only then) result in a handbook update, I think.

**Comment by bpoldrack** [comment]
@bpinsard 
> I cannot find anywhere in the doc or handbook, how the riastore can use 7z archives, so I guess config files are the answer?Thank you!

7z must be available at the store side, of course. The important part is, that users can't directly push into an archive. Instead it is kind of a maintenance task to pack annex objects into an archive and put it into the store. This could be automated of course. To help with building an archive reflecting a dataset there is the `datalad export-archive-ora` command:

```

datalad export-archive-ora(1)                      General Commands Manual                      datalad export-archive-ora(1)

NAME
       datalad export-archive-ora - export an archive of a local annex object store for the ORA remote.

SYNOPSIS
       datalad export-archive-ora [-h] [-d DATASET] TARGET ...

DESCRIPTION
       Keys  in  the local annex object store are reorganized in a temporary directory (using links to avoid storage duplica‐
       tion) to use the the directory-type special remote. This alternative object store is then moved into  a  7zip  archive
       that is suitable for use in a ORA remote dataset store. Placing such an archive into::

       <dataset location>/archives/archive.7z

       Enables the ORA special remote to locate and retrieve all keys contained in the archive.

OPTIONS
       TARGET if  an existing directory, an 'archive.7z' is placed into it, otherwise this is the path to the target archive.
              Constraints: value must be a string

       list of options for 7z to replace the default '-mx0' to generate an uncompressed archive.

       -h, --help, --help-np
              show this help message. --help-np forcefully disables the use of a pager for displaying the help message

       -d DATASET, --dataset DATASET
              specify the dataset to process. If no dataset is given, an attempt is made to identify the dataset based on the
              current  working  directory.  Constraints:  Value  must be a Dataset or a valid identifier of a Dataset (e.g. a
              path)
```

**Comment by bpinsard** [comment]
@bpoldrack 
Thanks!
I got the procedure to index/add-as-remote the archive using `git-annex fsck` from elsewhere, which was the main missing piece for me to make it work. However, I will carefully read the config file and certainly adapt it to our needs to make stuff easier for our end users.

**Comment by bpoldrack** [comment]
> However, I will carefully read the config file and certainly adapt it to our needs to make stuff easier for our end users.

Note, that `create-sibling-ria` wasn't around yet, when this was written. So, an updated version would just use that with a "canonical" ria+URL and possibly set `url...insteadOf` to replace that URL per system (for example to switch between access via SSH and local operation when you are on the same file system).

**Comment by jmschabdach** [comment]
Hello,

Not sure if this is a reiteration of the original issue - I was able to log into GitLab via Shibboleth and see the repository, but the infrastructure subproject does not appear to exist (or be accessible).

[Target link](https://jugit.fz-juelich.de/inm7/infrastructure/inm7-datalad/blob/master/inm7_datalad/resources/procedures/cfg_inm7.py)

Would it be possible to make the code in this file publicly available?

Thanks,
Jenna

**Comment by adswa** [comment]
Sorry Jenna, this part of the chapter is badly outdated. I have been meaning to update it for months already, but never really got around. As @bpoldrack mentioned above:

> The procedure in question is rather outdated by now and likely not worth looking at. We can and possibly should provide an updated version of it (or something very similar) to showcase the use of procedures for a more complex setup routine, but ATM it's neither used the way it was meant to, nor does it do exactly what it used to in an earlier version (because we changed when and how GitLab projects are set up).
Anyways - I have put the current version in the new repo and put in some additional remarks in the docstring at the top. So, if anyone really wants to get an idea: https://github.com/datalad/ria-tools/blob/master/ria_tools/resources/procedures/cfg_inm7.py

> Note, however, that the important aspect for it to exist in the first place is that the config variables annex.ria-remote.inm7-storage.base-path and annex.ria-remote.inm7-storage.ssh-host are set at system-level (git config --system ....). And those configs can be different on different system, so that users using this procedure would be directed to different stores (or different access methods) transparently depending on where exactly they are.

> In current datalad version, this kind of configuration would be done using ria+(ssh|file|http(s)):// .... URLs, which could be "rerouted" in the same transparent fashion using git's url.URL-OR-PART-THEREOF.insteadof overrides.

**Comment by jmschabdach** [comment]
Thanks for your quick response @adswa! Even though the procedure is outdated, it was insightful to look at the script to see what the though processes were at the time.

**Comment by mih** [comment]
I am closing this issue. The TODOs are not to be solved within the scope of the handbook.
