### ISSUE TITLE
Brainstorm templates

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#6]
I'm just brainstorming bit and pieces, but something that came to my mind is that recurrent "types" of content -- specifically I am thinking about use-cases -- are easiest digested IMO if they follow a common outline/template/structure.

I'm currently thinking of something like 
- summary: what is the context, what will you learn from reading this
- problem: a relatable, pointed description of a problem that we aim to solve
- solution/utopia: a description of the outcome state after applying the datalad procedures necessary. To basically awaken demand to know how to get to the state, and to give a quick overview beyond the summary whether the following recipe is worth the readers time given their interest/motivation
- recipe: a step-by-step tutorial how to get from problem to solution, as short as possible, but with as many steps as necessary, and with pointers to more detailed resources (within the book) for particular commands.
- additional resources, links, etc for further reading

but that is a preliminary line of thought that could very well not be applicable at all - I just want to keep my thought somewhere. I will write a Remodnav use case and try to find a sensible structure (probably very iteratively over and over again) and maybe we are able to find a generic template structure that is applicable to all kinds of use cases. By supplying a template to fit that structure future contributions by others could be made easy as well.

**Comment by mih** [comment]
I think we have settled on a structure. Closing.
