### ISSUE TITLE
Needed: Collection of crendential env var names

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#600]
I recall several conversations about how credential management in DataLad is not optimal, and that a switch to the Git credential manager could be useful.
For the time being, it may be helpful to

- document the environment variable method of setting credentials
- have a list of env var names 

As a note to myself to add later:
- HCP S3: ``DATALAD_hcp_s3_key_id`` and ``DATALAD_hcp_s3_secret_id``
- HCP connectome DB: ``DATALAD_hcp_db_username`` ``DATALAD_hcp_db_password``

**Comment by mih** [comment]
Related: https://github.com/datalad/datalad/pull/5491
