### ISSUE TITLE
A table with data hosting providers/archives datalad could "publish/export" to, features and limits

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#611]
I keep forgetting which providers have what limits, so I thought that it might be nice to initiate a registry of (only "free" with pragmatically useful limits and found to be used with datalad) providers which datalad could be used to "publish" or "export" to.  I see following "columns" which could be useful:

- Size limit:  total (e.g. figshare - 20GB?) and per file (to inform to do chunking in case of special remote)
- Integration: git-annex (native, e.g. gin), annex special remote, annex external special remote (with references to project), datalad export* of some kind (like for figshare)
- Access: private, public, shared (e.g. with dropbox, box etc AFAIK we would have "private, shared" ATM since people need to share that folder with others)
- Limitations: e.g., flat files tree (figshare, zenodo)
- Target domain: could be empty if generic, or "neuroscience" if e.g. for Gin
- Examples: sample references to example DataLad datasets found to be "published" there
- References: e.g. links to sections within handbook presenting examples or providing HOWTO

AFAIK these are some  which come to mind: OSF, GitHub LFS, Gin, DropBox, box, google drive, figshare.

edit: could add initiatives/archives which might be (ab)used -- e.g. fcp-indi (s3 bucket, regular git-annex s3 special exporttree remote), openneuro (not direct datalad ingest yet, but will come) -- just would need a column (or in references) for "Contact" information etc to "orchestrate", CONP-PCNO - for "Canadians", etc

**Comment by adswa** [comment]
I'm reviewing which past issues are still applicable, and while I think this table is useful to have for users, it would be quite difficult to maintain and keep up to date. Knowing what publication venues exist certainly exceeds my horizon, and that list will also change dynamically or differ on a user basis (e.g., hosting "for Canadians" is completely useless for everyone outside of Canada), and I'd be afraid to selectively disadvantage users we simply do not know personally.
