### ISSUE TITLE
Handbook edits - two suggestions

### ISSUE THREAD

**Issue by green-coins-and-ham** [datalad-handbook/book#636]
Change "operating system" to "operating systems" somewhere prior to page 50
Change "suites" to "suits"

**Comment by adswa** [comment]
Hey @green-coins-and-ham! Thank you for your suggestion! Would you like to attempt a pull request to apply them? If you need assistance, I would be happy to help you. :)

**Comment by adswa** [comment]
Tagging you again, @green-coins-and-ham, just to make sure that the notification didn't accidentally slip through over the course of the holidays. Let me know if you want to give it a go :)

**Comment by adswa** [comment]
giving this another ping

**Comment by adswa** [comment]
I have to close this, I can't locate the exact place where the suggestions should apply to :(
