### ISSUE TITLE
Pointers on how to install python

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#649]
Got a few labmates who have started to play around with datalad (I promise I did not twist their arms... that much).

But several of them had only the "basic" python install on their machine.

Made me realize that there is no section or pointer in the handbook to how to install python.

I think that at least a link to something, that tells people how to install python on all OS could a good thing.

I thought of the "install" section (see very bottom of [this page](https://ohbm.github.io/hackathon2020/logistics/)) we used at the last OHBM hackathon (actually reused from another event in Montreal). It focuses on using conda.

It is a bit lost in the whole page there so if you want I could try to condense it into a single paragraph for the handbook.

Happy to add pointers to any better resource you might know though.

**Comment by adswa** [comment]
> Made me realize that there is no section or pointer in the handbook to how to install python.

That is very true! Thanks! We haven't actually ever thought about this outside of the context of Windows (#638). 

> I thought of the "install" section (see very bottom of this page) we used at the last OHBM hackathon (actually reused from another event in Montreal). It focuses on using conda.

Focusing on conda is a good idea. The handbook already does it for Windows and for Servers. 
Thinking about the most useful and maintainable way to add it to the installation section, I'd suggest a single "Python" paragraph at the very start. It could

- note that Python3 is required
- note that this could be checked by typing "python" and/or into the terminal
- point to Miniconda as the way to go if Python isn't installed, or only available as Python2.

I'm in the source code at the moment anyway, will try my hands at a PR :)

**Comment by Remi-Gau** [comment]
Sheeesh !!! You're quick!!!!
