### ISSUE TITLE
Question: `datalad get` on ENKI

### ISSUE THREAD

**Issue by mattcieslak** [datalad-handbook/book#673]
Hi! I'm using your ENKI instructions to process a similarly-sized set of data with fmriprep. I'm noticing that it takes an enormous amount of time to run the `datalad get -n -r -R1 .` command after many of the participants have finished. Particularly the freesurfer and fmriprep directories take hours to clone.

Is this a result of there being thousands of branches in the remote fmriprep subdataset?

**Comment by adswa** [comment]
Hi @mattcieslak!

> Is this a result of there being thousands of branches in the remote fmriprep subdataset?

This may be. Hours to clone is definitely not good. We haven't observed this in the enki dataset, but we have seen it half way through processing the UKBiobank dataset with a similar setup. Writing up the lessons-learned for this workflow based on scaling it up to ~40k jobs is still on my todo list, though.

@mih, please chime in, I wasn't involved in house-keeping. Did a manual garbage collection (``git gc``) did the job for you?

**Comment by mih** [comment]
Yes, I can confirm @adswa 's facts. For eNKI we did not recognize it as a problem (fmriprep runtime per job was too long), but for UKB processing with a different short pipeline it quickly became a bottleneck.

I can recommend the following approach to avoid this issue: Use two locations to pull from and to push to. Put a lean start dataset (just the main branch and the git-annex branch) in location A. let all jobs clone from there. When a job has finished, push the file content (annex keys) only to the data store that collects the outputs, and selectively push the branch where the job results were saved to a location B. Do not push the git-annex branch (yes, discard on the compute node). Do not push any branch to location A.

This will have two main effects:

1) The initial clone is always as fast as it was for job 1
2) The final push is always fast, because no merge or other consolidation needs to be done

When all jobs are done, the merging of all branches must take place. Depending on the number, this can take a while (for 42k UKB branches it was a few hours), but it is a cost that is only paid once. The last thing to do is the restoration of the git-annex branch info (that was not updated per job for speed reasons). This can be done with a single `git annex fsck -f storage-sibling-name --fast`.

**Comment by mattcieslak** [comment]
Thanks for the quick response @mih and @adswa! I will try the different A/B pull/push strategy on the next large dataset. It seems like `git gc` in the `fmriprep/` and `freesurfer/` directories sped things up dramatically.

We're planning on running a number of huge datasets through the preps and would be happy to help with writing that section. Would this issue be a good place to keep a conversation going?

**Comment by adswa** [comment]
> We're planning on running a number of huge datasets through the preps and would be happy to help with writing that section.

I would be delighted :)

> Would this issue be a good place to keep a conversation going?

Certainly. I have to apologize in advance for having only little spare time to write in the immediate future, but happy to collect and answer questions/issues/experiences here.

**Comment by mattcieslak** [comment]
@mih should the repository at location B be a sibling of location A, or does that not matter?

Should location B be outside of the superdataset?

for example, in my superdataset I could do something like:

```bash
datalad create \
    -D "fmiprep outputs" \
    -d . \
    fmriprep

datalad create-sibling \
    -d fmriprep \
    --name push_fmriprep \
    ../push/fmriprep
```

and at the end of the fmriprep run script I would do

```bash
flock $DSLOCKFILE datalad push -d fmriprep --to push_fmriprep
```
and should I flock a different file when pushing to push_fmriprep?

**Comment by mattcieslak** [comment]
I'm trying to modify the [ENKI section](https://handbook.datalad.org/en/latest/beyond_basics/101-171-enki.html) to work with the alternative-push strategy. I'm keeping the `freesurfer/` and `fmriprep/` subdatasets in `/data/project/enki/superds` empty except for the master and git-annex branches. Then making some datasets to push to somewhere outside of the superds, say something like `/data/project/enki/push`.

To make the siblings for each, before submitting any of the subject jobs

```
# in the superds
datalad create-sibling \
    -d fmriprep \
    --name push_fmriprep \
    /data/project/enki/push/fmriprep

# Is this necessary?
datalad push -d fmriprep --to push_fmriprep
```

I noticed that there is no reference to the remote `push_fmriprep` in the output from `datalad siblings` when run in `/tmp/superds/fmriprep`. Is it necessary to add the sibling to the copy on the compute host? Like

```
# on compute host in superds clone
cd fmriprep
datalad siblings add --name push_fmriprep --url /data/project/enki/push
```
And finally, to only push the results branch, not the git-annex branch, this seems to work:

```
# from superds/fmriprep
git config --local remote.push_fmriprep.push "refs/heads/job-$JOBID"
PUSHDSLOCKFILE=/data/project/enki/push/fmriprep/.git/datalad_lock
flock ${PUSHDSLOCKFILE} datalad push --to push_fmriprep
```

Does this implement what you described?

**Comment by adswa** [comment]
Sorry for the late response! I'll add what I know, but maybe @mih can add his thoughts, too, and correct me where I have overlooked something :) .To me, it looks very similar.

> To make the siblings for each, before submitting any of the subject jobs
```
# in the superds
datalad create-sibling \
    -d fmriprep \
    --name push_fmriprep \
    /data/project/enki/push/fmriprep
```
One difference in our setup is that the dataset we're pushing to (push_fmriprep in your case) is a dataset in a RIA store. This allows us to separate the git aspect of the data (where the job branch is pushed to) and the data aspect (where the results and git-annex branch are pushed to) more explicitly. 
So instead of ``create-sibling``, we are doing ``create-sibling-ria``, which creates a storage special remote for the data, and a regular git-remote for the rest. (Please tell me if I should be more verbose with this explanation - currently typing this in between two other tasks and I can return to this with more time if needed). But it should work with a regular dataset, too.

```
# Is this necessary?
datalad push -d fmriprep --to push_fmriprep
```
I don't think so. This will happen within the compute job anyway, if I understand your setup correctly. 

> I noticed that there is no reference to the remote push_fmriprep in the output from datalad siblings when run in /tmp/superds/fmriprep. Is it necessary to add the sibling to the copy on the compute host? Like
```
# on compute host in superds clone
cd fmriprep
datalad siblings add --name push_fmriprep --url /data/project/enki/push
```

YES! We pass three positional arguments to the participant-wise job: the "superds" to clone from, the subject-ID for branch naming, and a "pushgitremote" which is push_fmriprep in your setup.
The we add it as a remote/sibling after cloning the super_ds.


> And finally, to only push the results branch, not the git-annex branch, this seems to work:
```
# from superds/fmriprep
git config --local remote.push_fmriprep.push "refs/heads/job-$JOBID"
PUSHDSLOCKFILE=/data/project/enki/push/fmriprep/.git/datalad_lock
flock ${PUSHDSLOCKFILE} datalad push --to push_fmriprep
```
This looks good me. @mih?


For completeness, here is the script we are using. The difference is the use of a RIA store. That why we do a git push to the Git part of the dataset in the store, and a datalad push to the storage remote at the end.
```
cat code/participant_job                                                                                     1 !
#!/bin/bash

# the job assumes that it is a good idea to run everything in PWD
# the job manager should make sure that is true

# fail whenever something is fishy, use -x to get verbose logfiles
set -e -u -x

dssource="$1"
pushgitremote="$2"
subid="$3"

# get the analysis dataset, which includes the inputs as well
# importantly, we do not clone from the lcoation that we want to push the
# results too, in order to avoid too many jobs blocking access to
# the same location and creating a throughput bottleneck
datalad clone "${dssource}" ds

# all following actions are performed in the context of the superdataset
cd ds

# in order to avoid accumulation temporary git-annex availability information
# and to avoid a syncronization bottleneck by having to consolidate the
# git-annex branch across jobs, we will only push the main tracking branch
# back to the output store (plus the actual file content). Final availability
# information can be establish via an eventual `git-annex fsck -f joc-storage`.
# this remote is never fetched, it accumulates a larger number of branches
# and we want to avoid progressive slowdown. Instead we only ever push
# a unique branch per each job (subject AND process specific name)
git remote add outputstore "$pushgitremote"

# all results of this job will be put into a dedicated branch
git checkout -b "job-$JOBID"

# we pull down the input subject manually in order to discover relevant
# files. We do this outside the recorded call, because on a potential
# re-run we want to be able to do fine-grained recomputing of individual
# outputs. The recorded calls will have specific paths that will enable
# recomputation outside the scope of the original Condor setup
datalad get -n "inputs/ukb/${subid}"

# the meat of the matter
# look for T1w files in the input data for the given participant
# it is critical for reproducibility that the command given to
# `containers-run` does not rely on any property of the immediate
# computational environment (env vars, services, etc)
find \
  inputs/ukb/${subid} \
  -name '*T1w.nii.gz' \
  -exec sh -c '
    odir=$(echo {} | cut -d / -f3-4);
    datalad -c datalad.annex.retry=12 containers-run \
      -m "Compute $odir" \
      -n cat \
      --explicit \
      -o $odir \
      -i {} \
      -i code/cat_standalone_batch.txt \
      -i code/finalize_job_outputs.sh \
      sh -e -u -x -c "
        rm -rf {outputs[0]}/tmp ;
        mkdir -p {outputs[0]}/tmp \
        && cp {inputs[0]} {outputs[0]}/tmp \
        && gzip -d {outputs[0]}/tmp/* \
        && /singularity -b {inputs[1]} {outputs[0]}/tmp/*.nii \
        && bash {inputs[2]} {inputs[0]} {outputs[0]}/tmp {outputs[0]} \
        && rm -rf {outputs[0]}/tmp \
        " \
  ' \;

# it may be that the above command did not yield any outputs
# and no commit was made (no T1s found for the given participant)
# we nevertheless push the branch to have a record that this was
# attempted and did not fail

# file content first -- does not need a lock, no interaction with Git
datalad push --to joc-storage
# and the output branch
flock --verbose $DSLOCKFILE git push outputstore

echo SUCCESS
# job handler should clean up workspace
```

**Comment by mattcieslak** [comment]
Thank you @adswa, this is super helpful! I will try this out on our system. Are you thinking it would be good to update the enki fmriprep section with this version? If so I can start a PR

**Comment by adswa** [comment]
Thanks for offering!
As a cautionary advice, it may be a bit early for changes that need a lot of time. The section is quite a beast and we are still in the middle of poking this workflow for holes and edge cases on different computing infrastructure and datasets - I wouldn't want your work to be in vain. But by all means, please start a PR with any quick changes you have in mind or simply notes on where things need to be changed! :)

**Comment by mattcieslak** [comment]
Would you be open to sharing the contents of `code/cat_standalone_batch.txt` and `code/finalize_job_outputs.sh`? If you don't want to post them publicly, could you email them to matthew.cieslak at pennmedicine.upenn.edu? I assume these scripts delete things that would cause a merge conflict, preventing the pre-octopus-merge step of creating the `msub-` branches?

**Comment by adswa** [comment]
Personally, I don't see a reason why to not share it publicly, but I haven't authored these scripts and there is a paper being written on the workflow - let me check in with all involved people, I don't want to step onto the toes of people more senior than me...

> I assume these scripts delete things that would cause a merge conflict, preventing the pre-octopus-merge step of creating the msub- branches?

The first is a batch file for CAT12 segmentation, mean GM ROI extraction to csv, and TIV & tissue volume extraction for a SPM12 standalone installation, and the latter takes a CAT output structure and packages the desired pieces into a set of compressed tarballs.

I'm not sure if they are useful for you, but I've reached out to everyone involved and hope to get back soon.

Out of curiosity, what merge conflicts are you seeing? We didn't need to accommodate for merge conflicts, and with fmriprep only had one in the "CITATION.md" files. Happy to help/take a look.

**Comment by adswa** [comment]
[cat_standalone_batch.txt](https://github.com/datalad-handbook/book/files/6118761/cat_standalone_batch.txt)


[finalize_job_outputs.txt](https://github.com/datalad-handbook/book/files/6118769/finalize_job_outputs.txt)

**Comment by adswa** [comment]
@mattcieslak 🠕

**Comment by mattcieslak** [comment]
Also very helpful, thanks again @adswa. This workflow looks pretty different from the setup in the ENKI chapter. 

>  Out of curiosity, what merge conflicts are you seeing?

The merge conflicts are the same that you saw - the stuff in logs/, so I thought maybe you deleted them in the containers-run so you wouldn't have to make new branches before the octopus merge.


Is this no longer needed?
```
git submodule foreach --recursive git annex dead here
```

Here is my attempt to get a working example using an external push RIA dataset

```bash

# Create a dataset for the analysis
EXAMPLE_DIR=${PWD}
datalad create -d source_ds
# Add some inputs
datalad install -d source_ds ///openneuro/ds000007
# Create a subdataset that will contain outputs
datalad create \
    -d source_ds \
    -D "prep outputs" \
    source_ds/prep

# Create its RIA sibling 
datalad create-sibling-ria \
    -d source_ds \
    --name push_data_sink \
    ria+file://${EXAMPLE_DIR}/sink_ds

# Find the actual path to the RIA store
RIA_DIR=${EXAMPLE_DIR}/sink_ds/???/*

# Then simulate a run of a pipeline 
mkdir tmp
cd tmp
datalad clone ${EXAMPLE_DIR}/source_ds ds
cd ds
git remote add outputstore ${RIA_DIR}

# Check what the remotes are
datalad siblings

# Get the input data
datalad get -n -r -R1 .
datalad get -r ds000007/sub-01

# Change the branch, we'll "process" sub-01
git checkout -b sub-01

# Instead of running a prep, just copy the inputs to the output dir
datalad run \
    -m "fake job" \
    -i ds000007/sub-01 \
    -o prep \
    cp -r ds000007/sub-01 prep/

datalad push --to push_data_sink-storage
git push outputstore
cd ..

# Do another subject, this time sub-07
datalad clone ${EXAMPLE_DIR}/source_ds ds2
cd ds2
git remote add outputstore ${RIA_DIR}

# Check what the remotes are
datalad siblings

# Get some input data
datalad get -n -r -R1 .
datalad get -r ds000007/sub-07

git checkout -b sub-07

# Instead of running a prep, just copy the inputs to the output dir
datalad run \
    -m "fake job" \
    -i ds000007/sub-07 \
    -o prep \
    cp -r ds000007/sub-07 prep/

datalad push --to push_data_sink-storage
git push outputstore
```

This all runs without a problem and it looks like the branches made it to the RIA store, but I'm not sure what to do next. If I do

```shell
$ cd $RIA_DIR
$ git branch -v
  sub-01 c07699a [DATALAD RUNCMD] fake job
  sub-07 8f1397c [DATALAD RUNCMD] fake job
$ git merge -m "Merge results" $(git branch -l | grep 'sub-' | tr -d ' ')
fatal: this operation must be run in a work tree
```

How does the final octopus merge happen?

**Comment by adswa** [comment]
It took a while, but an initial documentation is in place. Currently, the handbook will only point to it (#783) because we have plans to refine the workflow even further and its best to only have one place to do this in, but it eventually will become a full replacement for ENKI.
