### ISSUE TITLE
Confusing depiction of quotes for procedure configs

### ISSUE THREAD

**Issue by bpoldrack** [datalad-handbook/book#688]
As reported in https://github.com/datalad/datalad/issues/5493, the "Find out more" section "Write your own procedures" in https://handbook.datalad.org/en/latest/basics/101-124-procedures.html, somewhat suggests that within the respective config file quotes are needed for the help string and call format string of a procedure. This seems to be suggested by this part:

> Below is a minimal .datalad/config entry for a custom procedure:

> `[datalad "procedures.<NAME>"]`
> `     help = "This is a string to describe what the procedure does"`

However, neither are those quotes required in the config file, nor would the later shown call to `git-config`

> `$ git config -f .datalad/config datalad.procedures.example.help "A toy example"`

result in such quotes, nor can the quotes be achieved by using `ConfigManager.set/add` via datalad's python API.
Quotes are only needed within such command line calls (to not make "A toy example" 3 arguments to `git-config`), not within the config files itself. They don't hurt when put there by editing the config file either - they simply make no difference when we read the config.

ping @pvavra

**Comment by adswa** [comment]
Could you PR a quick improvement, @bpoldrack? Thanks in advance!

**Comment by bpoldrack** [comment]
@adswa : PR filed. However, it's just about this particular section. The underlying issue might show elsewhere, too, since this is by no means specific to those particular configs, but to `git-config` in general.

**Comment by adswa** [comment]
I think these quotes were just not spotted in the review of the procedures section that was added a while after the general configuration sections: https://github.com/datalad-handbook/book/pull/158#issuecomment-531173048
Typically, glimpses into config files are based on actual, existing config files where such quotes wouldn't show up, but if you spot any, please let me know.
