### ISSUE TITLE
Permalinks section so it is searchable on the main page somewhere

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#696]
Often need to find a permalink to some section, and having a page on the website with them would be super useful

**Comment by mih** [comment]
We have http://handbook.datalad.org/r.html for that. Not all links to all sections, but those links to those section for which "perma" is actually being taken care off.

**Comment by yarikoptic** [comment]
That is exactly the page I was looking for, thank you. What I thought it might be nice to include a version of it (without the warning) to be referenced within the table if context so it could be easily found. But now that I know that it is there I guess I coughs search it up after I forget that it is r.html ;-)
