### ISSUE TITLE
Use GIN as autoenabled data source

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#706]
Something like this would work:

```
datalad siblings add \
  -d . \
  --name gin-update \
  --pushurl git@gin.g-node.org:/studyforrest/aggregate-fmri-timeseries.git \
  --url https://gin.g-node.org/studyforrest/aggregate-fmri-timeseries.git \
  --as-common-datasrc gin
```

But ATTN: https://github.com/datalad/datalad/issues/5621

Also, when there the GIN project is still empty (not initialized with any default content), git-annex does not find an annex and configures it to be ignored (annex-ignore). This prevents `datalad push` from uploading any files.

So:

`git config --unset-all remote.gin-update.annex-ignore`

**Comment by adswa** [comment]
I have PRed #707
