### ISSUE TITLE
Typo causes broken ref in handbook

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#709]
**What does not work?**

There's a broken `ref` tag on the page: http://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html
Easy fix.

**Background information**
I was reading through the handbook around 11pm, as one does, and spotted it.

**Screenshots/Trace backs**
<img width="671" alt="Screenshot 2021-05-11 at 23 14 27" src="https://user-images.githubusercontent.com/10141237/117885988-de62c280-b2ae-11eb-870d-9e311d52a6b2.png">

**Additional context**
I can add a PR to fix.

**Comment by adswa** [comment]
Thank you! :)
