### ISSUE TITLE
Walkthrough for setting up S3 as special remote

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#712]
# Feature description and question

**Is your feature request related to a problem? Please describe.**
The handbook's section on [Setting up 3rd party services to host your data](http://handbook.datalad.org/en/latest/basics/101-138-sharethirdparty.html#setting-up-3rd-party-services-to-host-your-data) contains a thorough walkthrough of using `rclone` with Dropbox to set up a special remote for a datalad dataset. The handbook also points to a [useful resource](https://git-annex.branchable.com/tips/public_Amazon_S3_remote/) for doing the same with Amazon S3. However, IMO the latter instructions could be more user friendly and would ideally be written from the datalad context. 

**Describe the solution you'd like**
Would such walkthrough for setting up a special remote on an Amazon S3 bucket be a useful addition to the handbook? Or should it live elsewhere?

**Describe alternatives you've considered**
I've started jotting down some steps for the walkthrough, based on successfully setting it up locally. Feedback welcome!!

---

### Step 0: Dependencies
- Verified AWS account
- datalad, git and git-annex
- awscli (don't think it's a dependency, but still a useful command line tool to have when working with AWS.

### Step 1: AWS credentials
Get the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from your AWS account. If you don't have an account, create one. You will need to submit your credit card and address details. After login at https://console.aws.amazon.com/, you can generate a new access key by going to your username in the top right tab, then: 

Select your username dropdown > My Security Credentials > Access keys > Create New Access Key

Next, export your access key id and secret:

**Code to run:**
```bash
export AWS_ACCESS_KEY_ID="<your-key-id>"
export AWS_SECRET_ACCESS_KEY="<your-secret>"
```

### Step 2: Create or navigate to the local version of your datalad dataset

In the example below, we create a new directory and copy sample data to it (a TSV file and a few JPEGs and JSOn files). You can copy whichever files you prefer. We use the `force` flag with `datalad create` to turn the existing data directory into a datalad dataset, then save the dataset.

*NOTE: ensure that the datalad/git repository is being created with default branch as main, to prevent this issue: https://github.com/datalad/datalad/issues/4997. This issue can occur when you eventually push to your github sibling. To set main as default branch, you can change your global git config:
      `git config --global init.defaultBranch main`*

**Code to run:**
```bash
cd <wherever-you-want-to-create-the-dataset>
mkdir datalad-s3-test
cd datalad-s3-test
cp -a /Users/jsheunis/Documents/test-data/ .
datalad create --force --description "test datalad repo on s3"
datalad save
```

### Step 3: Initialise the S3 special remote

This has been adapted from https://git-annex.branchable.com/tips/public_Amazon_S3_remote/).

First we run `datalad siblings` to confirm that the only "sibling" is the current dataset (`>> .: here(+) [git]`). Then we create a variable with the intended bucket name where your annexed data will be available on S3. This bucket and its contents will be public. Then we call `git annex initremote` to create the special remote on S3 for the dataset. Many options are available (see https://git-annex.branchable.com/special_remotes/S3/).

Options used below include:
- `public-s3`: name of the special remote
- `type=S3`: the type of special remote (git-annex can work with many types: https://git-annex.branchable.com/special_remotes/)
- `encryption=none`: no encryption (alternatively enable encryption=shared, meaning files will be encrypted on S3, and anyone with a clone of the git repository will be able to download and decrypt them)
- `bucket=$BUCKET`: using the declared variable, the name of the bucket to be created on S3. 
- `public=yes`: Set to "yes" to allow public read access to files sent to the S3 remote
- `datacenter=EU`: defaults to "US" if not specified, but here we use "EU" (which is EU/Ireland, a.k.a. eu-west-1)

After running `git annex initremote...` successfully, run `datalad siblings` to see that a sibling has been added (`>> .: here(+) [git]` `>>.: public-s3(+) [git]`).

You can now also navigate to https://console.aws.amazon.com/s3/ and navigate to Buckets to seee your newly created bucket. It should only have a sinle annex-uuid file as content, since nothing has been pushed yet.

**Code to run:**
```bash
datalad siblings
BUCKET="<your-public-bucket-name>"
git annex initremote public-s3 type=S3 encryption=none bucket=$BUCKET public=yes datacenter=EU
datalad siblings
```

### Step 4: Enable the special remote for `git-annex`

For `git-annex` to be able to download files from that bucket without needing your AWS credentials, you then need to tell it the url of the bucket. This url takes a standard format, and can be copied from your AWS console as well.

**Code to run:**
```bash
git annex enableremote public-s3 publicurl="https://$BUCKET.s3-eu-west-1.amazonaws.com"
```

### Step 5: Create GitHub sibling.

The special remote is now set up, and we want to give people access to the `datalad` dataset. A common way to do this is to create a sibling of the dataset on GitHub with the command `create-sibling-github`. In order to link the contents in the S3 special remote to the GitHub sibling, we also need to configure a publication dependency to the `public-s3` sibling, which is done with the `publish-depends <sibling>` option: 

**Code to run:**
```bash
datalad create-sibling-github -d . datalad-s3-test --publish-depends public-s3
```

### Step 6: Push the GitHub sibling

Because of the publication dependency, datalad will push the dataset annex contents to the special remote (i.e. the S3 bucket) first.
Once the publishing step has finished successfully, you will be able to see the annex file contents (with md5 hashes as filenames) in the S3 bucket in your AWS console.

You will also be able to view the newly created GitHub repository (if the repo defaults to the git-annex branch, refer to the note and issue mentioned in Step 1 above)

**Code to run:**
```bash
datalad push --to github
```

### Step 7: Test the setup!

You have now successfully created a datalad dataset with a special s3 remote for annexed file content and with a public GitHub sibling from which the dataset can be cloned. Now we can test the setup to see if it works.

First we clone the dataset from the GitHub repo URL to a new location on your machine. You will likely see a notification similar to the following:
    `"access to 1 dataset sibling public-s3 not auto-enabled, enable with:..."`

This requires someone who wants to access the data to enable the special remote, using the `datalad siblings` with the `enable` action. Once enabled, you should be able to `datalad get` individual files.

**Code to run:**
```bash
cd <new-location>
datalad clone https://github.com/<enter-your-your-organization-or-account-name-here>/datalad-s3-test.git
datalad siblings -d . -s public-s3 --as-common-datasrc enable
datalad get datalad-s3-test/<location-of-file-you-want-to-get>
```

**Comment by adswa** [comment]
> Would such walkthrough for setting up a special remote on an Amazon S3 bucket be a useful addition to the handbook? Or should it live elsewhere?

It would be a super super useful addition to the handbook, and fit in really well into the third party sharing chapter :)

> NOTE: ensure that the datalad/git repository is being created with default branch as main, to prevent this issue: datalad/datalad#4997. This issue can occur when you eventually push to your github sibling. To set main as default branch, you can change your global git config:
git config --global init.defaultBranch main

Side thought: In the context of the handbook I have been pondering for a while now whether we should switch everything to ``main``. I was reluctant to do so so far. For one, because of the amount of adjustments in the handbook and its resources. And second, because I feared causing confusion in novices in early parts of the book where it is too early to talk about the concept of branches, but commands and command outputs may mismatch if someone's default branch is master. However, seeing your snippet here, I thought that it could (in addition to being mentioned in the walk-through) be useful to simply add it into the installation instructions, in the section on Git configuration, together with a note that while ``master`` was the default, ``main`` becomes the new and more useful standard.
I thought I already had it somewhere, but it is definitely useful to have an FAQ on the git-annex branch as the default on GitHub confusion - I will open an issue on this. Thanks again for raising this.

> Step 3: Initialise the S3 special remote

I don't have an S3 account to test this with, but I think, because git annex supports S3 so seamlessly, you could pass the ``autoenable`` parameter to the initremote call (@mih, @yarikoptic please correct me if I am wrong here). From the [docs](https://git-annex.branchable.com/git-annex-initremote/):

> To avoid git annex enableremote needing to be run, you can pass "autoenable=true". Then when git-annex is run in a new clone, it will attempt to enable the special remote. Of course, this works best when the special remote does not need anything special to be done to get it enabled.


I'm really excited about having a wlakthrough like this in the handbook :) How can I best help you in getting this into the handbook?

**Comment by Remi-Gau** [comment]
Right now I am testing this to see if I can wrap my head around it.

I nudged @jsheunis a couple of days ago by saying:
> "Wouldn't it be nice if there was an S3 walkthrough?"

And because he is as able as me to say "no", here it is. And now I feel I need to make sure I give him a review on this. :-)

**Comment by mih** [comment]
Cool stuff!

> pass the autoenable parameter to the initremote call

If the credentials are known or not needed this should work!

**Comment by jsheunis** [comment]
Thanks @Remi-Gau :)

And thanks for the detailed comments @adswa

> It would be a super super useful addition to the handbook, and fit in really well into the third party sharing chapter :)

Great!

> Side thought: In the context of the handbook I have been pondering for a while now whether we should switch everything to main. I was reluctant to do so so far. For one, because of the amount of adjustments in the handbook and its resources. And second, because I feared causing confusion in novices in early parts of the book where it is too early to talk about the concept of branches, but commands and command outputs may mismatch if someone's default branch is master. However, seeing your snippet here, I thought that it could (in addition to being mentioned in the walk-through) be useful to simply add it into the installation instructions, in the section on Git configuration, together with a note that while master was the default, main becomes the new and more useful standard.
I thought I already had it somewhere, but it is definitely useful to have an FAQ on the git-annex branch as the default on GitHub confusion - I will open an issue on this. Thanks again for raising this.

Sounds good to me, let me know if I can help.

> I don't have an S3 account to test this with, but I think, because git annex supports S3 so seamlessly, you could pass the autoenable parameter to the initremote call

Thanks for pointing out what I missed, I will try it out now and report back.

>I'm really excited about having a wlakthrough like this in the handbook :) How can I best help you in getting this into the handbook?

- I think the best help would be some input/feedback on the wording and context of the walkthrough steps. Since I'm not yet experienced with the wider datalad + git-annex ecosystem, there might be sentences that could do with restructuring, content or tips that could be added, or datalad commands that could be improved.
- Another help would be to suggest how to make this walkthrough slot in with the rest of that page in the handbook, as well as with the build process. E.g. should we use the same example dataset that was used for the Dropbox example? And which is the best way to automate capturing the shell output (I've already forgotten the gist of what you explained to me regarding building the book, sorry...)
- Another point: for the time being we can use my AWS account for the walkthrough, as long as the example data that we push to the S3 bucket is not large (I don't want to end up with unexpected costs, although this is probably highly unlikely). Alternatively, we don't have to link to an actual S3 bucket that the users can see and we can just illustrate the steps and results with screenshots.

**Comment by jsheunis** [comment]
> If the credentials are known or not needed this should work!

It works :)

**Comment by adswa** [comment]
> I think the best help would be some input/feedback on the wording and context of the walkthrough steps. Since I'm not yet experienced with the wider datalad + git-annex ecosystem, there might be sentences that could do with restructuring, content or tips that could be added, or datalad commands that could be improved.

Certainly! I think we could get the best UX if you paste your current contents into a file and PR them. I suggest to add them in a file ``docs/basics/101-139-s3.rst`` (you will also need to add ``101-139-s3`` into the table-of-contents toc-tree in the file ``docs/basics/basics-thirdparty.rst``

> Another help would be to suggest how to make this walkthrough slot in with the rest of that page in the handbook, as well as with the build process. E.g. should we use the same example dataset that was used for the Dropbox example? And which is the best way to automate capturing the shell output (I've already forgotten the gist of what you explained to me regarding building the book, sorry...)

It doesn't necessarily need to fit in super well. Based on the analytics of readthedocs, I think the section on third party sharing is one that is often visited by people who have not read the rest of the book. If there is something self-contained that we could add there (especially for something that is as popular as S3), many people will be happy. Alternatively, you can publish the ``datalad-101`` dataset at the state that it is in at that point in the handbook. I have a tagged dataset that you could use for this.

wrt to the shell output, you can use the following mark-up:

```
.. runrecord:: _examples/DL-101-139<consecutive-numbering-starting-at-101>
  :language: console
  :workdir: dl-101/DataLad-101 [if you are publishing the datalad-101 dataset, else invent a path]

   # this is a comment
   $ this-line-is-executed and its output captured
```

The software setup is detailed in http://handbook.datalad.org/en/latest/contributing.html (its a hacky setup, I'd say we get started even with only a draft and whack at it together until the CI is green ;) ). But also, see below:

> Another point: for the time being we can use my AWS account for the walkthrough, as long as the example data that we push to the S3 bucket is not large (I don't want to end up with unexpected costs, although this is probably highly unlikely). Alternatively, we don't have to link to an actual S3 bucket that the users can see and we can just illustrate the steps and results with screenshots.

I think we should not use your S3 account. It could potentially cause costs, it requires quite some additional setup to automate this in a way that it works after the first push (e.g., to actually push the data with every new build we would need to remove it from the bucket first), and its also not done for the rclone example. Its not ideal because we can't find out when the workflow breaks, but it is a fairly stable workflow.  So I am all for your suggestion of illustrating the general process with ``.. code-block: bash`` mark-up and screenshots.

**Comment by adswa** [comment]
There are too many pitfalls to mention in advance, but one thing came to my mind: screenshots should go into ``docs/artwork`` - this is a subdataset (https://github.com/datalad-handbook/artwork) though, so it needs an extra (or recursive) push. No need for PRs in that submodule, you can push to master. Also, commit the files directly to Git (just try to keep them small-ish). There is ``optipng`` for squashing pngs if your screenshots are large,

**Comment by adswa** [comment]
Worthwhile to copy the "importantnote" from  http://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html#publishing-the-dataset-to-github into the file, following @Remi-Gau pointing out in the DataLad channel  that user-password-auth is not working for him

**Comment by Remi-Gau** [comment]
Well also add a "Remi is a dumb dumb, so your mileage may vary." in a footnote too while you're at it.

**Comment by Remi-Gau** [comment]
OK thanks to @adswa 's tip on the datalad channel I am now pushing 30 Go of ephys and microscopy data to an S3 bucket.

So until Step 6 I am now good.

Conceptually there are a couple of things that I struggled with and that maybe are mentioned somewhere in the Handbook but that I have not come across yet:

- I assumed that the S3 sibling would behave like my GIN sibling and that I could push to it "as is" with a `datalad push --to public-s3`.  Is it that is is not possible and that you "must" have a "github front" while the data is on the S3? 

- Somewhat related: I suspect we might want to mention, how to setup private S3 bucket (does it then have to be associated with a private repo on github)? Private repos are the default on GIN and I suspect that some people would like how to know this.

- Regarding the github token: I was unclear which options to tick using the GUI among the  many available (https://docs.github.com/en/developers/apps/scopes-for-oauth-apps): I gave the `repo` access only and that worked but maybe that is already too much. 
I did try to use https://github.com/sociomantic-tsunami/git-hub but I got stuck into the 4th circle of dependency hell... :smiling_imp:

**Comment by Remi-Gau** [comment]
> Well also add a "Remi is a dumb dumb, so your mileage may vary." in a footnote too while you're at it.

FYI this was meant as a bout of self deprecating humor, but it reads as very passive agressive. Sorry about that. 
Gosh I am cranky today.

**Comment by adswa** [comment]
> > Well also add a "Remi is a dumb dumb, so your mileage may vary." in a footnote too while you're at it.
> 
> FYI this was meant as a bout of self deprecating humor, but it reads as very passive agressive. Sorry about that.
> Gosh I am cranky today.

Never received as anything but humor :)

**Comment by yarikoptic** [comment]
I think the best use of S3 with git-annex is to 

- have a bucket with versioning turned on
- establish the remote with "exporttree=true"

since then the "tree" on s3 bucket would be readily usable without git-annex, while git-annex would also record `versionId`s for each exported file, thus making prior versions available as well even after a new ones re-exported for the same key.  That is how openneuro exports their datasets to s3.

More details on additional aspects for "public" setup (so keys would also be exposed via direct https urls) is available from https://git-annex.branchable.com/tips/publishing_your_files_to_the_public/ . Not sure what aspects would be different for non-public.

**Comment by jsheunis** [comment]
@adswa thanks for all the pointers, I'll get going with a single file and with bash code blocks and screenshots. If i can figure it out, I'll use the `Datalad-101` dataset.

Thanks @yarikoptic , I can add these options.

Slightly off-topic question @adswa and @Remi-Gau, which "DataLad channel" are you referring to?

**Comment by adswa** [comment]
> If i can figure it out, I'll use the Datalad-101 dataset.

There is one under this organization, but I just realized its quite outdated. I have pushed an up-to-date dataset to juseless: ``/data/project/deleted_every_sunday/DataLad-101``.

**Comment by Remi-Gau** [comment]
Did I mess up something or is it normal that the git-annex branch is the default in the `github` remote?

**Comment by adswa** [comment]
No, github just doesn't treat ``master`` as the default branch anymore, and if it can't find a ``main`` branch, it takes the first one in alphabetical order,  I think: https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/

You can change the default branch via githubs web interface :)

Stephan also noticed this problem, and it's about time it gets into the handbook... it's quite confusing to see the git-annex branch (#713)

**Comment by Remi-Gau** [comment]
oh ok I saw that convo but did not connect the dots. Thanks for the clarification.

**Comment by yarikoptic** [comment]
FWIW: if you use `datalad create-sibling-github` and `datalad push` for your initial push, default branch would be "set correctly" since datalad 0.14.1

**Comment by Remi-Gau** [comment]
> FWIW: if you use `datalad create-sibling-github` and `datalad push` for your initial push, default branch would be "set correctly" since datalad 0.14.1

Time to update datalad then!!

**Comment by jsheunis** [comment]
> I think the best use of S3 with git-annex is to
> - have a bucket with versioning turned on
> - establish the remote with "exporttree=true"

> since then the "tree" on s3 bucket would be readily usable without git-annex, while git-annex would also record versionIds for each exported file, thus making prior versions available as well even after a new ones re-exported for the same key. That is how openneuro exports their datasets to s3.

@yarikoptic the [S3 special remote docs](https://git-annex.branchable.com/special_remotes/S3/) say that setting `exporttree=yes` will result in it not being "usable as a general-purpose special remote."

What does this mean, and is this a concern for the above use case or otherwise?

**Comment by jsheunis** [comment]
FYI https://github.com/datalad/datalad/issues/5684

**Comment by jsheunis** [comment]
@adswa Can you add me as a collaborator on the artwork submodule? I don't currently have push access to it.

**Comment by adswa** [comment]
Sorry, only saw this now. thanks for raising it in the chat again.

**Comment by jsheunis** [comment]
Closing since this was completed with PR #721
