### ISSUE TITLE
Problems with setup for contributing to the handbook on macOS

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#714]
I'm going through the [instructions](http://handbook.datalad.org/en/latest/contributing.html) on how to  set up my machine for contributing to the Handbook.

I have  a Macbook pro running macOS Big Sur (v11.2.3). I can run the `datalad install` command fine, I can set up a virtual environment correctly, and then I can successfully `pip install` the requirements. But after that, I am running into some discrepancies and issues when following the instructions:

1. I use `brew` to manage packages. It seems that the closest to the suggested `librsvg2-bin` package that is available via `brew` is `librsvg`. I hope this provides the required functionality, but have not been able to test it.
2. I cannot create a new directory in the `/home` directory: `mkdir: /home/me: Operation not supported`. This is most likely a problem with the way macOS is shipped, where the `/home` dir is protected since it's used as some sort of mounting point ([see e.g. here](https://apple.stackexchange.com/questions/88797/how-to-execute-mkdir-in-home-directory)). There are options to change this, e.g. by editing the `etc/auto_master` file ([see example](https://www.programmersought.com/article/2831410481/)), but this file is locked on my local system (even when opening as root).

Am I missing something? Or will my inability to complete this step outlined in point 2 above result in me not being able to build the handbook locally? It seems like at least a single person with a Mac must have already built the book successfully, but no-one complains when things work :) I couldn't find existing similar closed/open issues though.

**Comment by adswa** [comment]
Hey, thanks for sharing these difficulties. As far as I am aware, no Mac has ever built the handbook, so its good to know where difficulties lie.

> I use brew to manage packages. It seems that the closest to the suggested librsvg2-bin package that is available via brew is librsvg. I hope this provides the required functionality, but have not been able to test it.

I don't know it, but the description sounds promising. We need it to render svg's into PDF

> I cannot create a new directory in the /home directory: mkdir: /home/me: Operation not supported. This is most likely a problem with the way macOS is shipped, where the /home dir is protected since it's used as some sort of mounting point (see e.g. here). There are options to change this, e.g. by editing the etc/auto_master file (see example), but this file is locked on my local system (even when opening as root).

oh, I didn't know. Inside of ``docs/conf.py`` you can find the variable ``autorunrecord_basedir``. It is set to ``/home/me``, but this can become any other directory. I have always kept it in ``/home``, but you could also point this into for example ``/tmp`` (if mac has ``/tmp``?) 

Hope this works better. :)

You should be able to run ``make`` without this setup nevertheless. It needs step 2 in order to build new example code snippets from ``.. runrecord:`` directives.

**Comment by jsheunis** [comment]
Thanks Adina, good to know! Will update here with more Mac-related comments.

**Comment by jsheunis** [comment]
Ok, the book builds successfully on my Mac, yay! In case it's useful for other mac users, these are the steps I followed:



#### 1 - Get the code
Fork the handbook repo and clone my fork with datalad:
```
datalad install -r https://github.com/jsheunis/book.git
```

#### 2 - Create a virtual environment
I use [miniconda3](https://docs.conda.io/en/latest/miniconda.html):
```
conda create -n datalad-handbook python=3
conda activate datalad-handbook
```

#### 3 - Install requirements and custom helper
```
cd book
pip install -r requirements.txt
pip install -e .
```

#### 4 - Install `librsvg`
Not sure yet if it will do the required job, will report back on that.
```
brew install librsvg
```

#### 5 - Change execution directory
In `book/docs/conf.py`, change `autorunrecord_basedir`:
```
autorunrecord_basedir = '/tmp/me'
```
Also, remember to create the directory:
```
mkdir /tmp/me
```

#### 6 - Create mock Git identity
```
$ HOME=/tmp/me git config --global user.name "Elena Piscopia"
$ HOME=/tmp/me git config --global user.email "elena@example.net"
```

#### 7 - Build the book!
From the root `book` directory, run `make`.

**Comment by jsheunis** [comment]
Closing this since building was successful, and instructions provided.
