### ISSUE TITLE
Incomprehension

### ISSUE THREAD

**Issue by tsankeuodelfa** [datalad-handbook/book#715]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsankeuodelfa** [comment]
Hi
I have a problem with the book on the second chapter. I am on the first part where it is to create a schell skript that will browse some data. There is a program underneath. I don#t know if I should write it with a program language or with the window command.  I tried to write this program on the window command without success

**Comment by adswa** [comment]
Hi @tsankeuodelfa, thanks for opening an issue here! :)

Are you referring to this part (see screenshot below)?
![Screenshot from 2021-05-19 10-16-51](https://user-images.githubusercontent.com/29738718/118779503-65a1ce80-b88b-11eb-9713-6049b851d496.png)

> There is a program underneath. I don#t know if I should write it with a program language or with the window command. 

Inside of the "Windows Wit" Box there is a hint that the code should be written into a new file with an editor (for example Notepad+). Can you try to open an editor, copy the contents of the code block in the Windows Wit into it, and save it under the name ``list_titles.sh`` in the directory ``DataLad-101\code``?

The Unix version below (the lines that start with a ``cat`` command) does not work in all terminal types on Windows. 
Could you tell me which "windows command"/terminal exactly you mean (for example the ["windows cmd"](https://de.wikipedia.org/wiki/Cmd.exe), an [Anaconda prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/), or a ["Git Bash"](https://gitforwindows.org/))? It would be helpful to know this.

**Comment by adswa** [comment]
I see that this is the first issue that you have ever opened on GitHub - Well done, and congrats! :) 

Let me give you a few hints for future issues:
- The placeholder text in the issue template (what currently is in your [opening comment of this issue](https://github.com/datalad-handbook/book/issues/715#issue-895079335) can be removed. It is only a placeholder, and aims to help to structure your issue. If it does not fit, you can remove it completely, and replace it with your own description of the problem.
- GitHub has many useful features that can help you to make your text more informative. If you click on the small "M↓" symbol at the bottom right corner when editing a comment (see screenshot), it takes you to a website that explains GitHub markdown: https://guides.github.com/features/mastering-markdown/. This site shows you how to create hyperlinks, bold or italic text,  bullet lists, and much more. You can use it if you want to "style" the text of your issues.
![Screenshot from 2021-05-19 10-30-46](https://user-images.githubusercontent.com/29738718/118781673-9a168a00-b88d-11eb-831f-a1b6e329f3a0.png)
- It is very very helpful if you can include technical details of your computer and your software environment in your issue description. For example, I would be happy if you could include a description of your operating system (for example: Window 10), your version of DataLad (you can type ``datalad wtf`` in your terminal to find out, or the type of terminal you are using. 
- It is also really helpful if you could copy-paste commands that you tried and the resulting errors from your terminal into the issue. This can give me a much better idea of what went wrong, and I can try to reproduce your problem. :)

**Comment by tsankeuodelfa** [comment]
Hi thanks for your suggestion.
 I am using Window 10 and working on the window command. I tried to follow the steps in the book but the files that should be copied recordings/podcasts.tsv (for part 2.2 of the book) were not done and I don't know why. 
![datalad1](![data2](![ed1](https://user-images.githubusercontent.com/83062549/118936752-1cb24e80-b94d-11eb-82df-0f32e2b855dc.PNG)/118935476-e0cab980-b94b-11eb-838c-11dc5cf6e193.PNG) 
![data3](![e++d1](https://user-images.githubusercontent.com/83062549/118936752-1cb24e80-b94d-11eb-82df-0f32e2b855dc.PNG)/118935597-ff30b500-b94b-11eb-933c-c3f82e54d52f.PNG)
the podcast file exists but it is empty.

- As for my problem yesterday, I created the requested list in the window command and wrote the program. I don't know if this is where my error came from
![ed](https://user-images.githubusercontent.com/83062549/118936484-dfe65780-b94c-11eb-803d-eb46501258f5.PNG)

**Comment by tsankeuodelfa** [comment]
Hi thanks for your suggestion.

 I am using Window 10 and working on the window command. I tried to follow the steps in the book but the files that should be copied recordings/podcasts.tsv (for part 2.2 of the book) were not done and I don't know why. 
![datalad1](https://user-images.githubusercontent.com/83062549/118938287-c6dea600-b94e-11eb-8481-6f15ebf458ca.PNG)
![data2](https://user-images.githubusercontent.com/83062549/118938312-cb0ac380-b94e-11eb-8fe4-eae97e62e263.PNG)


-

**Comment by tsankeuodelfa** [comment]
the podacst file exists but does not contain the required files and is not even displayed on the window command(picture 2)
![ed1](https://user-images.githubusercontent.com/83062549/118938898-6bf97e80-b94f-11eb-876b-1358c7871d40.PNG)

**Comment by tsankeuodelfa** [comment]
As for my problem yesterday, I created the requested list in the Window command and wrote the program. I don't know if this is where my error came from. 
![ed](https://user-images.githubusercontent.com/83062549/118939122-a82cdf00-b94f-11eb-8caa-abae2c15b254.PNG)

**Comment by adswa** [comment]
Hey, thanks for providing so much information and all of the screenshots! This helps a lot :) 
I'll try to hypothesize where the problem lies. For this, I'm taking a look into the error messages your screenshots show. One error message says "code/list_titles.sh: No such file or directory". This could either be due to the fact that the script you wrote (which looks good!) is placed in the wrong directory, or that the path specification (which currently uses Unix' way of using forwardslashes ``/`` instead of backslashes ``\`` ) is not understood by ``cmd``.
Let's try to see if this hypothesis is true: 
- Can you check if ``list_titles.sh`` is inside a directory ``code/``?
- If yes, can you try to run the ``datalad run`` command with backslashes in the path (``datalad run -m "create a list of podcast titles" "bash code\list_titles.sh  > recordings/podcasts.tsv"``)?

**Comment by adswa** [comment]
You wrote:

> the podacst file exists but does not contain the required files and is not even displayed on the window command(picture 2)

The screenshot shows that the file was created empty (its size is 0kB). This is likely due to the fact that the script (``code/list_titles.sh``) was not executed (because it wasn't found), but the remainder of the command ``> recording/podcasts.tsv`` was. I would suggest that you remove (delete) this file before retrying the command.

**Comment by tsankeuodelfa** [comment]
I took all your suggestions into account and started the exercise again. Concerning the creation of the list (list_titles.sh) since it is a shell I read on the internet that the adequate Windowcommand for the creation of this file is "copy NUL". curiously when I type tree in the code section there is nothing yet the list has been created. I also used "datalad create list_titles.sh" but it creates a file and I didn't know where to copy the code. So I opted for the first command. But the script still hasn't been executed. 
![data4](https://user-images.githubusercontent.com/83062549/118966479-154d6e00-b96a-11eb-93d3-2a68b6958b60.PNG)
![data 5](https://user-images.githubusercontent.com/83062549/118966553-1e3e3f80-b96a-11eb-96dc-973ed3743541.PNG)

**Comment by tsankeuodelfa** [comment]
![ed2](https://user-images.githubusercontent.com/83062549/118966713-28f8d480-b96a-11eb-9eb4-08dbc0b5bc2d.PNG)

**Comment by tsankeuodelfa** [comment]
I took all your suggestions into account and started the exercise again. Concerning the creation of the list (list_titles.sh) since it is a shell I read on the internet that the adequate Windowcommand for the creation of this file is "copy NUL". curiously when I type tree in the code section there is nothing yet the list has been created. I also used "datalad create list_titles.sh" but it creates a file and I didn't know where to copy the code. So I opted for the first command. But the script still hasn't been executed.
![data 6](https://user-images.githubusercontent.com/83062549/118967056-85f48a80-b96a-11eb-85fb-960759b16022.PNG)
![data 5](https://user-images.githubusercontent.com/83062549/118967074-8a20a800-b96a-11eb-8e2e-c3d0a50e3762.PNG)

**Comment by adswa** [comment]
Shall we schedule a videocall to sort this one out interactively?

**Comment by adswa** [comment]
>  I also used "datalad create list_titles.sh"

This will create a dataset (so a new directory), not a file. The way you created ``list_titles.sh`` with an editor was fine. :)

**Comment by adswa** [comment]
You can join me in this video call (it works in your browser, no app required), if you have time: https://meet.jit.si/DataLad

**Comment by tsankeuodelfa** [comment]
> Shall we schedule a videocall to sort this one out interactively?

please Yes!!
