### ISSUE TITLE
More Windows adorable quirks...

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#719]
I am reusing my windows machine these days (don't judge me: this is just another strategy to try to work less #WorkWithTheWorstTools).

Couple of "interesting" things I (re)encountered.

Some of the ways Windows encode certain things.

- line-endings configuration can lead to showing all the lines of a file has having been changed: drove me nuts in my git early days. https://github.com/bids-standard/bids-starter-kit/pull/120#pullrequestreview-221020345

- the other one is somewhat related to line endings but not to version control: was trying to run a bash script from WSL. It screamed at me because it was getting confused by the line endings encoded by Windows. Eventually had to resort to [unix2dos](https://en.wikipedia.org/wiki/Unix2dos) to create a temporary file that would run on WSL.

Not sure how much those should be mentioned in the handbook. Gut feeling says that the first one could be worth a Wndows wit. The second one... Not sure: maybe mentioning it, in the "So Windows hey?" page.

**Comment by adswa** [comment]
Digging around in my memory. There is a configuration option during the installation of Git for Windows:

![autocrlf](https://user-images.githubusercontent.com/29738718/119141770-f58b7800-ba45-11eb-879c-b8ba453e4a85.png)

Do you remember if you had this set when you installed Git?

**Comment by Remi-Gau** [comment]
That was like a life or 2 ago... In a time where you could meet people IRL and do this thing called "travel"...

No recollection, but having reinstalled git on another Windows machine recently, I did realize that there are more options now that should make this a VERY rare case. 

Never know when to mention those things to new-comers: hard balance between information bombardment or later frustration when things could have been prevented by said information bombardment...

Will let you decide if you think this is worth a mention: on the BIDS spec repo, I think we decided that we'll mention it if we ever come across this issue in one of our PR, but we are not in the business of teaching people about version control. :-)
So you might decide otherwise. 

LMKWYT

**Comment by adswa** [comment]
I'd say its a least worth an addition in the help chapter! :+1:  I have a huge pile of handbook todos piled up, I hope I can work myself through them this week or next
