### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by tsankeuodelfa** [datalad-handbook/book#720]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adswa** [comment]
Hi @tsankeuodelfa , what is your issue?

**Comment by tsankeuodelfa** [comment]
Hi @adswa 
I tried to work with Ubuntu (a linux system for windows) and I followed the installation procedure as in the book. At this stage here is the error that the terminal generates for me.
![ub2](https://user-images.githubusercontent.com/83062549/119218469-beb67000-bae0-11eb-90d5-dbafdcc4b29d.PNG)

**Comment by adswa** [comment]
Hi @tsankeuodelfa, that error indeed looks weird. Can you double-check that you are using WSL2 (not WSL1) for this? It may be a bug that looks like [this one](https://git-annex.branchable.com/bugs/WSL1__58___git-annex-add_fails_in_DrvFs_filesystem/) on WSL1. If you are using WSL1, please upgrade to WSL2.

**Comment by adswa** [comment]
This has been resolved in a private chat.
