### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#730]
Just noticed this dead link in the conda install section

http://handbook.datalad.org/en/latest/intro/installation.html#conda

"Detailed, platform-specific installation instruction" --> https://conda.io/projects/conda/user-guide/install/index.html

Not sure which alternative is best.

This one?

https://conda.io/projects/conda/en/latest/user-guide/install/index.html#regular-installation

**Comment by jsheunis** [comment]
Thanks for catching that, Remi!

That looks good to me. Or, alternatively, without the `#regular-installation` tag.
