### ISSUE TITLE
check external links once in a while?

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#741]
**Is your feature request related to a problem? Please describe.**

got a user reporting that a link is broken.

**Describe the solution you'd like**

automate checking of the external links.

I had done it using a custom patched version of linkchecker for bids: https://github.com/bids-standard/bids-specification/blob/f7fd3c2cb7a7fb85d3cf69a10259ea8452d1f78f/.circleci/config.yml#L22  but it seems that sphinx has `make linkcheck` so may be that one would be good enough?

with a quick run of `make linkcheck` got
```
$> xclip -o | grep broken
sphinx.errors.SphinxWarning: /home/yoh/proj/datalad/datalad-handbook/book/docs/basics/101-127-yoda.rst.rst:451:broken link: https://the-turing-way.netlify.com/reproducible_environments/06/containers#Containers_section (Anchor 'Containers_section' not found)
/home/yoh/proj/datalad/datalad-handbook/book/docs/basics/101-127-yoda.rst.rst:451:broken link: https://the-turing-way.netlify.com/reproducible_environments/06/containers#Containers_section (Anchor 'Containers_section' not found)
```
in the master branch 

There is also a good number of permanent redirects detected, might be worth addressing as well and not wait until redirects "deprecate", which is not unlikely.  Or they might just redirect to some login page like this one does:

```shell
$> grep https://jugit.fz-juelich.de/inm7/infrastructure/inm7-datalad/blob/master/inm7_datalad/resources/procedures/cfg_inm7.py /tmp/inm7-linkcheck
(line  264) redirect  https://jugit.fz-juelich.de/inm7/infrastructure/inm7-datalad/blob/master/inm7_datalad/resources/procedures/cfg_inm7.py - with Found to https://jugit.fz-juelich.de/users/sign_in
```
and thus might require a fix by sharing that repo somewhere else

**Comment by adswa** [comment]
Thanks - that is a great idea. It would be good to automate the check, maybe with a github action with a cron job...

> Or they might just redirect to some login page like this one does:
[...]
and thus might require a fix by sharing that repo somewhere else

Yeah, there is a different repo for that... need to link it, finally.

**Comment by adswa** [comment]
I've hopefully automated the check. Will fix the url when it runs the cron job the first time and should fail - fingers crossed it does!
