### ISSUE TITLE
improve the way code is displayed

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#75]
Quickly making a note of https://github.com/datalad-handbook/book/pull/73#discussion_r304781439 to remind us of a JS based solution about visually distinguishing comments and code @mih mentioned in the above command.

**Comment by adswa** [comment]
I'm seconding this issue. Basing a short DataLad intro on the book showed that it is inconvenient to copy commands with the leading `$`, especially long or multi-line commands.

**Comment by mih** [comment]
I had a quick look already, but dis not find something that would work with sphinx/pygments output out if the box. Needs a closer look.

**Comment by mih** [comment]
This could be a candidate: https://prismjs.com

It would require a bit of rewriting how we write out the html for code blocks, but looks doable.

**Comment by adswa** [comment]
@bpoldrack and I came up with another idea: "Copy-to-clipboard" buttons that copy the relevant commands directly into the clipboard, to save the need of selecting code and `CTRL-C`ing. I haven't looked into how one could do that, but it must be possible with a reasonable amount of effort, and I could learn a bit java script on the journey :slightly_smiling_face:

**Comment by adswa** [comment]
This could be helpful: https://github.com/choldgraf/sphinx-copybutton/pull/20
It's an unmerged PR towards the wonderful ``sphinx_copybutton`` extension. The copy button on its own would copy everything (including prompts and outputs), but with the changes introduced in this PR, only code gets copied and any leading prompt gets stripped away. Maybe, based on this PR, we can strip prompts based on used character (leaving comments (``#``) intact) -- this would be all it takes to make code snippets easily copied.

**Comment by adswa** [comment]
Added a "good first issue" label as to maybe attract people that are familiar with Chris's Copybutton feature during Hacktoberfest. :)

**Comment by sappelhoff** [comment]
It seems to me like sphinx-copybutton now has the feature released: 

https://sphinx-copybutton.readthedocs.io/en/latest/#strip-and-configure-input-prompts-for-code-cells

It may be as easy as adding sphinx-copybutton [here](https://github.com/datalad-handbook/book/blob/faf63a5b61bd3fa9807c53080978a88882102385/docs/conf.py#L75-L85) and [here
](https://github.com/datalad-handbook/book/blob/faf63a5b61bd3fa9807c53080978a88882102385/requirements.txt#L1)

... and defining `copybutton_prompt_text = "$ "` somewhere in [`conf.py`](https://github.com/datalad-handbook/book/blob/faf63a5b61bd3fa9807c53080978a88882102385/docs/conf.py#L1)

then users can click on the copy button and all lines prefixed with `$ ` (not the space) will be copied with that prefix stripped.

That also means that cells like this one can be copied and only the command gets put into the clipboard:

```bash
# this is a comment used for additional explanations. Anything preceded by $ is a command to try.
# if the line starts with neither # nor $, its the output of a command
$ datalad create myfirstrepo
[INFO   ] Creating a new annex repo at /home/adina/DataLad-101
create(ok): /home/adina/DataLad-101 (dataset)
```

copy it, get: `datalad create myfirstrepo`

whereas for code cells like this one (screenshot), where no "$ " prefix is found, everything gets copied.

![image](https://user-images.githubusercontent.com/9084751/99691327-664adb00-2a89-11eb-9d59-e1196ea229c4.png)
