### ISSUE TITLE
RIA store chapter mentions HTTP access, but does not explain how it is done

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#773]
### Is your feature request related to a problem?

User feedback revealed this shortcoming. `ria+http://` is mentioned, but not that it requires further setup.

### Describe the solution you'd like

I think it could be done with some pointers to a smarthttp setup for Git. There is nothing RIA-specific about it. Maybe an example config that points out

```
    SetEnv GIT_PROJECT_ROOT /...
    SetEnv GIT_HTTP_EXPORT_ALL
```

@bpoldrack may know more.

**Comment by adswa** [comment]
@bpoldrack, could you help me here to find out how to set up RIA HTTP access?

**Comment by adswa** [comment]
ping @bpoldrack
