### ISSUE TITLE
Ponder on whether to include instructions for venvs in installation

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#78]
Making note of https://github.com/datalad-handbook/book/pull/70#discussion_r304776497 in which the question is raised whether the installation instructions should show how to set everything up in a virtual environment.

**Comment by mih** [comment]
I think it is save to close this. I personally believe that the present instructions work well, and setting up virtualenvs on top of that is straightforward and generic enough to not require more detailed datalad-specific instructions.
