### ISSUE TITLE
Speed up DVC examples

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#788]
When building the handbook from scratch, the DVC/ML examples are a pain - mostly because they pull a 100MB dataset with 15k images several times (https://github.com/fastai/imagenette). We actually only need a fraction of the data (two categories instead of all 10). I was wondering if we could host a smaller version of this dataset somewhere such as datasets.datalad.org, so that we have a smaller version to pull for speed gains - removing a tiny obstacle towards automating builds/implementing CIs based on the handbook. @yarikoptic would it be possible to put a maybe 20MB archive to datasets.datalad.org? (or do you know an alternative place?)

**Comment by yarikoptic** [comment]
gin? osf?  store.datalad.org ?  but what is the license of that dataset (not sure if apache 2 of https://github.com/fastai/imagenette/blob/master/LICENSE covers dataset itself)

**Comment by adswa** [comment]
ah right, thats also easy. License is a good question, I initially thought it would. Will check if I can find out
