### ISSUE TITLE
Missing/Broken link for benchmarks in 'Going big with Datalad' section

### ISSUE THREAD

**Issue by Myrskyta** [datalad-handbook/book#797]
There is a a broken link in the section _2.1.1.2._ found at `book/docs/beyond_basics/101-160-gobig.rst`

The text reads: 
>If you are interested in up-to-date performance benchmarks, take a look at www.datalad.org/test_fs_analysis.html. This can help >to set expectations and give useful comparisons of file systems or software versions.

I did end up finding the old version for the link, but I am unsure if this was intentionally removed or not from the main site.

**Comment by adswa** [comment]
Thanks a lot for the report! Indeed, we redid the website, and this page is gone. Just for the record, in case you were interested in those (by now probably outdated) benchmarks, the sources for the old page are here: https://github.com/datalad/datalad.org/blob/92649aba9ba80221fafea467ffc990ce6c6d2cd9/content/pages/test_fs_analysis.html

@yarikoption, do you still maintain a source of benchmarks across file systems etc. that I could link by any chance? Else, we'll need to strip that sentence.

@all-contributors please add @Myrskyta for bug

**Comment by adswa** [comment]
oh I didn't realize I mistyped @yarikoptic 's github handle :facepalm: 

@yarikoptic  do you still maintain a source of benchmarks across file systems etc. that I could link by any chance? Currently, there is a broken link in the handbook to datalad.org, where we used to report those benchmarks, but this page doesn't exist anymore with the website update from December. If there is nothing, I need to strip that sentence.

**Comment by yarikoptic** [comment]
yeap, seems was removed in https://github.com/datalad/datalad.org/commit/233cb18719782db9290ec03c84384fd3f3846839 .  Source is still in the history of git and could be recovered. I do not remember if I have a separate instance of it published anywhere.  It would be nice to reincarnate it (attn @jsheunis) -- I had referenced that page in a good number of locations and AFAIK it is somewhat unique, albeit dated.  With @aqw we had hopes to redo it with more modern implementations of ZoL and BTRFS but never had that extra time.

**Comment by jsheunis** [comment]
Sorry, I missed this. @yarikoptic created an issue to recover it for the updated website: https://github.com/datalad/datalad.org/issues/113. Will post here once it's updated.

**Comment by jsheunis** [comment]
This page has been restored in https://github.com/datalad/datalad.org/pull/116 and is available on the new site: http://www.datalad.org/test_fs_analysis.html

**Comment by adswa** [comment]
Great thanks! #807 will bring it back into the book.

**Comment by adswa** [comment]
hey @Myrskyta! I have a random question: Everyone who contributes to this book is a co-author on the [PDF version](https://handbook.datalad.org/_/downloads/en/latest/pdf/). I'm currently going through the contributor list, and ask people who are named with their github handles whether they want to appear with their real name. If you want any other name than Myrskyta on it, feel free to ping me here :) Otherwise, feel free to ignore this. :)
