### ISSUE TITLE
Potential book structures

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#8]
Some thoughts emerging from an initial discussion with @loj : 

- modular approach: The book should **not** be a "read-from-start-to-end" resource. Users should be able to select modules/chapters/parts based on their knowledge and use case
- "Build your own Datalad adventure": @loj proposes this as an educational strategy and we agree that it is worthwhile to *try* to implement (if it fails, we end up with a modular structure anyways).
- We find a The Datalad Parable section in the introduction incredibly relevant and also helpful for us to get a grasp on Datalad ourselves. We've decided that we will start drafting one, building up on domain-agnostic problems and staying shorter than the original git parable if possible. To do this, we want to brainstorm domain-agnostic problems that datalad solves.
- Templates for (later) contributions by others for their individual examples with datalad. we cannot anticipate all the ways in which Datalad can be used in different fields and contexts, so these contributions will be especially relevant. With the book, we want to provide the basic building blocks people can use to assemble their use cases, and the community can contribute back by telling us how they did so.
- The introduction needs to contain an explanation of what datalad is. Both of us have the feeling that we do not grasp that yet (nor anyone else ;-) ). So our aim is to at the end have an answer to that and put it into a well-phrased summary.
- have a "things that can go wrong" section where we can talk about frequent error messages or warnings & their meanings, and where we educate people about important bits and pieces like thats its important to check the version of datalad and git-annex, how to use datalad wtf, how to seek help where, etc

**Comment by mih** [comment]
Sounds great. One comment: As mentioned before @jbpoline was also interested in this. Maybe this could live in a standalone document for a start (google doc), such that contributions and refinements are possible with zero technical threshold. Once complete, we could then import it into the book. How do you feel about that?

**Comment by adswa** [comment]
I think the has evolved a structure now, and it is fine to close this initial brain storming. Some points are reflected in the current structure (explanation of DataLad in the introduction, how-to-contribute "templates"), others were unfeasible (we couldn't achieve a modularity sufficient enough for a "build your own datalad adventure"-style, or a "not-read-from-start-to-end" book -- at least for the basics section). Some aspects are worked on elsewhere (DataLad parable). A "things that can go wrong section" is ongoing WIP in the chapter on "Help yourself".
