### ISSUE TITLE
`datalad run` chapter: more information/examples

### ISSUE THREAD

**Issue by jcolomb** [datalad-handbook/book#805]
### Is your feature request related to a problem?

Just read the datalad run chapter and get direct questions:

- should the git status be empty before running `datalad run` or will datalad run only save the files created during `datalad run` even if other changes were made before running the code ?
- Can datalad run R scripts, too. If yes, we probably need to run the command in the "project directory" when using RStudio, right? (which may be the code directory)

### Describe the solution you'd like

extend the chapter to  answer these questions

### Describe alternatives you've considered

get a chapter on using datalad with R/Rstudio, (if existent but I did not get to it yet, link it here)

**Comment by adswa** [comment]
Hey, 

> Just read the datalad run chapter and get direct questions:
> 
>     * should the git status be empty before running `datalad run` or will datalad run only save the files created during `datalad run` even if other changes were made before running the code ?

There is a complete section of this in the chapter (2.4): http://handbook.datalad.org/en/latest/basics/101-112-run4.html. In short: ``run`` will by default save everything and hence will refuse to run if the dataset is "dirty". If you want to run ``run`` in a dirty dataset, the ``--explicit`` flag lets you do this. Then, ``run`` will save any file or directory that is specified as an ``--output``. 



> * Can datalad run R scripts, too. If yes, we probably need to run the command in the "project directory" when using RStudio, right? (which may be the code directory)

Sure. I personally don't use R studio so I don't have first-hand experience, but have run R scripts within run many times. Its just that your script or project directory needs to be in a dataset and the run command should be executed in there, too.

Hope that helps :)

**Comment by jcolomb** [comment]
thanks, I will come back to R/Rstudio examples when I got to test it myself... hopefully soon.

**Comment by jcolomb** [comment]
#950 is the result of my Rstudio  work/tests
