### ISSUE TITLE
Mention credential integration with Git

### ISSUE THREAD

**Issue by bpoldrack** [datalad-handbook/book#806]
With DataLad 0.16 it's gonna be possible to let Git query DataLad's credential system and vice versa.

Relevant docs in DataLad itself are to be found at http://docs.datalad.org/credentials.html and - including more details about DataLad's credential system in general - at http://docs.datalad.org/design/credentials.html, once DataLad 0.16 is released.

**Comment by adswa** [comment]
Is there a place you think this would fit in well? And do you have some real-world usage example, for example from ``juseless``, that could serve to illustrate it?

**Comment by adswa** [comment]
ping @bpoldrack
