### ISSUE TITLE
Prepare the 0.16 release

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#808]
DataLad's ``0.16`` release is just around the corner. There are a number of todo's for the handbook's matching ``0.16`` release:

Required content updates:

- [x] #771
- [x] #773
- [x] #787
- [x]  #806

General TODOs:

- [x] Update all examples. This may be dependent on a resolution of https://github.com/datalad/datalad/issues/6258
- [x] check acknowledgements: Is every contributor in ``.allcontributorsrc`` and is their information in ``.zenodo.json``? 
- [x] update the CHANGELOG.
- [ ] Tag the repo with ``0.15``, freeze a ``0.15`` branch
- [ ] Render ``0.15`` in a separate readthedocs build
- [ ] make the release

**Comment by jsheunis** [comment]
I was thinking of contributing with these issues, but they're not required per se:
- https://github.com/datalad-handbook/book/issues/733
- https://github.com/datalad-handbook/book/issues/746

**Comment by adswa** [comment]
oh that would be cool!

**Comment by mslw** [comment]
- [ ] Update [Dataset hosting on Gin](https://handbook.datalad.org/en/latest/basics/101-139-gin.html) to mention `create-sibling-gin`. Right now, one of the previous sections ([Publishing datasets to Git repository hosting](https://handbook.datalad.org/en/latest/basics/101-139-hostingservices.html#how-to-add-a-sibling-on-a-git-repository-hosting-site-the-automated-way)) has distinct subsections for before and after 0.16 and introduces `create-sibling-*` but the GIN walkthrough says that such a function for GIN not available.

**Comment by adswa** [comment]
good catch, thanks @mslw
