### ISSUE TITLE
AssertionError: You need to install datalad

### ISSUE THREAD

**Issue by gaia2510** [datalad-handbook/book#818]
Despite having followed all the installation procedure for datalad for conda (including Git, git-annex), I keep getting the following error when downloading a public dataset:

local_path = si.download_dataset(remote_path='mearec/mearec_test_10s.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gaiaf\anaconda3\envs\si_env\lib\site-packages\spikeinterface\core\datasets.py", line 17, in download_dataset
    assert HAVE_DATALAD, 'You need to install datalad'
AssertionError: You need to install datalad

this is the section of the code from datasets.py:

from .default_folders import get_global_dataset_folder, is_set_global_dataset_folder
try:
    import datalad.api
    from datalad.support.gitrepo import GitRepo
    HAVE_DATALAD = True
except:
    HAVE_DATALAD = False
def download_dataset(repo=None, remote_path=None, local_folder=None, update_if_exists=False,
                     unlock=False):
    assert HAVE_DATALAD, 'You need to install datalad'

**Comment by adswa** [comment]
Hi @gaia2510 thanks for getting in touch. Can you give me a bit more context? It looks like you are using a library (spikeinterface?) that internally relies on DataLad, but it does not ensure that DataLad is installed as a dependency during its own installation. Can you let me know what system you are using and also how you installed spikeinterface? Do you use a virtual environment, or other package managers apart from conda?

**Comment by adswa** [comment]
Hey @gaia2510, did you see my comment? :) I need a bit more context to be able to help here. :)

**Comment by lanzso** [comment]
Hi! I have the same issue. I installed SpikeInterface in PyCharm terminal based on the documentation:
pip install spikeinterface[full]
I followed the getting started tutorial and got the same error when I called the spikeinterface.download_dataset() function. I even installed DataLad separately which was successful but I got the same error.
I use Windows (Windows 10 Pro 21H2) and python 3.9 in Virtualenv environment in PyCharm. 
I really appreciate any help you can provide.

**Comment by adswa** [comment]
hey everyone in this issue, a quick ping: Is someone still having issues? I want to close this issue due to a lack of details for now, but if issues persist or reoccur, please feel free to reopen this issue, or open a new one. Thanks in advance :)
