### ISSUE TITLE
Consider updating Sphinx requirement

### ISSUE THREAD

**Issue by mslw** [datalad-handbook/book#822]
The Sphinx version used by the book is pinned to 2.1.2, while the latest Sphinx version is 4.5. According to commit history, the version was pinned due to #379. However, it might have now led to #821 (in short: we pin Sphinx, but not Jinja2 versions, which led to a mismatch).

Regarding #821, pinning Jinja is a much simpler solution - and, considering that it's *probably* a dependency of Sphinx, and not ours, pinning them both actually makes sense.

Regardless, between Sphinx 2.1.2 and 4.5.0 there were many incompatible changes, some of which might be breaking for us, so an update may be challenging.

But I'm wondering what makes more sense in a long term (staying on Sphinx 2 vs upgrading to 4), and what should an upgrade process look like (build on 4, see if errors appear, and work from there?).

I don't necessarily think we need to update (and certainly not in a hurry), but I'm leaving this thought out there.

**Comment by adswa** [comment]
I'm looking into it, thanks much for the analysis!
