### ISSUE TITLE
New contributors

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#830]
Dear @tguiot, @jhpb7, and @mslw, thanks for your recent contributions to this repository! As the next release is imminent, I would like to invite you to add your name and optionally affiliation and ORCID to the [zenodo.json](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) file in this repository so that you officially appear as a coauthor in https://zenodo.org/record/5726829#.YlbfdvexUUE.
Please add a structured JSON record with your information with a PR to the file, at the second to last author place (i.e., just before Michael Hanke).
Here is an example record:
```json
    {
      "affiliation": "Department of Experimental Psychology, Heinrich-Heine University Düsseldorf, Düsseldorf, Germany",
      "name": "Ort, Eduard",
      "orcid": "0000-0001-5546-3561"
    },
```

If you don't have an affiliation and/or orcid, please don't include the respective line. 

Alternatively, just leave your information as a comment to this issue, and I will include your data :) If you do not wish to be included in the file, it would be great if you could let me know, too, such that I can make the release shortly. Thanks in advance!

**Comment by adswa** [comment]
quick ping to @tguiot

**Comment by tguiot** [comment]
thanks. did it this w-e but forgot to do the pull request. just did now

**Comment by adswa** [comment]
fantastic, thanks for your quick response! :)
