### ISSUE TITLE
Document installation instructions for datalad on M1 macs

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#833]
Relevant initial issue in datalad repo: https://github.com/datalad/datalad/issues/5701

Chat transcript of datalad office hour discussion to help a user install datalad on an M1 mac:

---

Me to Everyone (16:02)
Sorry my connection is crappy
I heard my name
Will try move to better connection
Alex Waite to Everyone (16:06)
The preferred way to use Rosetta at the CLI seems to be: https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/
You basically alias "Terminal" and tell macOS to launch it using Rosetta.
So it's spawned in that env, so all commands will detect the arch as x86.
And then you install homebrew, conda, etc in it.
If rosetta isn't yet installed, you can run the following to install it:
/usr/sbin/softwareupdate –install-rosetta –agree-to-license
Alex Waite to Everyone (16:15)
You can test whether you're in rosetta mode or note by running:
sysctl -n sysctl.proc_translated
(1 is rosetta, 0 is not)
Michael Hanke to Everyone (16:21)
https://wwwimage-secure.cbsstatic.com/thumbnails/photos/w1920/marquee/1033010/template_sp_hero_landscape.jpg
Alex Waite to Everyone (16:22)
:-)
Michael Hanke to Everyone (16:25)
https://anaconda.org/conda-forge/datalad
Alex Waite to Everyone (16:25)
-vvv
conda search datalad
Niels R to Everyone (16:32)
what's the conda version?
Adina Wagner to Everyone (16:33)
conda config --set --env subdir=osx-64
Niels R to Everyone (16:35)
--set subdir osx-64 --env?
Michael Hanke to Everyone (16:35)
https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple
Me to Everyone (16:37)
conda config --env --set subdir osx-arm64
conda config --env --set subdir osx-64
Michael Hanke to Everyone (16:42)
conda install -c conda-forge git-annex
https://anaconda.org/conda-forge/git-annex (only linux)
Alex Waite to Everyone (16:44)
which brew
Michael Hanke to Everyone (16:45)
https://stackoverflow.com/questions/64882584/how-to-run-the-homebrew-installer-under-rosetta-2-on-m1-macbook
Me to Everyone (16:45)
arch -x86_64 brew install git-annex
Alex Waite to Everyone (16:48)
brew search python
Me to Everyone (16:48)
brew doctor could also maybe provide more insight
Me to Everyone (16:52)
https://stackoverflow.com/questions/41113448/homebrew-error-no-formulae-found-in-taps
Alex Waite to Everyone (16:53)
file $(which brew)
Me to Everyone (16:54)
git -C $(brew --repo homebrew/core)
git -C $(brew --repo homebrew/core) checkout master
Michael Hanke to Everyone (16:59)
https://stackoverflow.com/questions/64882584/how-to-run-the-homebrew-installer-under-rosetta-2-on-m1-macbook

---

Also tried:
- dataLad-installer, this runs brew install. Can add -m options, but `auto-build` and `dmg` fails.

Decided at end to try brew installed into usr/local/.

Extra context and further steps to be added here once update received from user.

**Comment by anadiasmaile** [comment]
This was my terminal output during the datalad office hour:

**Comment by anadiasmaile** [comment]
[terminal-output-datalad-installation.txt](https://github.com/datalad-handbook/book/files/8490818/terminal-output-datalad-installation.txt)

**Comment by jsheunis** [comment]
Thanks a lot @anadiasmaile!

**Comment by jsheunis** [comment]
Possible approach for `git-annex` installation on M1 detailed by @fraimondo: https://github.com/fraimondo/csguide-hands-on#problem-3--git-annex-on-m1-mac

**Comment by jsheunis** [comment]
So @mih and @adswa, it seems that the suggested route should be Rosetta and git-annex as per instructions in link above, and datalad installed via pip / conda in a virtual environment? Should the virtual environment be run in the same rosetta terminal?

**Comment by adswa** [comment]
There are two workarounds added to the installation instructions now
