### ISSUE TITLE
remove hardcoded path in py-example code @ YODA principles 6.3.3

### ISSUE THREAD

**Issue by jhpb7** [datalad-handbook/book#840]
### Is your feature request related to a problem?

According to [a thread at neurostars.org](https://neurostars.org/t/can-the-datalad-run-command-of-a-python-script-automatically-save-input-and-output-files/22636/2) we thought that the example python code provided in [Chapter 6.3.3](https://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html#yoda-compliant-analysis-scripts) does not really reflect the YODA principles. The script uses hardcoded inputs inside the python code and the datalad run command gives the same inputs to the script which seem to be ignored.
To me this rather seems like a workaround, as the input to the code is in fact **not** tracked by datalad.

### Describe the solution you'd like

It would be nice if the python example code would get the inputs from _datalad run_ command directly (e.g. with import sys, sys.argv, ...).

**Comment by adswa** [comment]
Oh, that's a fair point, thanks for raising it!

**Comment by adswa** [comment]
My apologies, in a daze of lack of sleep I pushed the fixes to this issue  (18a9617ab03c0dbb8d35dba4eae47ed203374a76..d7c7046b39f79a3d489d5f6daae79d14ded3fdaf) straight to master - they are already up at http://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html and evaded proper review. If you or somebody else spots somethings that's off, please reopen this.
And thanks again for raising this! Very much appreciated
