### ISSUE TITLE
ENH: add publication dependency of `github-lfs` on `github` in gitLFS walkthrough

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#841]
http://handbook.datalad.org/en/latest/basics/101-139-gitlfs.html

Relevant excerpt:

> With this single step it becomes possible to transfer contents to GitHub:
```
$ git annex copy --to=github-lfs file.dat
copy file.dat (to github-lfs...)
ok
(recording state in git...)
```
> and the entire dataset to the same GitHub repository:
```
$ datalad push --to=github
[INFO   ] Publishing <Dataset path=/tmp/test-github-lfs> to github
publish(ok): . (dataset) [pushed to github: ['[new branch]', '[new branch]']]
```

After the above section, we could add a step that describes how to add a publication dependency, such that readers are aware that they can do the above two steps in one afterwards:

```
$ datalad siblings github --publish-depends github-lfs
$ datalad siblings
<add printed output>

$ datalad push --to github
<add printed output, which should show that both dataset and annexed content were pushed>
```

**Comment by adswa** [comment]
oh yes, that's a good idea! thanks for bringing it up. @yarikoptic , I remember git-lfs being your addition so I wanted to check back if you see anything that speaks against it?

**Comment by yarikoptic** [comment]
sounds like a good idea indeed. No show stopper comes to mind (it has been awhile... most likely I just forgot about publish-depends since was not actively using it)
