### ISSUE TITLE
git-annex available for Apple silicon via brew

### ISSUE THREAD

**Issue by ajveltri22** [datalad-handbook/book#858]
Just responding to your request in the handbook to let you know that git-annex is available for M1 Macs on brew. I successfully installed datalad on my M1 Macbook pro with `brew install datalad`. Thanks!

**Comment by adswa** [comment]
Thanks for the issue, @ajveltri22, this is fantastic news! :) @all-contributors please add @ajveltri22 for userTesting

**Comment by adswa** [comment]
@ajveltri22, feel free to add yourself (Name, Affiliation, Orcid if available) to the list of contributors in the [`.zenodo.json`](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) file (at the second to last place, i.e., before Michael Hanke). This file builds the author list at every handbook release for https://doi.org/10.5281/zenodo.6463273
