### ISSUE TITLE
Updates to `main` branch don't make their way to the website

### ISSUE THREAD

**Issue by mslw** [datalad-handbook/book#873]
- It seems to me that the readthedocs build for version "latest" still tries to look at the `master` branch (but it was renamed to `main` recently): [RTD versions](https://readthedocs.org/projects/datalad-handbook/versions/).
- The last build for version "latest" is from 2 weeks ago, and there have been only PR builds since, although these PRs were merged: [RTD builds](https://readthedocs.org/projects/datalad-handbook/builds/).
- This can be seen e.g. for the [installation and configuration](http://handbook.datalad.org/en/latest/intro/installation.html) page which saw recent changes (compare e.g. the bits including `conda update` or `datalad-installer git-annex` versus the source).
- I can't adjust the RTD project myself

**Comment by adswa** [comment]
Thanks much! Should work now (I selected "default branch", but it needed to be explicitly set to ``main`` it seems). I also gave you maintainer access :+1:
http://handbook.datalad.org/en/latest/intro/installation.html#windows-10
