### ISSUE TITLE
Explain how to search through openneuro through datalad

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#874]
### Is your feature request related to a problem?

Not exactly related to a problem but more like a tip that can help people find the dataset they are looking for on openneuro.

I have to tell this to a couple of people already so I suspect others may benefit from it too.

### Describe the solution you'd like

Adding to the openneuro page http://handbook.datalad.org/en/latest/usecases/openneuro.html

Something along those lines.

```bash
datalad install /// # install superdataset
cd datasets.datalad.org
datalad install openneuro # install openneuro subdataset
datalad install openneuro/ds* # install all openneuro datasets (this takes time)
```

Then you can use your usual command `ls`, `find`, `grep`  to search what you are looking for.

### Describe alternatives you've considered

Well the openneuro search bar in the GUI can get you sort of there but not as easy to browse.

**Comment by christinerogers** [comment]
fwiw, I sent a "support" inquiry to the OpenNeuro website (using their form) suggesting it... let's see what sticks?

**Comment by adswa** [comment]
Heya, better late than never :) thanks for the suggestion and patience, this is done in #921
