### ISSUE TITLE
Bump "minimal supported DataLad version" and adjust contents

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#888]
"Versioning" has proven to be more difficult in the narrative-based way the handbook is written (see #789). Currently, the handbooks index page says that the handbook requires at least DataLad version 0.12, and specific functionality adds rather ad-hoc descriptions of version changes or requirements (e.g., RIA requires 0.13.2, the chapter on publishing distinguishes behavior prior and after the 0.16 release). 

While the total number of these "in version X use this, in version Y use that" is still low (I hope), the practice behind it is unmaintainable. #789 has investigated some of the difficulties of being strictly "most recent version only", so my current take is that the handbook will probably never be perfect in that regard. However, given that the handbook is 3.5 years old already, I think it is justifiable to make a cut/version bump. In practice, I would propose the following:

- Set a higher "minimum required datalad version" than 0.12. 
- Remove warnings on features about any version requirements that are lower than the new minimum required version
- pull these changes in to be effective with the next handbook release

**Comment by mih** [comment]
My vote would be for a minimum DataLad version of 0.17. For the future, I would I would focus on whatever is the latest version, and aggressively prune historical info. Older handbook versions remain accessible, but we need not maintain information on obsolete behavior.

**Comment by adswa** [comment]
I will go through the handbook and do this.
