### ISSUE TITLE
Make use of readthedocs analytics

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#889]
Readthedocs is amazing in many regards, but something that is really cool is that they provide analytics. If someone has a love for data, it would be super fancy to have a CRON job or script that pulls https://readthedocs.org/dashboard/datalad-handbook/traffic-analytics/ and https://readthedocs.org/dashboard/datalad-handbook/search-analytics/ and visualizes it, e.g., in the repo README, or as a report similar to the Datalad Health update. We can find out which pages are visited most often, track handbook reads over time to have a metric of impact, or analyze search terms to prioritize working on content that is most useful to readers.

**Comment by adswa** [comment]
Here's one example download from https://readthedocs.org/dashboard/datalad-handbook/traffic-analytics: It contains the columns "Date", "Version", "Path", and "Views". The rows show an entry for any file that has had at least one view on the given day.
[readthedocs_traffic_analytics_datalad-handbook_2022-09-15_2022-12-14.csv](https://github.com/datalad-handbook/book/files/10227089/readthedocs_traffic_analytics_datalad-handbook_2022-09-15_2022-12-14.csv)

Its surprising that there are also view of old versions of the docs, e.g., 0.13 or even 0.12!



And here's a sample search analytic from https://readthedocs.org/dashboard/datalad-handbook/search-analytics/. It has "Created Date", "Query", and "Total Results" as columns, and the rows contain an entry for each term that was queried:
[readthedocs_search_analytics_datalad-handbook_2022-09-15_2022-12-14.csv](https://github.com/datalad-handbook/book/files/10227171/readthedocs_search_analytics_datalad-handbook_2022-09-15_2022-12-14.csv)

it contains very interesting search terms, hinting at content people search for frequently, as well as the total counts of results users found, and thus also hinting at content people need, but won't find yet.

**Comment by jsheunis** [comment]
We can look into https://mechanize.readthedocs.io/en/latest/index.html to automate exporting / downloading the analytics. HT @mih

**Comment by jsheunis** [comment]
Ping https://github.com/datalad-handbook/book/issues/897
