### ISSUE TITLE
Data analytics automated extraction (ReadTheDocs)

### ISSUE THREAD

**Issue by Manukapp** [datalad-handbook/book#897]
### What is the goal?

Extract meaningful data from ReadTheDocs analytics on traffic and search queries in the Datalad Handbook.
To achieve automation, it is suggested to use mechanize python library.

### Solution Descriptions

Firstly, because all analytics are restrained to a 30 day window there is a need to create a mechanism to store the monthly results (i.e. Dec_2022) to track yearly progression.

Importantly, as mentioned in #889, two types of analytics are available. Traffic - composed of 4 columns: _"Date", "Version", "Path" "Views"_ - and Search - 3 columns: _"Date"_, _"Query"_, _"Total Results"_

Secondly, here are a list of hypotheses about the data with potential approaches.

**Search Analytics per 30 days**

- what are the top 5-10 most popular search queries?
Counting in _"Query"_ most prominent search
 
- Which are neuro-related?
In _"Query"_ column.
Keywords: "mri" "neuroimaging" "neuro" "bids" "nifti" "dicom" "human connectome project"  "hcp""openneuro" "osf"

- Which are datalad command?
In _"Query"_ column.
key words:  "datalad" "save" "get" "delete" "create" "download-url" etc

- Which are computational concepts?
In _"Query"_ column.
KW: "containers" "metadata" "extension" "yoda" "ssh" "docker" "import" "zip"
In _"Query"_ column.
- Which are cloud & storage related?
In _"Query"_ column.
KW: "git" "annex" "zenodo" "ria" "multiple source" "multiple location" "google" "origin" "jupyter" "logging" "archive"

- Which are about code functionalities?
In _"Query"_ column.
KW: "python" "path" "import" "install" "text2git" "sys.path" 

**Traffic Analytics per 30 days**

- What are the top 10 most popular pages?
Summing numbers in _"Views"_ of same names in _"Paths"_, and listing by greater to lesser
- Total Handbook view count?
Summing all numbers in _"Views"_

- Most popular basics chapter?
Summing all "/basics/" in _"Paths"_ and listing by greater to lesser 

- Most popular intro chapter?
Summing numbers in _"Views"_ "/intro/" in _"Paths"_ and listing by greater to lesser 

- Most popular beyond_basics chapter?
Summing numbers in _"Views"_ "/beyond_basics/" in _"Paths"_ and listing by greater to lesser 

- Most popular usecases?
Summing numbers in _"Views"_ for "/usecases/" in _"Paths"_ and listing by greater to lesser 

- Glossary total count
Sum Views glossary in _"Paths"_ only

- Ratio of using previous handbook version relative to latest.
Counting all non-"latest" (NL) version and dividing: NL/(latest-NL)

_**Future directions**_
**Correlations between traffic & search analytics?**
E.g. correlation between search query categories mentioned in above section with glossary page landing.

**Comment by adswa** [comment]
Those are nice aims for the scraped analytics data! If you're looking for a technical solution to generate those metrics from the data, take a look at [pandas](https://pandas.pydata.org/docs/index.html). Its a powerful python library often used for those data sciency tasks.

**Comment by Manukapp** [comment]
```
import mechanize

br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_redirect(mechanize.HTTPRedirectHandler)
br.addheaders = [('User-agent', 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1')]
br.open("https://readthedocs.org/")
# follow second link with element text matching regular expression
br._factory.is_html = True
base_url = br.geturl()

print(base_url)

br.open(base_url + "accounts/login/")
print(br.title())

br.select_form(nr=0)
print(br.form)
br.form['login'] = "Leodoc"
br.form['login'] = "Earthwars1"
response1 = br.submit()
print(br.geturl())

Inside = "https://readthedocs.org/dashboard/datalad-handbook/traffic-analytics/"
br.open(Inside)
print(br.geturl())
```

**Comment by mih** [comment]
The following code does downloading the traffic analytics data for me

```py
import mechanize

class ReadTheDocs:
    traffic_url = "https://readthedocs.org/dashboard/datalad-handbook/traffic-analytics/"

    def __init__(self, username, password):
        br = mechanize.Browser()
        br.set_handle_robots(False)
        br.set_handle_redirect(mechanize.HTTPRedirectHandler)
        br.addheaders = [
            ('User-agent',
             'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1')
        ]
        br.open("https://readthedocs.org")
        # follow second link with element text matching regular expression
        br._factory.is_html = True
        base_url = br.geturl()
        # login
        br.open(base_url + "/accounts/login/")
        # find first form
        br.select_form(nr=0)
        br.form['login'] = username
        br.form['password'] = password
        br.submit()
        # keep browser running
        self.br = br

    def get_traffic_analytics(self):
        self.br.open(ReadTheDocs.traffic_url)
        # the download is done via a form button. find the form
        self.br.select_form(nr=0)
        # press the buttom
        r = self.br.submit()
        # download CSV data as text
        return r.get_data()
```
