### ISSUE TITLE
Distinguish prompt/code lines from output in code examples

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#9]
Not doing that can be confusing, in particular in longer examples. I propose:

```rst
.. code-block:: bash

   % ls .
   one
   two
   three
```

and

```rst
.. code-block:: python

   >>> print('this')
   this
```

**Comment by adswa** [comment]
very good idea, thx!

**Comment by adswa** [comment]
I would propose to change ``%`` to ``$`` in the bash code-blocks.

**Comment by mih** [comment]
Yes, I agree. `$` is also the only character recognized by the example extension.

**Comment by adswa** [comment]
This can be closed I think, using ``$`` for code is established now.
