### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by candleindark** [datalad-handbook/book#937]
### Current behavior

The user guide for creating a metadata extractor alluded to in https://github.com/datalad-handbook/book/blob/main/docs/beyond_basics/101-181-metalad.rst#creating-your-own-extractor is currently missing.

### Operating system

MacOS

### Browser

- Chrome

**Comment by adswa** [comment]
Thx! I hope my commit to the ``main`` branch just now fixed this (I'll check once it is built).
