### ISSUE TITLE
Suggested edits for https://handbook.datalad.org/en/latest/usecases/datastorage_for_institutions.html

### ISSUE THREAD

**Issue by jcf2** [datalad-handbook/book#949]
Suggested edits for https://handbook.datalad.org/en/latest/usecases/datastorage_for_institutions.html

Principle investigators --> Principal investigators

prides itself with --> prides itself on

not formerly trained --> not formally trained

does not only lead to --> not only leads to

analyses projects, analyses datasets: would use "analysis"

ones scientific insights --> one's scientific insights

complimentary but independent --> complementary but independent

institutes compute cluster --> institute's compute cluster

compute clusters' head node --> compute cluster's head node

thus were pristine --> thus where pristine

should end up in --> should end up

One aspect of the problem are: should be "is"

and ease collaboration --> and easing collaboration

**Comment by adswa** [comment]
Hi @jcf2, thanks for these suggestions for typo fixes! They would be nice to have, would you like to propose them as a pull request?

**Comment by mslw** [comment]
Thanks @jcf2, great suggestions. I hope I'm not stealing your thunder, but given that it's been more than two weeks I felt justified in opening a pull request that applies these changes.

**Comment by jcf2** [comment]
Thanks everyone. I lost track of this (and was kind of getting acquainted with GitHub). I appreciate the help.
