### ISSUE TITLE
Update DVC use case for DVC 3+

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#965]
It looked like the DVC section finally broke, Appveyor isn't happy. I need to go through the DVC walkthrough and update it to the latest commands, or pin the DVC version I think

**Comment by mslw** [comment]
Looks like DVC 3.0 came out last week with some breaking changes, but the required update may be very small

> dvc run command has been removed, use stage add --run instead

https://github.com/iterative/dvc/releases/tag/3.0.0

<hr>

More recent appveyor runs also show a more basic failure which looks like a problem with appveyor itself?

**Comment by adswa** [comment]
I think its that a the release note of a PPA repo has changed and its complaining, similar to here: https://github.com/datalad/datalad-next/pull/428
