### ISSUE TITLE
Link for more info regards `> git config --global filter.annex.process "git-annex filter-process"`

### ISSUE THREAD

**Issue by da5nsy** [datalad-handbook/book#972]
### Is your feature request related to a problem?

Currently, the text [here](https://handbook.datalad.org/en/latest/intro/installation.html#conda) reads:
> For performance improvements, regardless of which installation method you chose, we recommend to also set the following git-annex configuration:

It would be nice to have a link to somewhere for more info (_why_ do you recommend this?)

**Comment by adswa** [comment]
let me dig...

**Comment by adswa** [comment]
Let me dump a few links that I found:

- I believe it started with this issue: https://github.com/datalad/datalad/issues/5994
- It resulted in a corresponding git-annex issue: https://git-annex.branchable.com/projects/datalad/bugs-done/Windows__58___substantial_per-file_cost_for___96__add__96__/
- I pasted some benchmarking into a comment at https://git-annex.branchable.com/todo/incremental_hashing_for_add/.
- The plan to add it to the handbook was based on https://github.com/datalad/datalad/pull/6245.

I'm inclined to link the original git-annex issue for background information. It has the most comprehensive infos, and its also a likely place to see an update when git-annex makes it a default on windows.

**Comment by da5nsy** [comment]
Awesome, thanks! ❤️

**Comment by da5nsy** [comment]
I'll leave this to you to PR @adswa, since you know the history better than I! (Though do shout if I can help)
