### ISSUE TITLE
Employ wikimedia URL shortener for wikipedia links?

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#991]
The current handbook has 64 unique links to wikipedia. The all start with `https://en.wikipedia.org/wiki/` hence there minimum length is 30+ chars. This is a non-issue for the HTML handbook. However in the PDF version, long URLs are a visual and formatting problem.

What about switching to shortened URLs for wikipedia/media?

Wikimedia provides a dedicated service for that https://meta.wikimedia.org/wiki/Wikimedia_URL_Shortener

Using this service would create URLs like https://w.wiki/_vqBu

This means that remain clearly recognizable as wikipedia/media URLs (and to not turn into a tracker blackhole).

It might still be desirable to make this switch for the book/PDF version alone.

**Comment by mslw** [comment]
Seeing that it's an official Wikimedia shortener, I would be ok with that.

However, if the Read The Docs PDF build is anything to go by, the links are turned into footnotes containing just the link address, so I doubt that line width overflow would be an issue? And on that note, the non-shortened links read more naturally to me, as they contain the page title (and real words).
