### ISSUE TITLE
Sanitize URLs

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#992]
I have written a helper to check handbook URLs for a set of issues that I would consider worthwhile addressing.

The following issues are recognized:
- `redundant-trailing-slash`
    The same URL, but without the trailing slash, is used elsewhere
    in the book.
- `unshorted-youtube-link`
    This could be a https://youto.be/ style short URL
- `needless-trailing-slash`
    A URL without a path component. It should need nbow trailing slash
- `permanent-redirect`
    A permanent redirect is reported for a URL

Here is a per-file list of URL issues in the current handbook sources:

- `docs/glossary.rst`:
  - *line 155*: `permanent-redirect` [https://docs.github.com/en/github/getting-started-with-github/fork-a-repo - permanently to https://docs.github.com/en/get-started/quickstart/fork-a-repo]
  - *line 163*: `permanent-redirect` [https://try.github.io - permanently to https://docs.github.com/en/get-started/quickstart/set-up-git]
  - *line 363*: `permanent-redirect` [https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent - permanently to https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent]
- `docs/intro/howto.rst`:
  - *line 293*: `redundant-trailing-slash` [https://xkcd.com/1205/]
- `docs/contributing.rst`:
  - *line 376*: `needless-trailing-slash` [https://allcontributors.org/]
- `docs/intro/windows.rst`:
  - *line 32*: `permanent-redirect` [https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later - permanently to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later]
  - *line 32*: `permanent-redirect` [https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation - permanently to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation]
  - *line 102*: `permanent-redirect` [https://www.gnu.org/software/octave/ - permanently to https://octave.org/]
  - *line 130*: `permanent-redirect` [https://docs.microsoft.com/en-us/windows/wsl/faq - permanently to https://learn.microsoft.com/en-us/windows/wsl/faq]
  - *line 154*: `needless-trailing-slash` [https://forums.linuxmint.com/]
  - *line 162*: `permanent-redirect` [https://uk.pcmag.com/adobe-photoshop-cc/124238/how-to-make-the-switch-from-windows-to-linux - permanently to https://uk.pcmag.com/linux/124238/how-to-make-the-switch-from-windows-to-linux]
- `docs/extension_pkgs.rst`:
  - *line 67*: `redundant-trailing-slash` [https://osf.io/]
  - *line 67*: `needless-trailing-slash` [https://osf.io/]
  - *line 73*: `redundant-trailing-slash` [https://www.ukbiobank.ac.uk//]
  - *line 78*: `needless-trailing-slash` [https://www.xnat.org/]
  - *line 125*: `redundant-trailing-slash` [https://github.com/datalad/datalad-extensions/]
- `docs/basics/101-105-install.rst`:
  - *line 91*: `permanent-redirect` [https://github.com/datalad-datasets/longnow-podcasts.git - permanently to https://github.com/datalad-datasets/longnow-podcasts]
  - *line 446*: `permanent-redirect` [https://longnow.org/membership - permanently to https://longnow.org/join/]
- `docs/basics/101-127-yoda.rst`:
  - *line 22*: `permanent-redirect` [http://phdcomics.com/comics/archive.php?comicid=1531 - permanently to https://phdcomics.com/comics/archive.php?comicid=1531]
  - *line 184*: `permanent-redirect` [https://travis-ci.org - permanently to https://www.travis-ci.com/]
  - *line 453*: `permanent-redirect` [https://the-turing-way.netlify.app/welcome - permanently to https://the-turing-way.netlify.app/index.html]
- `docs/basics/101-130-yodaproject.rst`:
  - *line 623*: `permanent-redirect` [https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token - permanently to https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens]
- `docs/basics/101-133-containersrun.rst`:
  - *line 105*: `permanent-redirect` [https://sylabs.io/guides/3.4/user-guide/installation.html - permanently to https://docs.sylabs.io/guides/3.4/user-guide/installation.html]
  - *line 134*: `permanent-redirect` [https://sylabs.io/guides/3.4/user-guide/build_a_container.html - permanently to https://docs.sylabs.io/guides/3.4/user-guide/build_a_container.html]
- `docs/basics/101-137-history.rst`:
  - *line 729*: `permanent-redirect` [https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line - permanently to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line]
- `docs/basics/101-138-sharethirdparty.rst`:
  - *line 24*: `permanent-redirect` [https://dropbox.com - permanently to https://www.dropbox.com/]
  - *line 24*: `permanent-redirect` [https://google.com - permanently to https://www.google.com/]
  - *line 44*: `permanent-redirect` [https://git-lfs.github.com - permanently to https://git-lfs.com/]
  - *line 72*: `permanent-redirect` [https://gitea.io/en-us - permanently to https://about.gitea.com/]
- `docs/basics/101-139-dropbox.rst`:
  - *line 18*: `permanent-redirect` [https://github.com/DanielDent/git-annex-remote-rclone - permanently to https://github.com/git-annex-remote-rclone/git-annex-remote-rclone]
  - *line 293*: `permanent-redirect` [http://git-annex.branchable.com/special_remotes - permanently to https://git-annex.branchable.com/special_remotes/]
- `docs/basics/101-139-gitlfs.rst`:
  - *line 6*: `permanent-redirect` [https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage - permanently to https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage]
  - *line 51*: `permanent-redirect` [https://docs.github.com/en/github/managing-large-files/versioning-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository - permanently to https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository]
- `docs/basics/101-139-hostingservices.rst`:
  - *line 63*: `permanent-redirect` [https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent - permanently to https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent]
  - *line 336*: `redundant-trailing-slash` [https://developer.github.com/changes/2020-02-14-deprecating-password-auth/]
- `docs/basics/101-139-privacy.rst`:
  - *line 49*: `redundant-trailing-slash` [https://git-annex.branchable.com/git-annex-wanted/]
- `docs/basics/101-139-s3.rst`:
  - *line 6*: `needless-trailing-slash` [https://aws.amazon.com/]
  - *line 39*: `needless-trailing-slash` [https://console.aws.amazon.com/]
  - *line 158*: `redundant-trailing-slash` [https://git-annex.branchable.com/tips/public_Amazon_S3_remote/]
  - *line 188*: `redundant-trailing-slash` [https://git-annex.branchable.com/special_remotes/]
- `docs/basics/101-180-FAQ.rst`:
  - *line 345*: `redundant-trailing-slash` [https://git-annex.branchable.com/]
  - *line 345*: `needless-trailing-slash` [https://git-annex.branchable.com/]
  - *line 345*: `needless-trailing-slash` [https://www.datalad.org/]
- `docs/beyond_basics/101-146-providers.rst`:
  - *line 94*: `permanent-redirect` [https://tools.ietf.org/html/rfc6750 - permanently to https://datatracker.ietf.org/doc/html/rfc6750]
  - *line 220*: `permanent-redirect` [https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token - permanently to https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens]
- `docs/beyond_basics/101-168-dvc.rst`:
  - *line 47*: `permanent-redirect` [https://github.com/datalad-handbook/data-version-control.git - permanently to https://github.com/datalad-handbook/data-version-control]
- `docs/beyond_basics/101-170-dataladrun.rst`:
  - *line 8*: `redundant-trailing-slash` [https://www.ukbiobank.ac.uk/]
  - *line 8*: `needless-trailing-slash` [https://www.ukbiobank.ac.uk/]
- `docs/beyond_basics/101-182-catalog.rst`:
  - *line 14*: `unshorted-youtube-link` [https://www.youtube.com/watch?v=4GERwj49KFc]
- `docs/code_from_chapters/ABCD.rst`:
  - *line 166*: `permanent-redirect` [https://studyforrest.org - permanently to https://www.studyforrest.org/]
  - *line 408*: `redundant-trailing-slash` [https://www.docker.com/]
  - *line 408*: `needless-trailing-slash` [https://www.docker.com/]
  - *line 408*: `permanent-redirect` [https://sylabs.io/guides/3.5/user-guide/ - permanently to https://docs.sylabs.io/guides/3.5/user-guide/]
- `docs/code_from_chapters/DLBasicsMPI.rst`:
  - *line 205*: `redundant-trailing-slash` [http://datasets.datalad.org/]
  - *line 205*: `needless-trailing-slash` [http://datasets.datalad.org/]
  - *line 394*: `needless-trailing-slash` [http://www.image-net.org/]
  - *line 394*: `permanent-redirect` [http://www.image-net.org/ - permanently to https://image-net.org/]
- `docs/code_from_chapters/OHBM_OSR.rst`:
  - *line 111*: `unshorted-youtube-link` [https://www.youtube.com/watch?v=ix3lC6HGo-Q&feature=youtu.be]
- `docs/code_from_chapters/dgpa.rst`:
  - *line 225*: `redundant-trailing-slash` [https://github.com/ReproNim/containers/]
  - *line 225*: `redundant-trailing-slash` [https://www.repronim.org/]
  - *line 225*: `needless-trailing-slash` [https://www.repronim.org/]
  - *line 287*: `redundant-trailing-slash` [https://gin.g-node.org/]
  - *line 287*: `needless-trailing-slash` [https://gin.g-node.org/]
  - *line 351*: `needless-trailing-slash` [http://singularity.lbl.gov/]
  - *line 351*: `permanent-redirect` [http://singularity.lbl.gov/ - permanently to https://singularity.lbl.gov/]
- `docs/code_from_chapters/neurohackademy.rst`:
  - *line 253*: `redundant-trailing-slash` [https://openneuro.org/]
  - *line 253*: `needless-trailing-slash` [https://openneuro.org/]
- `docs/extension_create.rst`:
  - *line 37*: `needless-trailing-slash` [https://www.appveyor.com/]
  - *line 39*: `needless-trailing-slash` [https://codeclimate.com/]
  - *line 72*: `redundant-trailing-slash` [https://readthedocs.org/]
  - *line 72*: `needless-trailing-slash` [https://readthedocs.org/]
- `docs/intro/executive_summary.rst`:
  - *line 96*: `permanent-redirect` [https://owncloud.org - permanently to https://owncloud.com/]
- `docs/intro/filenaming.rst`:
  - *line 128*: `permanent-redirect` [https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces - permanently to https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces]
  - *line 178*: `redundant-trailing-slash` [https://github.com/datalad-handbook/book/issues/new/]
- `docs/intro/installation.rst`:
  - *line 165*: `permanent-redirect` [https://docs.microsoft.com/en-us/windows/wsl/install-win10 - permanently to https://learn.microsoft.com/en-us/windows/wsl/install]
  - *line 279*: `needless-trailing-slash` [http://p7zip.sourceforge.net/]
  - *line 279*: `permanent-redirect` [http://p7zip.sourceforge.net/ - permanently to https://p7zip.sourceforge.net/]
- `docs/intro/philosophy.rst`:
  - *line 150*: `redundant-trailing-slash` [https://figshare.com/]
  - *line 150*: `needless-trailing-slash` [https://figshare.com/]
- `docs/usecases/HCP_dataset.rst`:
  - *line 265*: `redundant-trailing-slash` [https://research.cs.wisc.edu/htcondor/]
  - *line 303*: `redundant-trailing-slash` [http://store.datalad.org/]
  - *line 303*: `needless-trailing-slash` [http://store.datalad.org/]
  - *line 407*: `redundant-trailing-slash` [https://keyring.readthedocs.io/en/latest/]
- `docs/usecases/collaborative_data_management.rst`:
  - *line 81*: `needless-trailing-slash` [http://studyforrest.org/]
  - *line 81*: `permanent-redirect` [http://studyforrest.org/ - permanently to https://www.studyforrest.org/]
- `docs/usecases/encrypted_annex.rst`:
  - *line 13*: `redundant-trailing-slash` [https://git-annex.branchable.com/encryption/]
  - *line 59*: `needless-trailing-slash` [https://gnupg.org/]
- `docs/usecases/ml-analysis.rst`:
  - *line 59*: `redundant-trailing-slash` [https://numpy.org/]
  - *line 59*: `redundant-trailing-slash` [https://pandas.pydata.org/]
  - *line 59*: `redundant-trailing-slash` [https://scikit-image.org/]
  - *line 59*: `redundant-trailing-slash` [https://scikit-learn.org/stable/]
  - *line 59*: `needless-trailing-slash` [https://numpy.org/]
  - *line 59*: `needless-trailing-slash` [https://pandas.pydata.org/]
  - *line 59*: `needless-trailing-slash` [https://scikit-image.org/]
  - *line 74*: `redundant-trailing-slash` [https://realpython.com/python-data-version-control/]
- `docs/usecases/openneuro.rst`:
  - *line 41*: `needless-trailing-slash` [https://openfmri.org/]
- `docs/usecases/reproducible-paper.rst`:
  - *line 21*: `redundant-trailing-slash` [https://github.com/datalad-handbook/repro-paper-sketch/]
  - *line 446*: `permanent-redirect` [http://github.com/psychoinformatics-de/paper-remodnav/ - permanently to https://github.com/psychoinformatics-de/paper-remodnav/]
- `docs/usecases/reproducible_neuroimaging_analysis.rst`:
  - *line 86*: `needless-trailing-slash` [https://www.dicomstandard.org/]
  - *line 86*: `needless-trailing-slash` [https://nifti.nimh.nih.gov/]
  - *line 154*: `redundant-trailing-slash` [https://singularity-hub.org/]
  - *line 154*: `needless-trailing-slash` [https://singularity-hub.org/]
  - *line 253*: `needless-trailing-slash` [http://fsl.fmrib.ox.ac.uk/]
- `docs/usecases/reproducible_neuroimaging_analysis_simple.rst`:
  - *line 53*: `needless-trailing-slash` [https://legacy.openfmri.org/]
  - *line 97*: `redundant-trailing-slash` [https://bids.neuroimaging.io/]
  - *line 97*: `needless-trailing-slash` [https://bids.neuroimaging.io/]
- `docs/usecases/using_globus_as_datastore.rst`:
  - *line 8*: `redundant-trailing-slash` [https://www.globus.org/]
  - *line 8*: `needless-trailing-slash` [https://conp.ca/]
  - *line 8*: `needless-trailing-slash` [https://www.globus.org/]
  - *line 68*: `needless-trailing-slash` [https://git-scm.com/]
  - *line 155*: `needless-trailing-slash` [https://orcid.org/]

**Comment by Remi-Gau** [comment]
Interesting.
I may need to deal with the permanent redirection of url some bids repo.
Care to share your little helper?

**Comment by mih** [comment]
It is included in https://github.com/datalad-handbook/book/pull/994
